ilastik/ilastik

ilastik/shell/gui/ilastikShell.py
ilastik/workflow.py

Adds support for workflow menus.

Workflow menus

---

ilastik/shell/gui/ilastikShell.py

Example implementation of request #1074. For a non-debug implementation we would probably want something like a status bar icon.

adds option to hide applets to debug menu

---

tests/helpers/shellGuiTestCaseBase.py

fixed import in tests

---

ilastik/applets/objectClassification/objectClassificationGui.py

fixes #1043 (BadObjectsDialog in ObjectClassification)

---

ilastik/applets/tracking/base/trackingBaseGui.py

... was already done for Manual Tracking.

Fix #1025 Initial centering in Automatic Tracking workflow.

---

ilastik/workflows/carving/carvingGui.py
ilastik/workflows/carving/opCarving.py
ilastik/workflows/carving/watershed_segmentor.py

- seg and seeds will be removed after saving

minor carving update

---

ilastik/workflows/pixelClassification/pixelClassificationWorkflow.py
ilastik_main.py

Added the following command-line arguments:
* trees-number: Number of trees for Vigra RF classifier.
* variable-importance-path: Location of variable-importance table.
* label-proportion: Proportion of feature-pixels used to train the classifier.

Added Parameter-Optimization Command Line Arguments

---

ilastik/applets/tracking/base/opTrackingBase.py
ilastik/applets/tracking/base/trackingBaseDataExportApplet.py
ilastik/applets/tracking/base/trackingBaseDataExportGui.py
ilastik/widgets/exportObjectInfoDialog.py
ilastik/widgets/exportObjectInfoDialog.ui
ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py

Fix tracking export behaviour

---

ilastik/applets/tracking/base/opTrackingBase.py
ilastik/applets/tracking/conservation/conservationTrackingApplet.py
ilastik/applets/tracking/conservation/opConservationTracking.py
ilastik/applets/trackingFeatureExtraction/trackingFeatureExtractionApplet.py
ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py

Added batch processing to conservation tracking and enabled multi lane processing in conservation tracking workflow.

Added batch processing to conservation tracking

---

ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
tests/test_applets/conservationTracking/testConservationTrackingHeadless.py

Added headless mode capabilities to the conservation tracking workflow, and included a headless mode unit test. 
In order to run the unit test, you have to download the following files from the ilastik_testdata repository:
* miceConservationTracking.ilp
* mice.h5
* mice_prediction.h5

Added headless mode processing to the conservation tracking workflow

---

ilastik/applets/objectClassification/objectClassificationGui.py

propagate computed feture names change

---

ilastik/applets/objectClassification/opObjectClassification.py

On the `execute()` function of `OpObjectPredict`, object feature computation and object prediction was previously done one frame at a time, and now it can be done in parallel.

opObjectClassification: Object extraction and prediction can now be done in parallel

---

ilastik/applets/objectExtraction/objectExtractionSerializer.py
ilastik/applets/objectExtraction/opObjectExtraction.py
ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py
ilastik/applets/trackingFeatureExtraction/trackingFeatureExtractionSerializer.py

Replaced `opCompressedCache` with `OpBlockedArrayCache` (with the compression flag enabled).

Replaced opCompressedCache with opBlockedArrayCache

---

ilastik/applets/multicut/opMulticut.py

Making nifty based multicut solvers available.
Not tested in any way yet.

multicut: Added nifty based solvers

---

ilastik/applets/tracking/conservation/opConservationTracking.py

Added calls to the HyTra pipeline on the `Track()` function.

opConservationTracking: Added calls to the HyTra pipeline on the Track() function

---

ilastik/applets/tracking/conservation/opConservationTracking.py

Fixed issue with hardcoded shape.

opConservationTracking: Fixed issue with hardcoded shape

---

ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py

If you switch to the object count classification applet, it still shows 25 features selected, but runs with 5.

do not take 2d features for 3d data in tracking

---

ilastik/applets/thresholdTwoLevels/drawer.ui
ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py

add a colored square to the channel selection widget

---

ilastik/applets/tracking/annotations/annotationsGui.py
ilastik/applets/tracking/annotations/drawer.ui
ilastik/applets/tracking/annotations/opAnnotations.py
ilastik/applets/tracking/structured/opStructuredTracking.py
ilastik/applets/tracking/structured/structuredTrackingGui.py
ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py

It would be good if this makes it into the next release (rc8)

Learning: fixes #1276

---

ilastik/applets/labeling/labelingGui.py
ilastik/applets/objectClassification/objectClassificationGui.py
ilastik/applets/objectClassification/opObjectClassification.py

triggers live update mode for the  user to see the changes
remove lablel also triggers live update mode

fixes #1352 clear label code added

---

ilastik/applets/autocontextClassification/autocontextClassificationSerializer.py
ilastik/applets/batchProcessing/batchProcessingApplet.py
ilastik/applets/blockwiseObjectClassification/opBlockwiseObjectClassification.py
ilastik/applets/counting/countingGuiBoxesInterface.py
ilastik/applets/counting/countingOperators.py
ilastik/applets/counting/countingSerializer.py
ilastik/applets/counting/countingsvr.py
ilastik/applets/dataSelection/dataSelectionApplet.py
ilastik/applets/deviationFromMean/opDeviationFromMean.py
ilastik/applets/featureSelection/featureSelectionGui.py
ilastik/applets/layerViewer/layerViewerGui.py
ilastik/applets/objectExtraction/opObjectExtraction.py
ilastik/applets/splitBodyCarving/splitBodyCarvingGui.py
ilastik/applets/tracking/annotations/annotationsGui.py
ilastik/applets/tracking/manual/manualTrackingGui.py
ilastik/applets/trackingFeatureExtraction/trackingFeatures.py
ilastik/shell/gui/ilastikShell.py
ilastik/widgets/exportObjectInfoDialog.py
ilastik/workflows/carving/splitBodyCarvingWorkflow.py
ilastik/workflows/objectClassification/objectClassificationWorkflow.py
ilastik/workflows/pixelClassification/pixelClassificationWorkflow.py
tests/bin/generate_test_data.py
tests/test_applets/blockwiseObjectClassification/testOpBlockwiseObjectClassification.py
tests/test_applets/objectClassification/testTransferLabels.py

**Tag**: py2to3_v0.2
**Details**: PEP238 support for integer division using future import division.
**Test status**:
- Most of the changes tested - list attached ([v1.2_Overall_result.xlsx](https://github.com/ilastik/volumina/files/461749/v1.2_Overall_result.xlsx))
- unit tests  
- manual invocation of application; and/or 
- python -3 switch
- Some changes could not be reached and are asserted <br \>
- Testing of Automatic tracking is pending and shall be taken up later along with HyTra framework - see comment from @chaubold (https://github.com/ilastik/ilastik/pull/1329)

Py2to3 ilastik

---

ilastik/applets/multicut/opMulticut.py

Minimal changes to adapt to the new nifty syntax, not tested yet.

opMulticut: Updated to nifty multicut solvers to new syntax

---

ilastik/widgets/exportObjectInfoDialog.py

defines match before using it

---

benchmarks/objectExtractionRunningTime.py
ilastik/applets/objectExtraction/opObjectExtraction.py
ilastik/utility/exportFile.py
tests/test_applets/objectExtraction/testOptimization.py

Object extraction is now done in parallel. 
This PR also includes a script to compare the running-time of the object extraction operator against a simplified version of the same operator in order to figure out the running-time of the overhead (caches, plugin system, labelling, etc). This script is found in the `benchmarks` folder.

Object extraction optimization

---

ilastik/applets/tracking/conservation/opConservationTracking.py

Suggested fix for #1387, @ilastikdev please check whether it works for the dataset where you saw the error.

ConservationTracking: fix table export

---

ilastik/workflows/examples/thresholdMasking/thresholdMaskingWorkflow.py

Implementation based on usage of DataExportApplet in pixelClassificationWorkflow

Added export to thresholdMaskingWorkflow

---

ilastik/utility/exportFile.py

was globally changed for 1.2.0 release

new feature names

---

ilastik/plugins_default/tracking_contours_with_head_export.py
ilastik/plugins_default/tracking_contours_with_head_export.yapsy-plugin
ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py

Important Fix and Plugin to Export Contours with Head Location

Important Fix and Plugin to Export Contours with Head Location

---

ilastik/applets/thresholdTwoLevels/drawer.ui
ilastik/applets/thresholdTwoLevels/opThresholdTwoLevels.py
ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py

- Add prob normalization (copied from multicut applet) and close issue #1473 
- Cosmetic improvements in the ui file
- Hide the word "Final" when single threshold is used

Polishing the new thresholding applet

---

ilastik/applets/cropping/cropSelectionGui.py
ilastik/applets/cropping/croppingGui.py
ilastik/applets/tracking/conservation/opConservationTracking.py
ilastik/applets/tracking/structured/drawer.ui
ilastik/applets/tracking/structured/opStructuredTracking.py
ilastik/applets/tracking/structured/opStructuredTrackingPgmlink.py
ilastik/applets/tracking/structured/structuredTrackingApplet.py
ilastik/applets/tracking/structured/structuredTrackingGui.py
ilastik/utility/gui/progress.py

allows the user to choose the solver type

solver combo box in learning

---

ilastik/applets/tracking/conservation/opConservationTracking.py
ilastik/applets/tracking/structured/opStructuredTracking.py
ilastik/applets/tracking/structured/opStructuredTrackingPgmlink.py
ilastik/applets/tracking/structured/structuredTrackingGui.py
ilastik/utility/gui/progress.py
ilastik/utility/progress.py
tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraFluo-N2DH-SIM-01.py
tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithDivisions.py
tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithMergers.py

check for ILP solver added (needed for learning)
non-gui progress bar methods moved to ilastik/utility/progress.py

tests in learning

---

ilastik/utility/gui/progress.py

adding Qt to import

---

ilastik/workflows/carving/opCarving.py

Set data type of segmentation layers in Carving workflow to uint32

---

ilastik/widgets/labelListView.py

LabelListView: show label name in context menu regardless of selected column

---

ilastik/applets/dataSelection/datasetInfoEditorWidget.py
ilastik/applets/dataSelection/datasetInfoEditorWidget.ui

Input properties editor: Fixed focus on OK button and tab order

---

ilastik/applets/objectExtraction/opObjectExtraction.py

Compute global object features in parallel (one plugin per thread). Fixes #347 .

Parallel global features

---

ilastik/applets/objectClassification/opObjectClassification.py

add user labels to the exported table

---

appveyor.yml

As discussed with @akreshuk ilastik is tested on windows using the binary distribution of ilastik to circumvent issues with private conda channels.
Thanks @bluescarni for the help in setting it up

Added testing on windows via appveyor.com

---

ilastik/applets/base/appletSerializer.py

When serializing the tracking results, several slots use a pickled representation. Apparently, there are NULLs (`b'\x00'`) within the `bytes` objects resulting from pickling. The HDF5 docs mention that this is not allowed in their variable length strings, and we ran into the exact error that they mention in their docs (http://docs.h5py.org/en/latest/strings.html). They suggest to use `numpy.void` instead, and that's exactly what this PR does. 
I just made it a separate PR so everyone is aware of that issue and change.

Fix hdf5 serialization of pickled slots, which crashed on nulltermination bytes

---

ilastik/applets/counting/opCounting.py

With the recent change from OpArrayCache to OpBlockedArrayCache blockshape has
to be given as a tuple. The code still expected a single int.

Fixes 'Cell Density Counting' error when clicking 'Update total density'

---

ilastik/widgets/listModel.py

fixes #1586 
case statement was missing a default

Fix for #1586 - label delete in listModel

---

ilastik/plugins_default/tracking_csv_export.py

ensures the same order of features in the header and in value columns
fixes 
https://github.com/ilastik/ilastik/issues/1618

Tracking CSV export: fix feature order

---

ilastik/applets/base/appletSerializer.py
ilastik/applets/multicut/opMulticut.py
ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py

With this and ilastik/ilastikrag@addf55bab031af910aadddeb28c94206cfaa1932 multicut workflow works in master

fix multicut workflow for py3

---

ilastik/applets/base/appletSerializer.py
ilastik/applets/tracking/conservation/conservationTrackingGui.py
ilastik/applets/tracking/structured/structuredTrackingGui.py
ilastik/plugins_default/tracking_csv_export.py
ilastik/plugins_default/tracking_mamut_export.py
ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py

This PR fixes a bunch of tracking bugs and problems that came up when I processed a larger set of data.
* properly close the progress bar window when an exception occurred
* allow batch processing in the _Tracking with Learning_ workflow (was looking for annotations)
* adds per-track color as feature in the MaMuT export
* fixes a bug in appletSerializer that was expecting lists to always only contain strings

Fix tracking bugs

---

ilastik/workflows/carving/carvingGui.py
ilastik/workflows/carving/opCarving.py

As described in #1224 , it was not possible to show objects after loading a project.
fixes issue #1224

fixes bug showing objects from loaded projects

---

appveyor.yml
circle.yml
ilastik/applets/base/appletSerializer.py
ilastik/applets/objectClassification/objectClassificationSerializer.py
ilastik/applets/pixelClassification/pixelClassificationSerializer.py
ilastik/applets/tracking/base/trackingSerializer.py
ilastik/applets/tracking/manual/manualTrackingSerializer.py
ilastik/applets/tracking/structured/structuredTrackingSerializer.py

Cherry picked important commits from https://github.com/ilastik/ilastik/pull/1650
I've tested this on linux with Pixel Classification, Tracking, Carving, Object Classification, Autocontext. Didn't run into any issues - tests also pass.
Addresses #1571

Fix: load projects saved with python 3 version

---

ilastik/applets/multicut/opMulticut.py

also check for WITH_CPLEX/WITH_GUROBI flags after import

check availability of nifty_with_cplex/gurobi with subprocess

---

ilastik/applets/counting/countingsvr.py

and make RF the default.
@FynnBe already tested this locally and it works on Windows, too

CountingSrv: remove regressors that depend on gurobiwrapper

---

ilastik/workflows/counting/countingWorkflow.py

allow for higher dimensional input to counting, if higher dimensions have length 1

force allowed axis orders for counting workflow

---

ilastik/applets/batchProcessing/batchProcessingApplet.py
ilastik/applets/dataSelection/dataSelectionApplet.py
ilastik/applets/dataSelection/opDataSelection.py
tests/test_applets/dataSelection/testOpDataSelection.py
tests/test_workflows/dataConversion/testDataConversionWorkflow.py

Requires lazyflow stack-headless branch!

Stack headless

---

ilastik/applets/labeling/labelingGui.py

Quick and dirty fix for the following: https://github.com/ilastik/ilastik/issues/933.
A proper fix/refactoring will follow in a subsequent PR.

Extend color table list dynamically to accommodate more than 16 labels

---

ilastik/applets/labeling/labelingImport.py

Now we can change axis order and automatically map the last label. Fixes #1713 .

Fix label import in pixel classification

---

ilastik/applets/dataSelection/addFileButton.py
ilastik/applets/dataSelection/dataSelectionGui.py
ilastik/applets/dataSelection/datasetDetailedInfoTableView.py
ilastik/applets/dataSelection/precomputedVolumeBrowser.py
ilastik_main.py

Added the front-end parts to enable loading of precomputed chunked volumes. Will only be available if ilastik is started with the `--hbp` flag.
needs https://github.com/ilastik/lazyflow/pull/267

Ilastik parts for the precomputed chunked reader

---

ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py

fixes#1653
in a code i add an other condition to activate the DT Watershed Applet that raw data as well as probability data is ready to activate this applet and also change the input conditions
works for more than a single image lane.

AssertionError during creation of MultiCut project

---

ilastik/applets/dataSelection/opDataSelection.py
ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py
tests/test_workflows/axesOrderPreservation/testAxesOrderPreservation.py

fix tests, broken by https://github.com/ilastik/lazyflow/pull/272

Fix original axisorder

---

ilastik.py
ilastik/shell/projectManager.py

- close project file in headless
- make sure folder for project file exists (if not leads to os error -- at least on windows)

Be nice to OS

---

bin/merge_carving_projects.py

I also have versions for python 2 and python 3.5. Should they be included as well??

add carving merge script (python 3.6)

---

ilastik/applets/dataExport/opDataExport.py
ilastik/applets/layerViewer/layerViewerGui.py
ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
ilastik/workflows/examples/thresholdMasking/thresholdMaskingWorkflow.py
ilastik/workflows/multicut/multicutWorkflow.py
ilastik/workflows/newAutocontext/newAutocontextWorkflow.py
ilastik/workflows/nnClassification/nnClassificationWorkflow.py
ilastik/workflows/pixelClassification/pixelClassificationWorkflow.py
ilastik/workflows/wsdt/wsdtWorkflow.py

as discussed in the Janelia meeting last year, this makes it the code a lot readable.
Needs for the tests to pass https://github.com/ilastik/lazyflow/pull/264
tests pass locally on linux

[in progress] Refactor: partner -> upstream_slot

---

ilastik/applets/counting/opCounting.py
ilastik/widgets/labelListView.py

added the clearLabel function to the topLevel operator of counting

---

CONTRIBUTING.md
scripts/create-dev-env.sh

I wrote up some contribution guidelines in order to make contributing to ilastik for outsiders more interesting.
Of course I relied heavily on the docs already out there, so there should not be too many surprises.
But, as this will be our contributor-facing text, we should all be happy with it, so please everyone, especially @akreshuk , @FynnBe , @wolny have a look and leave some feedback!
In addition @FynnBe : I know time is a precious resource these days, but at some point it would be great if you could add your windows perspective on this. At some point in the coming months.

[for discussion] Added contribution guidelines for discussion

---

ilastik/applets/blockwiseObjectClassification/blockwiseObjectClassificationGui.py
ilastik/applets/counting/countingGuiBoxesInterface.py
ilastik/applets/cropping/croppingGui.py
ilastik/applets/labelImageViewer/labelImageViewerGui.py
ilastik/applets/labeling/labelingGui.py
ilastik/applets/objectClassification/objectClassificationDataExportGui.py
ilastik/applets/objectClassification/objectClassificationGui.py
ilastik/applets/pixelClassification/FeatureSelectionDialog.py
ilastik/applets/pixelClassification/opPixelClassification.py
ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py
ilastik/applets/pixelClassification/pixelClassificationGui.py
ilastik/applets/predictionViewer/predictionViewerGui.py
ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py
ilastik/applets/tracking/base/trackingBaseGui.py
ilastik/applets/tracking/conservation/conservationTrackingGui.py
ilastik/applets/tracking/structured/structuredTrackingGui.py
ilastik/workflows/carving/carvingGui.py

make all gui classes use volumina colortable
make that colortable colorblind-friendly

Colortable16 changes

---

ilastik/applets/pixelClassification/pixelClassificationGui.py

and also let the user warning be a little bit more helpful...

make sklearn classifiers available again

---

scripts/create-dev-env.bat
scripts/create-dev-env.sh

Win dev script

---

.github/ISSUE_TEMPLATE/bug_report.md

Wanted to add one of these for a long time.
The wording and sequence is not set in stone, let's optimize it together :)
I've submitted an issue using this template and it does take its time: https://github.com/ilastik/ilastik/issues/1821
But the result is quite useful I would say

[for discussion] Added issue template

---

ilastik/applets/counting/countingGui.py
ilastik/applets/edgeTraining/edgeTrainingGui.py
ilastik/applets/multicut/multicutGui.py
ilastik/applets/objectClassification/objectClassificationGui.py
ilastik/applets/pixelClassification/pixelClassificationGui.py

Change the 'play' icon to 'pause' when any live update is active.

Beautify Live Update Button

---

ilastik/applets/wsdt/wsdtGui.py

Disable watershed widgets while it updates

---

.github/ISSUE_TEMPLATE/feature_request.md

A feature request template, similar to a bug report template,
improves GitHub issue submission UI.

Create a feature request template for GitHub

---

ilastik/applets/edgeTraining/edgeTrainingGui.py
ilastik/applets/edgeTrainingWithMulticut/edgeTrainingWithMulticutGui.py
ilastik/shell/gui/ilastikShell.py
ilastik/utility/gui/__init__.py
ilastik/utility/gui/widgets.py

* Unfreeze classifier after labels from the ground truth have been generated
* Disable Multicut GUI if inputs from EdgeTraining are not ready
Closes #1837.

Fix EdgeTraining and Multicut interaction

---

ilastik/applets/dataSelection/addFileButton.py
ilastik/applets/dataSelection/dataLaneSummaryTableView.py
ilastik/applets/dataSelection/datasetDetailedInfoTableView.py

store and update current index of buttons in Gui dataset table within the button object.
This fixes #1857

preserve index consistency in Gui dataset tables

---

ilastik/applets/networkClassification/nnClassGui.py
ilastik/workflows/nnClassification/nnClassificationWorkflow.py

needs ilastik/lazyflow@aee1c1fbbb2ce556e325a5ba2f82e1228f119f26

join tiktorchLazyflowFactory and tiktorchLazyflowClassifier

---

.gitignore
CONTRIBUTING.md

- updated unittest cmd with pytest; 
- minor update of .gitignore to ignore vim user tmp files and pytest output project

Update CONTRIBUTING.md and .gitignore

---

ilastik_main.py

see: https://github.com/scikit-learn/scikit-learn/pull/9569/files
closes #1811

sklearn patch has been merged, we use sklearn>=0.20

---

tests/conftest.py

* fixed `sys.exec_info` being a function
* fixed last gui test not being executed

fix conftest

---

ilastik/applets/tracking/structured/opStructuredTracking.py
ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
tests/test_applets/structuredLearningTracking/testOpStructuredTracking.py

Addresses a few issues related to learning tracking weights in Tracking.
Summary:
* there was some incomplete refactor from `networkx 1.x` to `2.x`
* added tests
Todo:
fixes #2052, #2056, #2057, #2005

Fix tracking learning

---

ilastik/applets/dataSelection/dataLaneSummaryTableModel.py
ilastik/applets/dataSelection/datasetDetailedInfoTableModel.py
ilastik/applets/edgeTraining/edgeTrainingSerializer.py

Companion to https://github.com/ilastik/lazyflow/pull/310

Fix subslot indexing

---

ilastik/applets/counting/countingGui.py
ilastik/applets/counting/countingGuiBoxesInterface.py
ilastik/applets/counting/opCounting.py
ilastik/widgets/boxListModel.py
ilastik/widgets/boxListView.py
ilastik/workflows/counting/countingWorkflow.py
tests/helpers/shellGuiTestCaseBase.py
tests/test_applets/objectCounting/testObjectCountingGui.py

Counting: Fix box export and add box import

---

ilastik/applets/wsdt/wsdtGui.py

update wsdt layers each time the 'Update Watershed' button was pressed

---

ilastik/applets/pixelClassification/pixelClassificationGui.py
tests/test_applets/pixelClassification/testPixelClassificationMultiImageGui.py

Synchronizes the status of live update button and the associated prediction cache across lanes.
Also added a test to define this behavior.
fixes #2092

Fix live update consistency in pixel classification

---

ilastik/applets/dataSelection/opDataSelection.py

previously `z5py.Group.visititems` would supply the full path to the supplied callable, now it will give the relative path -> same behavior as `h5py`.
-> z5py >=1.51
(see also https://github.com/ilastik/lazyflow/pull/325)

reflect z5py.Group.visititems changes

---

ilastik/applets/dataExport/opDataExport.py
ilastik/applets/objectClassification/objectClassificationDataExportApplet.py
ilastik/applets/objectClassification/objectClassificationDataExportGui.py
ilastik/applets/objectClassification/opObjectClassification.py
ilastik/applets/tracking/base/trackingBaseDataExportApplet.py
ilastik/utility/exportFile.py
ilastik/utility/exportingOperator.py
ilastik/widgets/exportObjectInfoDialog.py
ilastik/workflows/objectClassification/objectClassificationWorkflow.py
ilastik/workflows/tracking/conservation/animalConservationTrackingWorkflow.py
ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
tests/test_applets/dataExport/testOpDataExport.py
tests/test_utility/test_exportFile.py
tests/test_workflows/testObjectClassificationGui.py

Export tables

---

ilastik/workflows/voxelSegmentation/opVoxelSegmentation.py
ilastik/workflows/voxelSegmentation/utils.py

to adapt the voxelsegmentation workflow better to our architecture, the multiprocessing bit was removed. This also led to problems on mac.
Should investigate how to parallelize releasing the gil.

removed pathos multiprocessing parallelism

---

ilastik/applets/serverConfiguration/serverConfigForm.py
ilastik/applets/serverConfiguration/serverConfigForm.ui
ilastik/applets/serverConfiguration/serverConfigGui.py
ilastik/applets/serverConfiguration/types.py
tests/test_applets/test_serverConfiguration/test_configStore.py
tests/test_applets/test_serverConfiguration/test_serverConfigForm.py

Removes unused port from server configuration form

Remove unused port from tiktorch form

---

.circleci/config.yml
appveyor.yml
ilastik/applets/edgeTraining/edgeTrainingSerializer.py
ilastik/applets/edgeTraining/opEdgeTraining.py
ilastik/applets/edgeTrainingWithMulticut/edgeTrainingWithMulticutGui.py
ilastik/applets/edgeTrainingWithMulticut/opEdgeTrainingWithMulticut.py
ilastik/applets/multicut/multicutGui.py
ilastik/applets/multicut/opMulticut.py
ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
tests/test_applets/edgeTraining/testOpEdgeTraining.py

* Use 'standard_edge_mean' feature on probability map to compute edge probabilities
* Add tickbox to toggle whether to train a classifier
* Re-use user selection of input channels from Watershed as probability map

Make training a random forest classifier optional

---

.circleci/config.yml
ilastik/applets/wsdt/opWsdt.py
ilastik/applets/wsdt/wsdtGui.py

* Simple convenience feature to invert the probabilities

Implement 'invert probabilities' functionality in wsdt GUI

---

.circleci/config.yml
tests/test_applets/featureSelection/testNewFeatureSelection.py

For unknown reasons the timing test fails on circleci currently
see also #2184

xfail feature computation timing test on circleCi for now

---

lazyflow/operators/tiktorch/classifier.py

does not work like this as reorder_feature_image always is of type float32.
we need to check meta data instead
Let's discuss and do it better!

do not normalize

---

ilastik/applets/featureSelection/opFeatureSelection.py
ilastik/applets/objectClassification/opObjectClassification.py
lazyflow/operators/__init__.py
lazyflow/operators/oldVigraOperators.py
lazyflow/operators/opLabelVolume.py
lazyflow/operators/opLazyConnectedComponents.py
setup.cfg

Allows proper code navigation for operators

Unroll lazyflow.operator imports

---

.circleci/config.yml
appveyor.yml
ilastik/applets/counting/countingGui.py
ilastik/applets/counting/countingGuiBoxesInterface.py
ilastik/applets/dataSelection/dataSelectionGui.py
ilastik/applets/objectClassification/objectClassificationGui.py
ilastik/applets/serverConfiguration/serverConfigForm.py
ilastik/shell/gui/ilastikShell.py
tests/conftest.py
tests/test_ilastik/test_workflows/testCarvingGui.py

qt 5.12 in combination with Python >= 3.7.4 will bubble up some errors that would previously be ignored (see also https://github.com/ilastik/volumina/pull/261).
This PR includes similar changes to main ilastik.
Todo before this can be merged:

Changes needed for dependency upgrade qt 5.12

---

ilastik/applets/dataSelection/dataSelectionGui.py
ilastik/applets/featureSelection/featureSelectionGui.py
ilastik/applets/objectClassification/objectClassificationDataExportGui.py
ilastik/applets/objectClassification/objectClassificationGui.py
ilastik/applets/tracking/base/trackingBaseDataExportGui.py
ilastik/applets/tracking/conservation/conservationTrackingGui.py
ilastik/applets/tracking/manual/manualTrackingGui.py
ilastik/applets/tracking/structured/structuredTrackingGui.py
ilastik/utility/exportingOperator.py
ilastik/widgets/featureDlg.py

see also: https://github.com/ilastik/ilastik/pull/2276/commits

Remove properties from QT class

---

ilastik/applets/serverConfiguration/serverConfigApplet.py
ilastik/applets/serverConfiguration/serverConfigGui.py
ilastik/workflows/nnClassification/nnClassificationWorkflow.py

Let's maybe go in small steps on this one. In this PR i have only moved it to the first position of the workflow. Only if it is configured, user can advance.
fixes #2329

Improve server config

---

ilastik/applets/wsdt/wsdtGui.py

fix freeze on windows due to signals from non qt thread

---

CONTRIBUTING.md
Readme.md

Make README more appealing, bring the contributing instructions up
to date with the current available tools, and add more copy-pasteable
command snippets.

Update CONTRIBUTING and README

---

ilastik/applets/labeling/labelingGui.py
ilastik/applets/pixelClassification/pixelClassificationGui.py

move live update shortcut into labelingGui

Live update shortcut available in all labelingGuis

---

ilastik/app.py

super minimal; `--version` will print the version number, nothing extra.

added version command line flag

---

ilastik/applets/dataSelection/dataSelectionApplet.py

this makes sure links are relative to the project file, not cwd
fixes #2429

make sure to pass project file path to dataset info

---

tests/test_lazyflow/test_operators/test_tiktorch/test_classifier.py

need to reflect some upstream changes in tiktorch https://github.com/ilastik/tiktorch/pull/173
needed to enable `NamedInt` and `NamedFloats`.

reflect TensorDim -> NamedInt in tests

---

ilastik/applets/neuralNetwork/nnClassGui.py
ilastik/workflows/neuralNetwork/_localLauncher.py
ilastik/workflows/neuralNetwork/_localWorkflow.py

also close session before stopping the launcher

Close the session on cleanup

---

ilastik/applets/multicut/multicutGui.py

The usefulness of this functionality was questionable - and we decided to remove it.

Removed "live" multicut button

---

ilastik/applets/edgeTraining/edgeTrainingSerializer.py
tests/test_ilastik/test_applets/edgeTraining/testEdgeTrainingSerializer.py

Previously it was possible to load the wrong RAG per Lane, as there was an implicit expectation to find serialized Rags for every lane. This absolutely has not to be the case (e.g. when a person chooses to work only on the second lane for training, then saves.
In this PR the deserializer will check to which lane the Rags belong before setting the cache.
thx to @ofrag for making us aware of this problem!

Multicut fix rag load

---

ilastik/applets/edgeTrainingWithMulticut/edgeTrainingWithMulticutGui.py

This code is touching UI, so it's necessary to run in in the main thread. Previous calls could end up in the UI freezing.
fixes #2482

make sure to handle gui update in main thread

---

ilastik.py
tests/conftest.py
tests/test_ilastik/test_workflows/testCarvingGui.py

Big Sur is 10.16.1
Monterey is 12.0.1 (thx @emilmelnikov)

looks like big sur went beyond 10.16 already

---

bin/make_tiles.py
bin/subsample_volume.py
ilastik/applets/batchProcessing/batchProcessingGui.py
ilastik/applets/counting/countingsvr.py
lazyflow/utility/io_util/multiprocessHdf5File.py
tests/test_ilastik/test_applets/base/testSerializer.py
tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
tests/test_lazyflow/test_operators/testOpLazyConnectedComponents.py
tests/test_lazyflow/test_operators/test_ioOperators/testOpStreamingH5N5SequenceReaderM.py

all instances of h5py.File must have a file mode

prepare for h5py>=3

---

.github/workflows/core-conda-bld.yml
conda-recipe/meta.yaml
lazyflow/operators/tiktorch/classifier.py
tests/test_lazyflow/test_operators/test_tiktorch/test_classifier.py

Tiktorch update

---

.circleci/config.yml
CONTRIBUTING.md
appveyor.yml
dev/environment-dev.yml

switching from managing dependencies for development from ilasik-dependencies recipe to this yaml file
deviating from our traditional development environment setup with a conda recipe. Doing it with environment.yml one has the flexibility to quickly try out different versions without hacky force-uninstalling the main package, or alternatively rebuilding the package to try something out. If something is changed due to code changes, this can be directly reflected, ci will pass, others can check it out...

add environment-dev.yml

---

.circleci/config.yml
.github/workflows/static-code-analysis.yml

the black check started failing recently with empty change sets.
Moved this to a gh action with darker.

use darker for black on gh actions

---

.github/workflows/deploy.yml

forgot to reference secrets...

fix release trigger

---

.github/workflows/deploy.yml

fixed release trigger

---

ilastik_scripts/ilastik_startup.py

Closes https://github.com/ilastik/ilastik/issues/2557

Fix OpenGL shared library lookup on macOS Monterey

---

conda-recipe/meta.yaml

multicut doesn't work now with older versions.

bump minimal volumina version

---

conda-recipe/meta.yaml
dev/environment-dev.yml
ilastik/applets/neuralNetwork/bioimageiodl.py
ilastik/applets/neuralNetwork/modelStateControl.py
ilastik/applets/neuralNetwork/nnClass.ui
ilastik/applets/neuralNetwork/nnClassGui.py
ilastik/applets/neuralNetwork/nnClassSerializer.py
ilastik/applets/neuralNetwork/opNNclass.py
ilastik/applets/neuralNetwork/tiktorchController.py
ilastik/widgets/percentProgressDialog.ui
ilastik/widgets/progressDialog.py
ilastik/workflows/neuralNetwork/_localWorkflow.py

Rework of some of the UI parts for the neural network workflow:
**Summary**
* support for entering dois, nicknames and also zip files via ui widget `ModelStateControl`
* moved some ui parts out of NN gui just because it got so large
* models are now checked for compatibility before downloading/initializing them in tiktorch
* show more detailed download progress

Nn doi support

---

bin/train_headless.py

Fixes the `train_headless.py` script  which was using the old way of getting workflow role names. Also allows labels that do not start at 1

Fixes train_headless_script

---

.github/workflows/core-conda-bld.yml
lazyflow/utility/helpers.py
pytest.ini
setup.cfg

ensure to run doctests in lazyflow

---

conda-recipe/meta.yaml
ilastik/applets/dataExport/dataExportGui.py
ilastik/applets/dataExport/opDataExport.py
ilastik/applets/tracking/base/pluginExportOptionsDlg.py
ilastik/config.py

Hello all, 
This small PR aims adds a reset button to the export gui so a user can revert to default "magic" path more easily. I'll do a separate PR for the corresponding changes in volumina asap
closes #2590

Add button resetpath

---

ilastik/applets/neuralNetwork/modelStateControl.py
ilastik/applets/neuralNetwork/nnClassGui.py

Summary:
* removed the "Labels" layer, as it cannot be interacted with (currently) but is still shown in the layerstack
* added right-click interaction on Prediction layers to change layer color (it uses the same method as going via the label list. Note: Labellist is currently not shown -> no other way to change colors).
* fixed a regression introduced in https://github.com/ilastik/ilastik/commit/1d4eb62deaf3a890435304e27a34994a75e0a210 that caused model information from a model saved in the project file not being shown when project was loaded.

Neural Network Worfklow UI improvements

---

conda-recipe/meta.yaml
dev/environment-dev.yml

xref #2612
was pending rebuilds against hdf5 1.12.2

Re-apply vigra build with latest patches

---

ilastik/shell/gui/ilastikShell.py

previously, closing the project would trigger update of `currentApplet` setting in project file. This had the unintentional side effect, that opening a file, doing something without saving, closing (without saving) would still alter the project file. This should not happen.
Now the `currentApplet` setting is only updated on the `saveProject` action (not on `saveProjectAs`, or `saveProjectSnapshot`).

move applet index saving to save method

---

ilastik/workflows/neuralNetwork/_nnWorkflowBase.py

For users (well, for everyone :P) it is confusing that there is the option to export the Labels from the NN workflow that does not allow for adding any labels :)
Thought I've done that already, but labels are _still_ there to export.
fixes #2264

Hiding labels in NN wf: currently users cannot label

---

.github/workflows/core-conda-bld.yml
conda-recipe/meta.yaml

mnt: update pytorch versions

---

ilastik/workflows/trainableDomainAdaptation/_localTrainableDomainAdaptationWorkflow.py

Exports could be incomplete previously :(. Now cache is unfrozen before doing any export.
cc: @Buglakova

unfreeze cache before exporting data from tda workflow

---

.github/workflows/core-conda-bld.yml
conda-recipe/meta.yaml
dev/environment-dev.yml
tests/conftest.py

What began as a "simple" update of dependencies (https://github.com/ilastik/ilastik/pull/2726/commits/b06dfe433f8ef4a5ca04b3f64a24edbc3ac75fe8) sent me into a ghost hunt for the cause of segfaults at the end of the tests.
I tried various things, like finally fixing parent/child relationships in volumina and ilastik, but nothing really helped. In the end, the first guess was probably right, that multiple instances of `QApplications` were created. https://github.com/ilastik/ilastik/pull/2726/commits/33f59942c69c51ec38a92490afea3133fbc9ece9 solves this...

Fix devenv

---

examples/opSlic.py
ilastik/workflows/voxelSegmentation/opSlic.py
tests/test_ilastik/test_applets/voxelSegmentation/testOpSlic.py

refs
* `multichannel` -> `channel_axis`: https://scikit-image.org/docs/stable/release_notes/release_0.19.html#api-changes
* `max_iter` -> `max_num_iter`: https://scikit-image.org/docs/stable/release_notes/release_0.19.html#newly-introduced-deprecations
closes #2791
Todos:

fixed `skimage.segmentation.slic` signature change

---

ilastik/applets/dataSelection/datasetDetailedInfoTableModel.py
ilastik/applets/dataSelection/datasetDetailedInfoTableView.py
tests/test_ilastik/test_applets/dataSelection/testDataSelectionGui.py

* Format internal paths for display
* Show tooltips
* Combine AxisOrder and Shape columns + default column width
Before:
After:

Prettify dataset table

---

tests/test_ilastik/test_applets/dataSelection/testDataSelectionGui.py

The test broke because of https://github.com/ilastik/ilastik/pull/2793, but on CI it still passed because the pop up assert is off on CI, and that left only an assert for a mock not being called. Which still passes when the test does nothing.

Tests: Fix mock table and assert combobox attempts to change

---

lazyflow/operators/generic.py
tests/test_lazyflow/test_operators/testOpMultiChannelSelector.py

This 
* Add `OpMultiChannelSelector` support for arbitrary channel ordering as supplied in `SelectedChannels`
* Fixed  a bug in the tests that would not test all possible variations of input-channels. :(

Fixed OpMultiChannelSelector

---

tests/test_ilastik/widgets/test_ImageFileDialog.py

This way the test still checks our custom functionality in `getSelectedPaths` without depending on user interaction. Though like all mocking, it also makes the test more specific to the implementation.

Tests: Mock user interaction in ImageFileDialog

---

ilastik/applets/dataSelection/opDataSelection.py
tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py

Was broken by 4403bb33 (which should not have removed this line)
Fixes #2824

Multiscale: Save scale

---

ilastik/shell/gui/ilastikShell.py

Hey, I am Theo! This is my first PR for the ilastik :) 
I am attempting to close #2830 . With this change the menu option `Save Project As` will refresh the opened recent files, in the exact same way that is happening when a project is loaded.
I wanted to add tests for this change, but I realized that there aren't any for the `ilastik/shell/gui/ilastikShell.py`. If this needs to be addressed on this PR please let me know  :)

Update open recent project list when saving as a project

---

ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py

The default selection is "Probabilities". When the user switches to "Simple Segmentation", the OpMultiArraySlicer2 created for Probabilities is still connected to `opLane.ImageToExport`. If the user now changes export axis order to remove "c", this change bubbles down to the orphaned OpMultiArraySlicer2, which cannot handle it as it has two channels. 
Solution: Keep a ref to the op and delete it
Reproduce/Manual test:
1. Pixel Classification project with any image (mitocheck works), export applet
2. Change output source to Simple Segmentation
3. Open Image export settings
4. Check Reorder axes
5. Change `yxc` to `yx`
6. Click OK
7. main crashes; PR works
Fixes #1244
- [ ? ] Add tests --- Not sure? Generally of course nice to have regression tests, but this is Gui code...

Pixel Classification: Fix pop error

---

tests/test_lazyflow/test_operators/test_ioOperators/testOpH5N5WriterBigDataset.py

Minor PR for refactoring a test. I rewrote the test because I was going to add zarr as another test case, then decided OME-Zarr warrants its own operator and won't go here.
I think the refactoring is still helpful in its own right. It makes the difference between the test cases clearer, and makes sure the h5 and n5 tests don't depend on each other (plus it's a bit shorter :smile: ).
The actual test cases covered and how they're implemented could be improved I think. I'm also not sure about the value of the third test using `.Output.meta.ram_usage_per_requested_pixel = 1000000.0` to force writing in tiny blocks. This test takes 0.5s to run, which is a long time for a test case that seems unnecessary to cover to me. But I intentionally purely refactored here to make review easier.
Note: …

H5N5 writing: Refactor test - readability, disentangle test cases

---

ilastik/applets/base/appletSerializer/slotSerializer.py

last usage removed in 2017/Tracking
see ff4eae6f6acdb9fad9fe6144f7120c49d34c7eeb

Removed unused `SerialHdf5BlockSlot`

---

ilastik/applets/dataSelection/datasetDetailedInfoTableModel.py
ilastik/applets/dataSelection/datasetDetailedInfoTableView.py

I like it in FIJI so I put it in ilastik :) should try to figure out some time how to change the default col width
current:
new:
expanded:

Multiscale: Preview scale file size in dropdown

---

ilastik/applets/dataSelection/dataSelectionGui.py

When loading multiple files, ilastik used to instantiate a viewer for every file added, which was shown only very briefly. With this commit, the viewer is only instantiated for the first added file.
I've seen 3-5 times speedup in loading files with this patch.

DataSelection don't show viewer for every added file

---

LICENSE
ilastik/shell/gui/licenseDialog.py

Summary:
* updated main license and the user-facing license dates.

1.4.1 prep

---

ilastik/app.py
lazyflow/operators/tiktorch/classifier.py

would result in a log message for every tile otherwise. too spammy...

Really last changes before release

---

.github/workflows/deploy.yml

Seems to be a recent incompatibility with boa and the rest of our build deps. Not going to investigate - conda build works just fine.

Fix dependency conflicts with boa, and go back to conda build

---

lazyflow/utility/io_util/OMEZarrStore.py

Just a couple of improvements in error messages when trying to use S3-like web servers. This should make it easier to diagnose from the log what exactly is working and what isn't (i.e. is it attempting the right auth pathway, is auth working).

OME-Zarr: Better feedback for S3 with auth
