- ilastik/applets/base/appletSerializer.py
- tests/test_applets/base/testSerializer.py
Changed the convenience methods so that `getOrCreateGroup` takes advantage of the method `require_group` from h5py, which does the same thing. Also, this ensures that an existing dataset might not be returned instead of a group. Now, an error will be raised. Changed `deleteIfPresent` to simply attempt deleting and handle an exception in the case that the item does not exist as opposed to performing the search twice.
> Cleanup convenience methods applet serializer

- ilastik/widgets/exportObjectInfoDialog.py
Fixing issue ilastik/ilastik-#1082
Default file type filters are now automatically set when changing the export file type.
Before you had to manually change the filter in the "Choose File" dialog.
> Fixing ilastik/ilastik-#1082

- ilastik/applets/base/appletSerializer.py
- tests/test_applets/base/testSerializer.py
This is related to ( https://github.com/ilastik/ilastik/issues/1076 ). It relies on features from this PR to function correctly ( https://github.com/ilastik/lazyflow/pull/164 ).
Provides support for serializing masked arrays from caches using SerialBlockSlot. Has tests to make sure serialization is working correctly.
> Provide serialization support for masked arrays

- ilastik/utility/exportFile.py
This fixes the issue ilastik#1107.
Apparently ``if x in iterable: ...`` advances the iterator, which was not intended here.
> Fixing ilastik/ilastik-#1107

- ilastik/shell/gui/startShellGui.py
- ilastik_main.py
- tests/helpers/shellGuiTestCaseBase.py
See #1061. (Including vigra before opengm yields ImportError: cannot import name IndexVector)
This only has an affect if OpenGM is built with the python wrapper, but that should be the case in our binaries.
> Include opengm before everything else to enable graph cut thresholding

- ilastik/applets/labeling/dataImportOptionsDlg.ui
- ilastik/applets/labeling/labelingGui.py
- ilastik/applets/labeling/labelingImport.py
I took the commits from #1119 and rebased them against the latest master.  Then I made some changes on top of it.  See the commit log for details.  BTW, to use this branch you will need the latest versions of lazyflow and volumina (master branches).
Summary of the changes I added on top of #1119:
- The new GUI for label import options is always shown to the user -- no defaults are assumed.
- The user may specify the axis-order of the file she selected (in case the `OpInputDataReader` guessed wrong)
- Don't assume 3D (or 5D)
- Show a busy indicator while the data is loading
> Label Import: Rebased from #1119

- ilastik/applets/featureSelection/featureSelectionGui.py
- ilastik/applets/featureSelection/opFeatureSelection.py
Rewrote the code to load features from a file in the feature selection applet. Now the code is cleaner and it works for 2D and 3D workflows. The format of the file is also more consistent with ilastik's hdf5 format.
The format of the external features file is the usual HDF5 volume dataset (usually called `data` or `external_data`) with the attribute `axistags`.
> Rewrote the code to load features from a file in the feature selection applet.

- ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Fixed problem caused because the object classifiers (for division and cell objects) were retrained everytime a lane was added during batch processing.
> conservationTrackingWorkflow.py: Fixed problem with classifiers being retrained during batch processing

- ilastik/applets/tracking/base/opTrackingBase.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Fixed 2 problems when connecting new lanes for batch-processing:
* New object features were erased every time a new lane was connected. To fix this bug, the `setValue()` functions of `opCellClassification` and `opDivisionDetection` were moved from `connectLane()` to the constructor of the workflow.
* Problem with conflicting sizes of `EventsVector` and `time_range` when adding a new lane. This problem was fixed by adding a `with_batch_processing` flag to the function `_generate_traxelstore` in `opConservationTracking.py`
> Fixed 2 problems when new lane is added for batch-processing

- ilastik/utility/exportFile.py
Fixed a problem in the file `exportFile.py` that was causing tracking to crash with a memory error. The function `objects_per_frame` was modified to load the data by streaming it using a roi instead of loading the whole video in ram.
> exportFile: Fixed problem in function objects_per_frame

- ilastik/applets/tracking/base/opTrackingBase.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
The axis ranges (stored in the `Parameters` slot) of the first lane were being used incorrectly for all the lanes during batch-processing. In order to fix the problem, I removed the `withBatchProcessing` flag from `_generate_traxelstore`, and restore the original axis ranges in `post_process_lane_export`.
There is a fundamental problem with the `Parameters` slot since it is a broadcasted slot, and therefore the same for all the lanes, but it also contains information on axis ranges that is different for every lane. The ideal fix would be to split `Parameters` into two slots, `Parameters`  and `AxisRanges`. This change however, requires a lot of modifications to the code which will make the merging of structured learning more difficult. For now I fixed the problem in a more simple way, by …
> Fixed problem with axis ranges stored in parameters

- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Solved a problem with the wrong number of dimensions(ndim) in the tracking batch processing mode. When the wrong number of dimensions (eg. 3 instead of 2 for a 2D+t video) was set, the following message was displayed from pgmlink:
error: subtraction: incompatible matrix dimensions: 2x404 and 3x404
04:22:37.252 WARNING: GMM fitting failed for Traxel(15, 19592), reverting to KMeans: subtraction: incompatible matrix dimensions: 2x404 and 3x404
> Solved problem with wrong number of dimensions(ndim) in batch processing mode

- ilastik/applets/tracking/base/opTrackingBase.py
- ilastik/applets/tracking/base/trackingBaseDataExportGui.py
- ilastik/applets/tracking/base/trackingSerializer.py
- ilastik/applets/tracking/conservation/conservationTrackingApplet.py
- ilastik/applets/trackingFeatureExtraction/config.py
- ilastik/widgets/exportObjectInfoDialog.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Added new object features, `RegionRadii` and `RegionAxes`, to conservation tracking in order to export the data in a format required by Branson's lab.
Also, fixed 2 errors when exporting object features:
* The was an error on the animal conservation tracking workflow when clicking on "Configure Table Export" of the `Data Export Applet`. Since the slot `ComputedFeatureNamesWithDivFeatures` is set to `None` in animal tracking, clicking on the button was crashing ilastik.
* The features and settings chosen on the object feature dialog in the `Tracking Result Export` section were reset everytime the dialog was closed or a new lane was added.
> Added New Object Features to Tracking

- ilastik/applets/dataSelection/dataSelectionApplet.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Changed `self` to `cls` reference in `dataSelectionApplet` and changed the name of the input parameter `binary-image` to `segmentation-image` in the tracking workflow in order to stay consistent with the object classfiication workflow and the ilastik docs.
> Fixed problem with ilastik input parameters on dataSelectionApplet and conservationTrackingWorkflow when running on headless mode

- ilastik/applets/tracking/base/opTrackingBase.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Added a couple of memory and running-time optimizations to the code:
* Optimized memory allocations in the `execute()` function of `opConservationTracking` and `opTrackingBase`
* Set some tracking logging messages to `debug` mode instead of `info` mode, since these messages where consuming a significant amount of time to print to screen
Also, added checks to make sure that `time_range`, `x_range`, `y_range`, and `z_range` are contained in the parameters when running batch processing.
> Tracking memory and running-time optimization

- ilastik/applets/pixelClassification/pixelClassificationGui.py
- ilastik/shell/gui/variableImportanceDialog.py
Added a variable-importance-table dialog accessible from the `Advanced` section of the menu bar. In order for the table to work, the user has to first activate the `Parallel Random Forest with Variable Importance (Vigra)` in the `Select Classifier Type` dialog:
Here's a screenshot of the table with color codes based on feature importance:
The table is sorted by overall feature importance.
> Variable Importance Table GUI

- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/applets/tracking/structured/opStructuredTracking.py
The following two fixes made it possible for headless mode to run on the `learning` branch:
* Removed QtGui import
* Added type conversions to pgmlink functions to get rid of incompatible function signatures
> Small changes to enable headless mode on the learning branch

- ilastik/applets/tracking/conservation/opConservationTracking.py
Set the `ideal_blockshape` to the shape of a single frame in `MergerOutput` and `RelabeledImage` since the blockshapes choosen by the `BigRequestStreamer` were not ideal.
> opConservationTracking: Set the ideal_blockshape in MergerOutput and RelabeledImage

- ilastik/applets/tracking/manual/opManualTracking.py
Added check for empty frames when exporting tracking results in `opManualTracking` in order to fix issue https://github.com/ilastik/ilastik/issues/1220
> opManualTracking: Added check for empty frames when exporting tracking results

- ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py
Set `LabelImageCacheInput` slot to optional, in `opTrackingFeatureExtraction`, in order to fix issue #1225
> opTrackingFeatureExtraction: Set LabelImageCacheInput slot to optional

- tests/test_applets/conservationTracking/testConservationTrackingHeadless.py
Removed unused import of `ilastik.config` that was causing an error in the learning branch.
> testConservationTrackingHeadless: Removed unused import of ilastik.config

- ilastik/applets/tracking/base/opTrackingBase.py
Fixed error when loading time_range parameter from `_setLabelToColor` when opening old tracking project files: Fixes #1235
> opTrackingBase: Fixed error when loading time_range parameter from _setLabelToColor

- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/tracking/conservation/config.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Fix #1188
The conservation tracking workflow was training the RF classifier only with the `Standard Object Features`, and it was ignoring the skeleton and convex hull features. In order to solve this problem the following changes were made:
1. The `opObjectExtraction` `Features` slot was populated with the `Standard Object Features`, `Skeleton Features` and `Convex Hull Features` on the initialization of the conservation tracking workflow.
2. In `objectClassificationGui` the values of the `computedFeatureNames` and `selectedFeatureNames` slots were obtained using a deep copy in order to prevent modfying them directly from the GUI.
> Fix 1188: Convex hull and skeleton features are now being used in the tracking workflow

- ilastik/applets/tracking/conservation/opConservationTracking.py
`opConservationTracking` is not inheriting from `opBaseTracking` anymore, and therefore it is independent from the base tracking operator. The conservation tracking operator will be simplified as the HyTra pipeline is integrated, replacing functions that include `_setLabel2Color`, `_generate_traxelstore`, and `track`.
> opConservationTracking: Removed inheritance from opBaseTracking

- ilastik/utility/exportingOperator.py
`ExportObjectInfoDialog` now remembers selected features and settings. This closes #1261.
> object classification: export dialog now remembers selected features and settings

- ilastik/applets/tracking/base/trackingBaseGui.py
During export of h5 sequence (in conservation tracking) the original label image (without resolved labels) was exported
but move and division ids are taken from the resolved events.
Fix:
- check if self.mainOperator.RelabeledImage exists (to be compatible with chaingraphTrackingApplet)
- if it exists use resolved label image for export
> fix resolved label image export in tracking h5 sequence export

- ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py
TrackingFeatureExtraction: Replaced `Features` slot by `FeaturesWithDefault` slot in `opObjectTracking` to fix #1380
> TrackingFeatureExtraction: Replaced Features slot by FeaturesWithDefault

- ilastik/applets/objectExtraction/objectExtractionGui.py
- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py
- ilastik/utility/exportFile.py
- tests/test_applets/conservationTracking/testConservationTrackingHeadless.py
This PR moves **augmentFeaturesNames()** from `opObjectExtraction` to `opRegionExtraction`, and also removed the slot `FeaturesWithDefault` to fix #1380 and fix #1382.
Also fixes another issue on `exportFile` that occurs when `Cell Divsion Features` is not found in the plugin manager.
@akreshuk I am now able to export the csv table with the long names, combined with the short names for features related to `Cell Division Features`. The mix looks a bit odd.  Could you review my changes and tell me if I'm missing anything?
> Fix 1380 and 1382

- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Bypassing cache (used in opObjectExtraction/opLabelVolume) when conservation tracking is running on headless mode.
> Bypassing cache when conservation tracking runs on headless mode

- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Set option to bypass cache to false on `post_process_lane_export()` on the conservation tracking workflow
> Set option to bypass cache to false on post_process_lane_export()

- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/applets/trackingFeatureExtraction/opTrackingFeatureExtraction.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Bypass `opLabelVolume` cache when running tracking on batch mode in order to improve RAM usage.
> Bypass opLabelVolume cache when running tracking on batch mode

- ilastik/applets/tracking/conservation/opConservationTracking.py
Added option to use simple  configuration to get features of relabeled mergers for animal tracking, instead of using `opRelabeledMergerFeatureExtraction`.
@chaubold I'm using your operator on the `Tracking Workflow` (cell tracking), what do you think?
> Added option to use simpler configuration to get features of relabeled mergers for animal tracking

- ilastik/applets/objectClassification/labelingDrawer.ui
- ilastik/applets/objectClassification/objectClassificationGui.py
New dialog that contains a table with max/min object areas and label counts per frame in order to assist with merger count labelling. The table can be sorted by frame number, object area, or label count. Users can also navigate to the frame when they click on a table row. Here's a screenshot:
This dialog is accessed from `Object Classification Applet>Dialog-Assist Table`
This features was requested by @kristinbranson and @chaubold.
> Show Dialog on the Object Classification GUI with Object Info to Assist Object Labelling 

- ilastik/plugins_default/tracking_contour_export.py
- ilastik/plugins_default/tracking_contour_export.yapsy-plugin
- ilastik/plugins_default/tracking_mwt_export.py
- ilastik/plugins_default/tracking_mwt_export.yapsy-plugin
2 Plugins to export the tracking results to `.outline` files, which contain larvae contours, and also to Multi-Worm-Tracker `.summary` and `.blobs` files.
These file formats are mainly used by Marta Zlatic's lab.
> Plugin to export tracking results to .outline contour files and MWT files

- ilastik/applets/objectClassification/objectClassificationGui.py
Computing only the object areas on the `Label-Assist` dialog (previously computing all the object features selected in object-extraction).
> Computing Object Areas Only on Label-Assist Dialog

- circle.yml
`ilastik-everything-but-tracking` is deprecated in favour of `ilastik-everything-no-solvers`, see https://github.com/ilastik/ilastik-build-conda/issues/25
> switched package to ilastik-everything-no-solvers

- ilastik/applets/dataExport/dataExportApplet.py
- ilastik/applets/dataExport/dataExportGui.py
- ilastik/applets/tracking/base/trackingBaseDataExportApplet.py
... which fixes #1466.
An alternative option would have been to change all signatures to e.g. `post_process_lane_export(self, lane_index, *args, **kwargs)`, but I think the way this PR handles it is more explicit and thus less prone to mistakes as the one we introduced, leading to #1466.
> Let DataExportApplets specify whether they provide checkOverwriteFiles

- ilastik/applets/dataExport/dataExportGui.py
- ilastik/plugins_default/tracking_mamut_export.py
The MaMuT export was tested with 2D+t and 3D+t data, works fine now.
The second commit fixes #1490.
> Tracking Export: Fix MaMuT export axis order, and fix existing file check

- ilastik/applets/tracking/conservation/conservationTrackingGui.py
- ilastik/applets/tracking/conservation/opConservationTrackingPgmLink.py
... and hide invalid options from the GUI when using `pgmlink`. Fixes #1503
@FynnBe, please check whether that also works on Windows (you need CPLEX for this), I tested it on my Mac.
> Fix API mismatches in tracking between pgmlink and hytra versions

- ilastik_main.py
- tests/nose_single.py
as discussed in #1120 as well as in https://github.com/h5py/h5py/issues/582 and https://github.com/h5py/h5py/issues/580 those monkey patches are not longer necessary.
> removed h5py monkey-patches

- ilastik/applets/dataSelection/opDataSelection.py
- tests/test_applets/dataSelection/testOpDataSelection.py
... because this leads to very strange behaviour of ilastik, as described in #1528.
I added a test to make sure we don't allow that, and rise an error from `OpDataSelection` if those assumptions are violated
> Do not allow users to select data without x or y axes

- Readme.md
Sorry for the overhead, but I wanted to make sure the appveyor build works with master before including the badge
> added status badge for appveyor build to readme

- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/opDataSelection.py
- ilastik/widgets/hdf5SubvolumeSelectionDialog.py
- ilastik/widgets/stackFileSelectionWidget.py
- tests/test_applets/dataSelection/testOpDataSelection.py
This PR only works with https://github.com/ilastik/lazyflow/pull/246 .
* Added tests for single file hdf5 stacks to `testOpDataSelection`
* Created a new Dialog to specify glob string for single file hdf5 files. This dialog is opened automatically if a single hdf5 file is supplied via the `Add single volume from image stack` dialog:
* The performance is not the greatest, but it worked with real life test images
> Added single file hdf5 stack loading through the GUI

- ilastik/applets/counting/opCounting.py
with the change from OpArrayCache to OpBlockedArrayCache, blockShape should
not be a single value anymore
> hard-coded block-shape as tuple

- ilastik/shell/gui/ipcManager.py
PyQt5 implements cooperative multi-inheritance behaviour.
In short, due to the `super().__init__(*kwargs)` call in `QObject.__init__`,
the `__init__` method of the next sibling (`ZMQBase`) is also called.
The arguments have to be, therefore, passed to the super init alread.
fixes #1588
> Fixes `ZMQSubscriber` initialization in debug mode with python 3 / pyqt5 mro behaviour 

- ilastik/applets/counting/countingGui.py
- ilastik/applets/counting/countingOperators.py
- ilastik/applets/counting/countingsvr.py
- ilastik/applets/counting/opCounting.py
- tests/test_applets/objectCounting/testObjectCountingMultiImageGui.py
The main commit is "solves" the problem of the gui test halting is https://github.com/ilastik/ilastik/commit/533006600dc185135cd7c6473ecfdb952a79bf09 . Unfortunately it is not a real solution, but rather a mere hack: Due to not yet clearly identified problems in lazyflow, `OpCacheFixer` will block the main thread if `OpCacheFixer.fixAtCurrent` is changed, while at the same time someone pulls from its output.
In any case, this will let the tests run through for now.
Note, that there will still be an error in the tests, which I will address in a different PR (out of scope).
This PR includes a few minor changes that I have introduced to make it more like pixelClassification.
Summary of other changes:
* didn't see a reason why `OpDenseLabelArray` was used, so changed it to …
> Fix counting gui test freeze

- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
this fixes an issue with an error showing up when creating a new object
classification project.
> Removed remaining references to filter in cmdln args

- appveyor.yml
I have updated the appveyor config to use our latest recipe based on python 3.
There is a failure on appveyor is a real failure and should be fixed. This PR re-enables appveyor testing and should be merged.
> Adapted appveyor.yml for python 3 testing

- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/plugins_default/tracking_ctc_export.py
- ilastik/plugins_default/tracking_ctc_export.yapsy-plugin
- ilastik/plugins_default/tracking_h5_event_export.py
- ilastik/plugins_default/tracking_json_export.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
- ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
- tests/test_applets/conservationTracking/testConservationTrackingHeadless.py
This PR adds functionality to export the tracking result in the format defined by the [ISBI Cell Tracking Challenge](http://www.codesolorzano.com/Challenges/CTC/Welcome.html). Check [here](http://ctc2015.gryf.fi.muni.cz/Public/Documents/Naming%20and%20file%20content%20conventions.pdf) for a detailed description of the file contents.
It also fixes the export filename for tracking plugins that take the name as folder instead of file.
**Update 25.10.2017:**
* fixed a problem with mergers in JSON export
* added a bunch of tests that at least runs our plugins and also verifies the result for some of them
> Tracking: add Cell Tracking Challenge export format

- bin/downsample_pointcloud.py
- bin/pointcloud_csv_to_ply.py
- ilastik/applets/base/appletSerializer.py
- ilastik/applets/dataExport/dataExportApplet.py
- ilastik/applets/dataExport/dataExportSerializer.py
- ilastik/applets/objectExtraction/objectExtractionSerializer.py
- ilastik/utility/commandLineProcessing.py
- tests/test_applets/base/testSerializer.py
- tests/test_utility/testCommandLineProcessing.py
In this PR I removed all `eval` occurences in the code.
Rationale: `eval` is just not that safe and not really needed for our purposes.
This PR should be thoroughly reviewed, as I am not sure everything is tested - so a second pair of eyes would be nice.
* Conversion from strings representing lists is now mostly handled while parsing the arguments and based on `json.loads`-> `ilastik.utility.commandLineProcessing.ParseListFromString`
* in the two scripts residing in `/bin` I have changed the behaviour slightly. Single sumbers are not allowed anymore for `scale` and `offset`. Also I have made optional arguments `required=False`, rather than `nargs='?', default=None`. Behaviour should be the same.
> Remove all evals

- tests/test_workflows/test_all/testAllHeadless.py
The code in this PR tests all workflows that are discovered with `ilastik.workflows.getAvailableWorkflows()`.
The tests are very basic:
* a blank project file is created for each workflow using `ilastik.shell.projectManager.ProjectManager`
* this project file is then opened in the headless shell.
Any unexpected errors (uncaught exceptions) will make this test fail.
Furthermore, project file creation via the command line is also tested.
Currently, the ObjectClassificationWorkflow will complain about `Couldn't obtain a classifier from your project file` and `Was not able to understand the batch mode command-line arguments.`. Those messages are properly caught errors, and should be okay for our purpose.
Open to suggestions to improve this test @akreshuk @chaubold
> Test all workflows in headless mode with blank project files

- ilastik/widgets/boxListModel.py
Summary ;):
* `BoxListModel.flags` returns `Qt.NoItemFlags` per default
I have also looked around all ilastik and befriended repos: we should be fine. Everywhere else there are default cases that return some kind of `Qt.ItemFlags` thing.
Fixes #1637
> fix error in counting workflow on box deletion

- ilastik/applets/edgeTraining/opEdgeTraining.py
- ilastik/applets/multicut/opMulticut.py
by making sure feature names are strings, not bytes, and adjusting the calls to the `nifty` API.
> Fix multicut for python 3

- ilastik/workflows/carving/watershed_segmentor.py
Due to the change of the ilastiktools backend, there is no `out` parameter any more in `getSegmentation`. But it was never used from ilastik anyways.
> Remove unused argument in call to carving backend ilastiktools

- ilastik/applets/base/appletSerializer.py
- ilastik/applets/objectClassification/objectClassificationSerializer.py
- ilastik/applets/pixelClassification/pixelClassificationSerializer.py
- ilastik/applets/tracking/base/trackingSerializer.py
- ilastik/applets/tracking/manual/manualTrackingSerializer.py
- ilastik/applets/tracking/structured/structuredTrackingSerializer.py
In `appletSerializer.py`, we had two classes that were doing basically the same thing: `SerialPickledValueSlot` and `SerialPickleableSlot`. Both were used in the code-base without an apparent reason. Since `SerialPickleableSlot` was already a bit nicer, I have ditched `SerialPickledValueSlot`. Furthermore, I changed all occurrences of `SerialPickledValueSlot` to `SerialPickleableSlot`.
I have also improved the error handling in `SerialPickleableSlot` which often failed unnecessarily.
> `SerialPickledValueSlot` replaced with `SerialPickleableSlot`

- ilastik/workflows/carving/carvingGui.py
- ilastik/workflows/carving/carvingSerializer.py
- ilastik/workflows/carving/opCarving.py
fixes issue #1657
see also PR #1658
this is the carving fix for the python-2 side
Before serializing the objects, it is first checked, which objects are already present in the h5 file.
All objects in `opCarving._dirtyObjects` are still processed (old behaviour),
but additionally all objects not present in the file are also saved.
> fix carving import

- ilastik/shell/projectManager.py
There was a problem in the rare case that someone used command line arguments at project creation.
> cmdline project creation: Encode individual args to UTF8, not list

- bin/labelcounts.py
- ilastik/utility/exportFile.py
Problem was related to the python 3 switch, see #1673
In the two changed files, `map` was used and immediately subscripted, which of course resulted in an error, as map returns an iterator.
I've replaced the `map` with list comprehensions, where it is subscripted afterwards. 
fixes #1673
not related to https://github.com/ilastik/ilastik/issues/1671
> Fixes Object classification h5 table export

- tests/run_each_unit_test.sh
this test fails sometimes and we do not really know why or how
to trigger these fails. Therefore, it is disabled for the time
being.
> Disabled testObjectCountingMutiImageGui

- ilastik/applets/labeling/labelingGui.py
- ilastik/applets/layerViewer/layerViewerGui.py
- ilastik/workflows/carving/carvingGui.py
We need to pass the workflow class name to the VolumeEditor in order to be able to correctly initialise the 3D widget, i.e. we want the 3D widget to be visible only for workflows for certain workflows (currently only the carving workflow (?))
> Disable 3D widget by default. Enable 3D widget for Carving GUI when the data is 3D

- ilastik/widgets/stackFileSelectionWidget.py
Invocation of `decode_to_qstring` was causing errors in the DataSelectionApplet, since id doesn't exist. Those two functions are obsolete anyways since we're on Python 3
> Remove obsolete 'encode_from_qstring' and 'decode_to_qstring' functions

- ilastik/shell/gui/variableImportanceDialog.py
seems to be a qt4->qt5 transition quirk, sortByColumn expects a parameter specifiing the order.
fixes #1705 -> at least the feature importance part
I have also grepped over all files, no related issues to expect.
> Added sort parameter explicitly

- ilastik/workflows/carving/carvingGui.py
- ilastik/workflows/carving/preprocessingGui.py
- ilastik/workflows/carving/preprocessingViewerGui.py
In preprocessing for the carving workflow, watershed layer is set visible iif none of the result layers are visible
Fix for issue #1217 @akreshuk
> Fix for issue #1217, carving workflow: watershed shown after successful preprocessing

- ilastik_main.py
Also faulthandler is part of the standard library since python 3.3 => do not 'except ImportError'
Undoes hotfix of #1608
> enable faulthandler on all platforms.

- ilastik/applets/dataSelection/dataSelectionGui.py
fixed #1662 
Loading data from .h5 files was limited to data with 3 to 5 
dimensions. In this PR I have changed the lower limit to 2 dimensions. 
Side effect: Also non-image data (e.g. tables) might now show up in 
the imge selection dialog when loading from .h5 files with multiple 
datasets.
> Allow 2D images to be loaded from H5 files

- tests/test_applets/blockwiseObjectClassification/testOpBlockwiseObjectClassification.py
- tests/test_applets/conservationTracking/testConservationTrackingHeadless.py
- tests/test_applets/dataExport/testOpDataExport.py
- tests/test_applets/dataSelection/testDataSelectionSerializer.py
- tests/test_applets/dataSelection/testOpDataSelection.py
- tests/test_applets/dataSelection/testOpDataSelectionGroup.py
- tests/test_applets/edgeTraining/testOpEdgeTraining.py
- tests/test_applets/featureSelection/testFeatureSelectionSerializer.py
- tests/test_applets/featureSelection/testOpFeatureSelection.py
- tests/test_applets/objectClassification/testConvexHull.py
- tests/test_applets/objectClassification/testMissingValues.py
- tests/test_applets/objectClassification/testOperators.py
- tests/test_applets/objectClassification/testPrediction.py
- tests/test_applets/objectClassification/testTransferLabels.py
- tests/test_applets/objectCounting/testObjectCountingOperators.py
- tests/test_applets/objectExtraction/testOperators.py
- tests/test_applets/pixelClassification/testPixelClassificationHeadless.py
- tests/test_applets/pixelClassification/testPixelClassificationSerializer.py
- tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraFluo-N2DH-SIM-01.py
- tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithDivisions.py
- tests/test_applets/structuredLearningTracking/testStructuredLearningTrackingHytraWithMergers.py
- tests/test_applets/thresholdMasking/testThreholdMaskingSerializer.py
- tests/test_applets/thresholdTwoLevels/testOpAnisotropicGaussianSmoothing.py
- tests/test_applets/thresholdTwoLevels/testOpGraphcutSegment.py
- tests/test_applets/thresholdTwoLevels/testOpLabeledThreshold.py
- tests/test_applets/thresholdTwoLevels/testThresholdTwoLevels.py
- tests/test_utility/testCommandLineProcessing.py
- tests/test_utility/testOperatorSubView.py
- tests/test_workflows/axesOrderPreservation/testAxesOrderPreservation.py
- tests/test_workflows/dataConversion/testDataConversionWorkflow.py
This is a bit of a bummer:
`tests/test_applets/pixelClassification/testPixelClassificationHeadless.py` has been failing silently for a while now, but it went unnoticed, because of the way the test has been invoked. This commit makes sure that a test failure is reflected in the return value.
Summary:
basically just changed `nose.run` to `nose.main`. The only difference between those functions is that `nose.run` returns `True` if all tests pass and `False` if tests fail. One would have to handle the return value explicitly. `nose.main` will exit after test execution with a proper return value indicating successful test runs with `0` and failures with `1`
About the failing test:
@FynnBe one of your commits (8080c81c6a99122f6754aa8b0548d1554d80fc45) brought that failure to light (did not …
> Fix show invisible test fail

- ilastik/applets/base/appletSerializer.py
- ilastik/applets/batchProcessing/batchProcessingApplet.py
- ilastik/applets/counting/countingSerializer.py
- ilastik/applets/dataSelection/dataSelectionSerializer.py
- ilastik/applets/dataSelection/opDataSelection.py
- ilastik/applets/featureSelection/featureSelectionSerializer.py
- ilastik/applets/fillMissingSlices/fillMissingSlicesSerializer.py
- ilastik/applets/pixelClassification/pixelClassificationSerializer.py
- ilastik/applets/predictionViewer/predictionViewerSerializer.py
- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsSerializer.py
- ilastik/shell/projectManager.py
- ilastik/workflows/carving/carvingSerializer.py
- ilastik/workflows/carving/preprocessingSerializer.py
- tests/test_applets/dataSelection/testDataSelectionSerializer.py
- tests/test_applets/dataSelection/testOpDataSelection.py
- tests/test_applets/pixelClassification/testPixelClassificationHeadless.py
Motivation:
unfortunately in order to run workflows in headless mode the raw data that the models were trained on has to be available. this has been quite uncomfortable for the users especially when the raw data has significant size (GBs) and has to be carry around in order to run tasks in headless.
Current solution:
- if we're in headless and the raw data exists the flow is the same as before
- if we're in headless and the raw data does not exists, tell the `opDataSelection` to fake the raw data and we are able to proceed with the batch
- if we're in headless, raw data does not exists and `--retrain` was passed -> we inform the user that retraining is not possible
Faking the raw data is possible, due to additional attributes to the lane metadata (`DatasetInfo`) serialized to the project …
> No need for raw data to run a project in headless

- .gitmodules
- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/gui/startShellGui.py
- ilastik_main.py
- tests/launch_workflow.py
This is not something that's set in stone. It's more to start a discussion about what should be done with the `eventcapture` in ilastik. `eventcapture` is not compatible with `ilastik` atm, cause it uses legacy `PyQt4`. We have two options to consider, depending of whether or not we want to continue using `eventcapture` for GUI testing:
- we want to keep using it, then `eventcapture` needs to be ported to `PyQt5`
- we don't want to used it, thus remove it from ilastik dependencies (this PR). See also the discussion under https://github.com/ilastik/eventcapture/pull/1#issuecomment-360521605
> Remove eventcapture submodule from ilastik

- ilastik_main.py
this sort of fixes https://github.com/ilastik/ilastik/issues/1149
However, this is just a monkey patch, and as of sklearn 0.20 it will be included in sklearn itself.
reference: https://github.com/scikit-learn/scikit-learn/pull/9569
I suggest we merge this for the time being and I will open up a new issue that will remind us to remove the monkey-patch once `sklearn 0.20` is out and we have update our dependencies to use it.
Todo:
> Monkey patched sklearn

- tests/helpers/shellGuiTestCaseBase.py
__Problem__ was that some gui tests freeze for reasons I couldn't pin down yet.
This often led to our tests on the CIs timing out and thus, blocking this
resource.
With the timeout, the tests will continue at least, and save us some time there.
This is clearly not a solution to the problem, but a viable workaround, since this problem has been here for a long time.
For reference, the problem is rooted in these lines:
https://github.com/ilastik/ilastik/blob/68481f403fa330d680b374dae5cf653628ff49a6/tests/helpers/shellGuiTestCaseBase.py#L142-L146
There, the event `finished` is sometimes never set.
__Update__: Added tiny `nose` plugin that handles `ShutdownTimeout` Exceptions during `ShellGuiTestCaseBase.teardownClass`
such a shutdown timeout will show up in the nose test report like this: …
> Added timeout for gui test shutdown

- ilastik/headless_dummy_modules/PyQt5/__init__.py
- ilastik_main.py
Fixes #1812
Moved replacing the `PyQt5` module with our dummy module to the beginning of `ilastik_main.py`.
I could pin down the offending `PyQt5` import to the following statement:
```python
from lazyflow.utility.pathHelpers import PathComponents
```
Before, `PyQt5` was not in `sys.modules`, after, it was;
The delinquent seems to be `vigra`, which does the following in its `__init__`:
```python
try:
import pylab
except Exception as e:
pass
```
via some detours, this will import `PyQt5`.
I also added some traceback printing in order to ease tracking down causes for recurrence of this issue.
> Fix pyqt5 headless import

- ilastik/applets/dataExport/dataExportApplet.py
See https://github.com/ilastik/ilastik/issues/1422
Due to a bug in cpython (https://bugs.python.org/issue22433) the argument parser will misinterpret arguments with spaces in them, even if enclosed in quotes.
e.g. the following command-line will fail
```bash
python ilastik.py --headless --project MyProject.ilp --raw_data blah.h5 --prediction_maps blah_export.h5 --cutout_subregion "[[0,None,None,None,None],[1,None,None,None, None]]"
```
because of the space in the `--cutout_subregion` argument it is treated as a default positional.
This commit just ensures the command line argument help does not send any mixed messages.
> Fixed parser argument docs

- ilastik/applets/dataSelection/dataSelectionGui.py
A user made me aware that selecting multiple (n) datasets in dataselection applet (add new -> add separate image(s)) resulted in a single added image and (n-1) empty added lanes.
I fixed this by not returning directly when a dataset is successfully added. This is the "old", working behaviour.
Furthermore, I made sure, that each path returns the correct value.
@FynnBe , since this could potentially mess with your new filter resizing dialog thing, is there something I should test other than the following (which I have already confirmed works):
* loaded a 3D dataset (big), selcted all the filters, then added another one with `10` `z`-slices only. The dialog appears and lets me modify the selected filters appropriately.
> fixed loading of multiple datasets

- ilastik/headless_dummy_modules/PyQt5/__init__.py
- ilastik/ilastik_logging/default_config.py
- ilastik/shell/headless/headlessShell.py
- ilastik_main.py
Just wanted to silence the printing of the stacktrace that was introduced by me (:-1: ) and ended up adding some extra.
Summary:
* disabled printing of stacktrace on headless startup
* make invoking headless without arguments exit gracefully
* removed those `numpy.dtype size changed` warnings that showed up starting up ilastik which fixes #1652
> Enh silence headless mode startup

- ilastik/applets/dataSelection/opDataSelection.py
- ilastik/workflows/examples/dataConversion/dataConversionWorkflow.py
The export applet requires the `meta.original_axistags` to be set. This is done when axes are reordered, usually, because `forceAxisTags` is set to something.
This PR enforces that the reorderAxesOperator is always added to the chain. From what I read in the code of OpDataSelection, this seems to be assumed.
> Always reorder axes in data-selection applet

- .circleci/config.yml
- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/datasetInfoEditorWidget.py
- ilastik/applets/featureSelection/featureSelectionGui.py
- ilastik/applets/featureSelection/opFeatureSelection.py
- tests/test_applets/featureSelection/testFeatureSelectionSerializer.py
- tests/test_applets/featureSelection/testNewFeatureSelection.py
I would recommend merging this one in favor of changing the hdf5 reader (for now). The code change is way more minimal and I also found, that the hdf5 reader is not the only one allowing for no channel axis.
fixes #1845
ToDo:
checks against the `_NontransposedImage` axes (no channel added) whether a channel
has has been provided by the respective reader instance, or was later added.
> Fixes axes reordering for data that has no channel axis

- ilastik/applets/base/appletSerializer.py
- ilastik/applets/objectExtraction/objectExtractionSerializer.py
- ilastik/applets/trackingFeatureExtraction/trackingFeatureExtractionSerializer.py
- tests/test_applets/base/testSerializer.py
Creates the SerialObjectFeatureNamesSlot, which can handle deserialization of old tracking workflow projects. Those used to have their object feature names saved under a '0' key, which is no longer the case. Also adds tests for the new serializer.
Closes #1325, #1340
Deprecates GH-1869
> Fixes backwards compatibility issues with deserialization of old tracking workflows pojects

- ilastik/shell/gui/ilastikShell.py
extract to a temporary directory rather than the installation directory, otherwise admin permissions are needed on win
> Fix halloween

- ilastik/applets/dataExport/dataExportApplet.py
- ilastik/applets/tracking/base/opTrackingBaseDataExport.py
- ilastik/applets/tracking/base/pluginExportOptionsDlg.py
- ilastik/applets/tracking/base/trackingBaseDataExportApplet.py
- ilastik/applets/tracking/base/trackingBaseDataExportGui.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/plugins.py
- ilastik/plugins_default/tracking_contour_export.py
- ilastik/plugins_default/tracking_contours_with_head_export.py
- ilastik/plugins_default/tracking_csv_export.py
- ilastik/plugins_default/tracking_ctc_export.py
- ilastik/plugins_default/tracking_h5_event_export.py
- ilastik/plugins_default/tracking_json_export.py
- ilastik/plugins_default/tracking_mamut_export.py
- ilastik/plugins_default/tracking_mwt_export.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
- ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
- tests/test_applets/conservationTracking/testTrackingBaseDataExportAppletSerialization.py
As suggested by @akreshuk we should avoid adding plugin specific state to the `OpTrackingBaseDataExport`. This PR replaces Fiji-MaMuT specific `BigDataViewerFilepath` slots with a more generic `AdditionalPluginArguments` holding a dictionary with additional context information that can be used by the plugins, e.g. user input.
Additional changes:
* Add missing serialization to `TrackingBaseDataExportApplet`
* Refactor `TrackingExportFormatPlugin.export` interface to be consistent among its implementations and got rid of the `kwargs`
> Remove plugin specific slots from the OpTrackingBaseDataExport

- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py
The thresholding operator must update its GUI when new labels
are added to the pixel classification 'Training' applet. In order
to do that, the operator/applet was watching for changes in its
InputImage slot and it would try to update its widgets before its
InputChannelColors slot would be ready with the new label, causing
an "Index Error" when trying to find the new color of the new label.
This commit makes the applet watch instead for changes on the
InputChannelColors slot, so that it will always have the information
needed for updating the GUI when the watcher function fires.
1- Create a Pixel + Object classification workflow;
2- Add your image;
3 - Select features;
4 - Training Applet -> Scribble around with 2 colors
5 - Thresholding  Applet -> Just open the applet
6 - Go back to the …
> Fixes 'Index Error' when adding new label to pixel 'Training' applet

- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/objectClassification/opObjectClassification.py
Correctly serializes labels to be encoded as JSON. Also hides the
'Export' menu entry when not in --debug mode, instead of allowing
it to show up without any sub-menu entries.
It's worth noting, though, that the ex/importing of labels still
has some issues; exporting labels, clearing and then re-importing
may not reproduce the exact same labels in many cases.
> Fix json export of object classification labels

- ilastik.py
pytorch should not be a general dependency of ilastik
(torch is also not needed in ilastik.py)
> remove 'import torch'

- ilastik/applets/networkClassification/nnClassGui.py
- ilastik/applets/networkClassification/opNNclass.py
- ilastik/applets/pixelClassification/opPixelClassification.py
BlockShape becomes an optional slot in the regular OpLabelPipeline class of pixelClassification, rather than keeping an very similar version in opNNclass.py
> Beautify Play Button and simplify opNNclass

- ilastik/plugins_default/vigra_objfeats_convex_hull.py
- ilastik/plugins_default/vigra_objfeats_convex_hull3D.py
this makes sure that RGB images are not treated as 3D images
I am assuming this was a type, so the fix is a tiny one
fixes https://github.com/ilastik/ilastik/issues/1739
> made sure to check label dimensions, not image dimensions

- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/objectClassification/opObjectClassification.py
- ilastik/utility/exportFile.py
Fixes #1776 
The underlying problem was that `LabelInputs` and the objects were out of sync. The fix is quite small, and kind of drastic: If the segmentation changes, then all labels are removed.
One problem (should be present in general in workflows that have more than one input image): changing the probability map image will not emit any _dirtyness_ and will, therefore, be unnoticed. Annotations will be meaningless then. @akreshuk @stuarteberg, out of your head, would you have an idea how to fix this properly?
This also fixes the unrelated index error in https://github.com/ilastik/ilastik/commit/41fad9acf247ce7a29b62f5c99ddacd3a0fcefae that occurred upon export when with no objects in the image
a "fix" for broken projects could be a script, that deletes the labels. Or one just changes …
> Fix index error

- ilastik/shell/gui/ilastikShell.py
Adds a 'Documentation' item to the 'Help' menu
> Add documentation link in ilastik

- ilastik/applets/pixelClassification/opPixelClassification.py
- ilastik/utility/slottools.py
- ilastik/workflows/newAutocontext/newAutocontextWorkflow.py
In our lab we are using Ilastik with uint16 images. Unfortunately, the `autocontext` workflow was only working with `uint8` so far. Towards making this workflow compatible with our data, I modified  `opPixelClassfication` to also produce an uint16 probabilities output (by adding an `PredictionProbabilitiesUint16`). I further modified the `newAutocontextWorkflow` to also tolerate `uint16` input and dynamically select between the pixel classification`PredictionProbabilitiesUint8` and  `PredictionProbabilitiesUint16` output slot depending on the input dtype. 
This was tested by assembling and running a 2 stage Autocontext once with uint8 and uint16 as well as running the existing tests sucessfully.
Based on the existing tests it is not really clear to me how to best add a test for such a …
> Adapts Autocontext workflow for arbitrary dtype input

- ilastik/applets/tracking/base/trackingBaseDataExportApplet.py
- ilastik/applets/tracking/base/trackingBaseDataExportGui.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/applets/tracking/manual/opManualTracking.py
- ilastik/plugins.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
- ilastik/workflows/tracking/manual/manualTrackingWorkflow.py
- ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
Plugins export shouldn't be available for manual tracking since all plugins assume the existence of hypothesisGraph which is absent in manual tracking.
> Move tracking export lugins to trackingExportApplet. 

- .circleci/config.yml
- appveyor.yml
- ilastik/applets/edgeTraining/opEdgeTraining.py
- ilastik/applets/tracking/structured/opStructuredTracking.py
- ilastik/plugins_default/tracking_csv_export.py
- ilastik/plugins_default/tracking_mamut_export.py
- scripts/create-dev-env.sh
Upgraded all dependencies to build with conda compilers, so let's see...
Also, the following dependencies have had considerable upgrades:
* python: `3.6` -> `3.7`
* numpy: `1.12` -> `1.14`
* networkx: `1.x` -> `2.x`
* boost: `1.63` -> `1.68`
* h5py: `2.7.1` -> `2.9.0`
* hdf5: `1.10.1` -> `1.10.4`
> Dependency upgrade, test with newly build dependencies

- bin/train_headless.py
- examples/example_python_client.py
- ilastik.py
- ilastik/applets/dataSelection/datasetInfoEditorWidget.py
- ilastik/workflows/pixelClassification/pixelClassificationClusterized.py
- ilastik_main.py
- internal-startup-options.cfg
- tests/test_workflows/test_all/testAllHeadless.py
* Refactor `--clean_paths` option implementation
* Modify GUI launch command-line handling
* Remove direct access to argument parser instance
* Remove comments about modifying command-line args
> Refactor startup script and command-line parsing

- ilastik/applets/pixelClassification/FeatureSelectionDialog.py
- ilastik/applets/pixelClassification/labelingDrawer.ui
- ilastik/applets/pixelClassification/pixelClassificationGui.py
- Removes recursive handling of FreezePredictions dirty event - the handler itself was also setting the value of the slot, firing another event;
- Moves code that deals with visual configuration of the "live update" button into the proper .ui file;
- Cleans up the code a bit.
> PixelClassificationGui: Fixes recursive FreezePredictions dirty event and cleans up code

- ilastik/widgets/viewerControls.py
with ilastik/volumina@03c7f80755b449f19da877687c2ff87f345529f4 the rename has to
be propagated to ilastik.
Furthermore did some cleanup, removing old format syntax.
> rename: get_settings_and_export_layer -> prompt_export_settings_and_export_layer

- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
The `Object Classification Workflow`s were not correctly enabling applets when running with multiple lanes.
This PR ensures that the `_inputReady` function correctly reports its state as a boolean, which can then be correctly interpreted in operations such as `&=`.
- Create any "Object Classification Workflow";
- Create two lanes;
- Verify that the applet  after `Data Selection` is not enabled.
> Fixes "Object Classification Workflow" Data Selection readiness when using multiple lanes

- scripts/devenv.py
To keep consistency with `conda`, global command-line options have been moved to subcommands.
> Move global arguments to subcommands

- ilastik/applets/dataSelection/dataSelectionGui.py
allow to select multiple files in batch file selection dialog
This is part1 to fixing #2004
> Fix: allow to select multiple files in FileDialog

- .circleci/config.yml
- appveyor.yml
opengl on ci is too old (1.1, 1.2) so we would see errors
because of our pyqtgraph based 3d widget.
Summary:
* use `devenv.py` to spin up environment
* hide 3D view (requires https://github.com/ilastik/volumina/pull/242)
> don't show 3d widget

- ilastik/applets/counting/countingsvr.py
If pickled SVR object occupies more than 13 bytes, `pickle.dumps(self)`
makes an incomplete write, and unpickling from such source results in
the "pickle data was truncated" error.
Close #2067.
> Use full-length numpy raw dtype in SVR.writeHDF5

- .circleci/config.yml
- ilastik/applets/batchProcessing/batchProcessingApplet.py
- ilastik/applets/batchProcessing/batchProcessingGui.py
- tests/test_applets/batchProcessing/test_batchProcessingGui.py
Summay:
* added drag and drop support
* factored out BatchRoleWidget to handle data
* added custom exception (as opposed to asserts)
* removed "feature" where one would supply less number of "secondary" images
in batch processing
* improved docstring for `run_export`
* removed some legacy stuff
closes #2004
> Add drag-n-drop support in  batch processing applet

- .circleci/config.yml
- CONTRIBUTING.md
- appveyor.yml
- scripts/devenv.py
**Rationale:**
with _recent_ changes to conda, it will try to repair your env when installing new packages. This means with our current approach of force-removing `ilastik-meta` and symlinking you practically cannot install new packages into your current environment... Creating a new environment every time you want to install something drove me nuts!
In preparation for this I changed `ilastik-dependencies` package not to include `ilastik-meta` in the first place. (https://github.com/ilastik/ilastik-conda-recipes/pull/66)
**Summary:**
* Instead of force-remove - symlink, use `conda develop` to add local
`ilastik-meta` to packages discoverable by current python environment.
You can try it out right now with the update `ilastik-dependencies-no-solvers-package` with
```bash
python …
```
> use conda develop instead of symlinks

- ilastik/ilastik_logging/logging_config.json
Summary: this commit restores the original behavior of hiding the exceptions,
it doesn't solve any other problem.
previously there were some error messages in volumina that have never appeared
although they called `sys.excepthook` explicitly. See
https://github.com/ilastik/volumina/commit/2b09109b478a7f30787d9cecbad01ce82812a671
which introduced the change that made exceptions surface.
Together with this PR there is a PR in volumina:
https://github.com/ilastik/volumina/pull/253 that changes these
`logging.errors` to `logging.debug`. In order to hide these, this PR sets the
log level to warning.
> set log level in volumina.tiling explicitly

- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/headless/headlessShell.py
- ilastik/shell/shellAbc.py
- ilastik/utility/abc.py
- tests/test_utility/test_abc.py
`ShellABC` now uses `StrictABCMeta` metaclass and registers it's virtual
subclasses after their definitions.
PyQt5 uses a custom SIP metaclass for QObject and it's subclasses,
making it impossible to use plain `ABC` or `ABCMeta` for `ShellABC`
since `IlastikShell` inherits from `QMainWindow`.
It is possible to define a custom metaclass
`QObjectABCMeta(QObject.__class__, ABCMeta)`  and use it for `ShellABC`,
but in this case we always depend on `QObject`, even though some
subclasses should not use Qt at all (e.g. `HeadlessShell`).
We could use `ABC.register` to "virtually" subclass `ShellABC`. However,
because such subclass is not a real ABC subclass, it is possible to
create an instance even if some abstract methods are not implemented.
Therefore, we perform all necessary checks during …
> Add StrictABC and use it for ShellABC

- tests/test_applets/conservationTracking/testTrackingBaseDataExportAppletSerialization.py
When launching tests with pytest, "tearDown" has not been called, and
stale test project file has not been removed. Now the file is created
in a temporary directory, which is automatically removed after a test.
> Fix TrackingBaseDataExportApplet tests

- ilastik/excepthooks.py
`volumina.pixelpipeline.asyncabcs` was superseeded by `volumina.pixelpipeline.interface`
relates to https://github.com/ilastik/volumina/pull/254
> quickfix: import after volumina/pulls/254

- ilastik/applets/dataExport/dataExportGui.py
- ilastik/applets/tracking/base/trackingBaseDataExportGui.py
- tests/test_workflows/testObjectClassificationGui.py
Don't call `opLaneView.cleanupOnDiskView()` for all operators before
running export in a different thread because `OpDataExport.run_export()`
already calls `cleanupOnDiskView()` when needed.
Also, merge methods for exporting a single lane and all lanes because
they are almost identical.
Closes https://github.com/ilastik/ilastik/issues/2097.
> Don't call cleanupOnDiskView in DataExportGui

- ilastik/widgets/ImageFileDialog.py
without passing the options explicitly, the qt file dialog would be shown
native dialogs are much nicer (so all your usual favorites are available ...).
> pass empty dialog options to show native dialog

- ilastik/applets/dataSelection/opDataSelection.py
another one-liner that was somewhat hard to spot.
this removes one dimension of tupleing from the drange. Comparison here with numpy.dtype object to tuple fails when loading the project file. This failure is overshadowed by an exception occurring in cleanup...
fixes  #2102
> don't wrap drange in tuple

- .circleci/config.yml
- ilastik/workflows/carving/carvingTools.py
Use uint32 throughout the watershed function in `carvingTools.py`. This will use less memory and was not possible earlier, because nifty did not expose the correct dtypes (should be fixed now).
Also, use `projectScalarNodeDataToPixels` to go from superpixel labels to volumetric segmentation by default.
> Use uint 32 in carvingTools

- ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
This is a "hotfix" for structured tracking. Apparently, the wrong slot was connected.
Looking at this code, the sheer amount of it, although structured tracking and conservation tracking should be fairly similar, made me open up #2059
fixes #1943
> structured learning tracking: use correct slots for export

- ilastik/applets/counting/countingGuiBoxesInterface.py
Previously, interpreters relied on a custom `__subclasshook__` for
`isinstance` checks. Now, each interpreter is a subclass of
`InterpreterABC`, which is a proper abstract base class.
This change should make it easier to trace class relationships.
> Inherit all interpreters from InterpreterABC

- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/dataSelectionSerializer.py
- ilastik/applets/dataSelection/opDataSelection.py
This patch adds back some properties that were expected by the classic project deserialization system, so that `.ilp` files created with the new versions can be opened with previous versions of ilastik.
We should eventually have multiple deserialization methods and just pick the one that matches the `.ilp` version rather than having new and old properties mixed together as they are today.
fixes #2121
> Restores .ilp forward compatibility

- ilastik/applets/dataSelection/datasetInfoEditorWidget.py
- ilastik/applets/dataSelection/opDataSelection.py
Fixes issues with internal paths when serializing `RelativeFilesystemDatasetInfo`, as well as when converting to/from it using `DatasetInfoEditorWidge`
> Fixes serialization of relative fs datasetinfo

- scripts/devenv.py
Due to https://github.com/ilastik/ilastik/pull/2080, `install_package_dev` requires
`conda-build` to be installed. It this is not the case, `devenv.py create` fails only
after the lengthy installation process.
This PR explicitly checks the availability of `conda-build` before proceeding
with the script's command.
> Fail when conda-build is not installed

- ilastik/applets/counting/countingDataExportGui.py
- ilastik/applets/dataExport/dataExportGui.py
- ilastik/applets/dataExport/opDataExport.py
- ilastik/applets/objectClassification/objectClassificationDataExportGui.py
- ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py
- ilastik/applets/tracking/base/trackingBaseDataExportGui.py
Removes the exported, from-disk layers of the export applets. These layers were a bit problematic on windows, as they claimed a handle to the underlying file, making it impossible to overwrite such file in subsequent exports.
Furthermore, this layer would often show stale data, like a previous run of ilastik, or even some run from a different lane if the user was using a static export path like `/tmp/my_export.h5`
Fixes #1547
> Removes exported file layer from export applet and export operator

- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/datasetInfoEditorWidget.py
- ilastik/applets/dataSelection/datasetInfoEditorWidget.ui
- ilastik/applets/dataSelection/opDataSelection.py
- tests/test_applets/pixelClassification/testPixelClassificationGui.py
Reverts automatic inner dataset selection (for, e.g. .h5 or .n5 files with multiple internal datasets) to classic logic, where remembered paths will persist only in a session, but will not leak over other projects.
Fixes pre-selected value in dataset combobox in `DatasetInfoEditorWidget`.
Adds a notice to the UI, informing the user that by changing the inner dataset path all his changes to the other DatasetInfo editor fields will be discarded in favor of the default values; Since we can't know in advance what kind of data will be found in the newly selected dataset, we can't apply the configurations (e.g. axis tags, normalization values) to that dataset, and therefore it's nice to notify the user.
Fixes #2129
> Fix automatic inner dataset path selection

- ilastik/applets/batchProcessing/batchProcessingApplet.py
- tests/test_applets/pixelClassification/testPixelClassificationHeadless.py
The ability to use a `PreloadedDatasaetInfo` in batch processing (which is useful when using ilastik inside a python script) was lost during the big `DatasetInfo` overhaul. This patches restores that capability and adds a test which is very much based on `examples/example_python_client.py`
Fixes #2137
> Restores ability to use PreloadedDatasetInfo when batch processing

- ilastik/applets/dataSelection/opDataSelection.py
Old projects might have input data without axistags. The new deserializer was always expecting for that key to be present.
This PR changes this behavior to allow for data without axistags, using the legacy 'axisorder' if present or defaulting to the vigra default axis order if hat is not present either.
> Fixes deserialization issue with sample projects: more lenient with 'axistags'

- ilastik/applets/batchProcessing/batchProcessingGui.py
- ilastik/applets/cropping/croppingGui.py
- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/featureSelection/featureSelectionGui.py
- ilastik/applets/labeling/labelingGui.py
- ilastik/applets/labeling/labelingImport.py
- ilastik/applets/multicut/multicutGui.py
- ilastik/applets/networkClassification/nnClassGui.py
- ilastik/applets/pixelClassification/pixelClassificationGui.py
- ilastik/shell/gui/ilastikShell.py
- ilastik/widgets/ImageFileDialog.py
- ilastik/widgets/stackFileSelectionWidget.py
- ilastik/workflows/carving/carvingGui.py
- tests/widgets/test_ImageFileDialog.py
PreferencesManager is a singleton that controls access to a preferences
file on disk. Since Python has module-level variables, singleton classes
can be replaced with private variables and public functions in a module.
Needs https://github.com/ilastik/volumina/pull/260.
> Replace PreferencesManager with module functions

- ilastik/applets/dataSelection/opDataSelection.py
default location changed from home-directory to project file location by overriding the base-class method.
`default_output_dir` will be accessed in `OpDataExport` to determine the output location for our magic value `{dataset_dir}`.
> Quickfix: changed default export path for project-internal data

- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/datasetDetailedInfoTableView.py
* determine row position for drop events
* convert paths to `pathlib.Path objects` (assumed by consuming function)
* changed signature of `DataSelectionGui.addFilePaths` in order to use with
two-parameter signal and partial (moved `rowIndex` to last position in
parameters).
fixes #2143, fixes #1251, fixes #1013
> fix drag and drop

- ilastik/applets/objectClassification/objectClassificationDataExportGui.py
- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/objectExtraction/objectExtractionGui.py
- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py
- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
Added the "object identities" layer to the set of exportable sources.
In order to enable some workflows that take might take object identities as an input (e.g. atlas/prediction mask) it is really beneficial to have this output in object classification available not only via right click export.
fixes #2106, fixes #1868
> Quickfix export objectids

- ilastik/applets/dataSelection/dataSelectionSerializer.py
- tests/conftest.py
This fixes our functionality of replacing the path of an image file after it has been moved.
Checks whether `filepath` is in the h5 group already and removes it before
updating if necessary. Also made sure to save the new filepath utf-8 encoded.
"+" some sneaky black changes courtesy of my pre-commit hook...
> Remove filepath in h5 before updating

- ilastik/applets/tracking/structured/opStructuredTracking.py
- ilastik/plugins_default/tracking_csv_export.py
- ilastik/plugins_default/tracking_ctc_export.py
- ilastik/plugins_default/tracking_json_export.py
- ilastik/plugins_default/tracking_mamut_export.py
- tests/test_applets/structuredLearningTracking/testOpStructuredTracking.py
* Replaced by nx.add_path(graph, [...]) since NetworkX 2.1
* https://github.com/networkx/networkx/commit/6b1ce03f485076d39994e8d624bbf6ca82466eb9
* graph.node -> graph.nodes
> Fix depreciated methods for NetworkX 2.4 and above

- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
In object classification headless mode, using either of
* `--export_object_prediction_img`
* `--export_object_probability_img`
* `--export_pixel_probability_img`
will now produce a warning. We should aim at removing those options in the future. They are not mentioned in our docs and
> There should be one-- and preferably only one --obvious way to do it.
We have the `--export_source` param to do that.
> deprecated undocumented command line args

- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
Multicut will currently freeze when used with more than one lane. See #2189 for more background. This PR disables the multi-lane functionality for now until the issue is fixed.
> Disable multilane for multicut

- ilastik/applets/edgeTraining/edgeTrainingGui.py
- ilastik/applets/multicut/multicutGui.py
We only have a single solver to choose from these days anyway.
SO it's just overcrowding the ui for normal users.
Also addresses the problem of live-update being disabled when loading a file with annotations present #2062
> multicut: show solver selection only in debug mode

- ilastik/applets/dataSelection/dataSelectionSerializer.py
If the missing file was caused because the original link was relative
and the project file was moved, then the previous behavior was to
try to instantiate a RelativeFilesystemDatasetInfo from the fixed file
path. That file could very well exist in a path that could not be
expressed relative to the current project file (i.e. in the same folder
or in any subfolder), raising an exception.
This patch forces fixed missing files to use FilesystemFatasetInfo,
which is an absolute path and therefore cannot cause this problem.
> Force FilesystemDatasetInfo when recovering from missing files

- appveyor.yml
- ilastik/utility/gui/threadRouter.py
- tests/conftest.py
- tests/test_ilastik/widgets/test_ImageFileDialog.py
It seems like there is slowdown because when GUI tests run in the end which may result in timeouts.
> Execute legacy GUI tests before anything else

- bin/labelcounts.py
- ilastik/applets/counting/countingSerializer.py
- ilastik/applets/dataSelection/dataSelectionSerializer.py
- ilastik/applets/featureSelection/featureSelectionSerializer.py
- ilastik/applets/fillMissingSlices/fillMissingSlicesSerializer.py
- ilastik/applets/pixelClassification/pixelClassificationSerializer.py
- ilastik/applets/predictionViewer/predictionViewerSerializer.py
- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsSerializer.py
- ilastik/applets/tracking/base/trackingUtilities.py
- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/projectManager.py
- ilastik/workflows/carving/carvingSerializer.py
- ilastik/workflows/carving/opCarving.py
- ilastik/workflows/carving/preprocessingSerializer.py
- tests/test_ilastik/test_applets/conservationTracking/testConservationTrackingHeadless.py
- tests/test_ilastik/test_applets/conservationTracking/testTrackingBaseDataExportAppletSerialization.py
- tests/test_ilastik/test_applets/featureSelection/testFeatureSelectionSerializer.py
accessing the `.value` member on h5py groups is deprecated.
Gets rid of
```
H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
```
> mnt: hdf5dataset.value -> hdf5dataset[()]

- lazyflow/operators/ioOperators/UfmfParser.py
the quest of reducing number of warnings during tests...
gets rid of
`DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead`
> mnt: numpy.fromstring -> numpy.frombuffer

- lazyflow/operators/ioOperators/opStreamingH5N5Reader.py
Adds support for reading the `axes` attribute in N5 datasets to improve compatibility with the neuroglancer convention.
> Adds support for neuroglancer-like axistags in .n5

- ilastik.py
The previous method of filtering would not leave even the default installation paths of cplex or gurobi in PATH.
This commit allows for paths like
`C:\something\arbitrary\gurobi*\**`
`C:\something\arbitrary\cplex*\**`
which is not possible with `pathlib.PurePath.match` alone.
> fix leaving cplex and gurobi in PATH

- ilastik/applets/dataSelection/dataSelectionSerializer.py
- ilastik/applets/dataSelection/opDataSelection.py
- lazyflow/operators/valueProviders.py
- tests/test_lazyflow/test_operators/testValueProviders.py
when deserializing a project in headless mode with the training data missing,
the axistags have to be deserialized, too. Otherwise ilastik guesses them.
If this guess is wrong, the data doesn't fit the workflow anymore.
* fixes running ilastik projects in headless without the data.
* fixes memory allocation for data for missing data in headless (previously an array of the same size as the missing image would have been allocated in memory).
> supply loaded axistags to PreloadedArray

- ilastik/app.py
- ilastik/utility/commandLineProcessing.py
Removes a major annoyance from ilastik's headless mode: allowing for concurrent access to project files per default.
Summary:
* `--readonly` flag kept. Projects will be opened per default with read access in GUI mode, without read access in headless mode. the `--readonly` flag now takes a parameter to allow changing this behavior.
fixes #1870
> open project files as readonly per default in headless

- lazyflow/utility/bigRequestStreamer.py
Was not giving the correct answer if the axis order was not xyz / xyt
Fixes #2271 
Tests pass locally on windows
> Bug fix for computing block RAM size in lazyflow 

- ilastik/__init__.py
- ilastik/applets/base/appletSerializer.py
- ilastik/applets/pixelClassification/pixelClassificationSerializer.py
- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
As [pointed out](https://forum.image.sc/t/ilastik-project-file-cannot-be-loaded-on-another-computer/40545) by user JesseDicello,  deserialization of Pixel Labels still had some problems leftover from the big 1.3.3 object classification workflow cleanup.
This PR  fixes axis reordering in Object Classification Workflows so that they are identical to 1.3.2, and so that they will be serialized in an identical manner.
It also corrects the bad assumption that all pixel labels were being saved without dropping dummy axis; labels will now be read back using the current axis keys of the label slot (except for some version-specific exceptions needed for backwards compatibility).
Finally, labels are being saved with their axistags as attributes in the H5 dataset, so that at least this part of the …
> Fixes pixel label deserialization

- bin/change_axisorder.py
- ilastik/applets/dataSelection/dataSelectionApplet.py
- lazyflow/operators/ioOperators/ioOperators.py
- tests/test_ilastik/test_applets/conservationTracking/testTrackingBaseDataExportAppletSerialization.py
- tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
- tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationSerializer.py
- tests/test_ilastik/test_applets/thresholdMasking/testThreholdMaskingSerializer.py
- tests/test_lazyflow/testH5py.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpH5N5WriterBigDataset.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpInputDataReader.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpStreamingH5N5SequenceReaderS.py
- tests/test_lazyflow/test_utility/testPathHelpers.py
`h5py.File` default file mode will be changed from `a` -> `r` and our code seemed to rely on this default behavior explicitly.
I went through the code and inserted appropriate modes if not specified before.
gets rid of
```
H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in
h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or
set the global default h5.get_config().default_file_mode, or set the environment
variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x',
'a'. See the docs for details.
```
> specify h5py/z5py file modes explicitly

- ilastik/applets/counting/countingDataExportGui.py
- ilastik/applets/layerViewer/layerViewerGui.py
- ilastik/applets/networkClassification/nnClassGui.py
- ilastik/applets/networkClassification/nnClassificationDataExportGui.py
- ilastik/applets/objectClassification/objectClassificationDataExportGui.py
- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/pixelClassification/pixelClassificationDataExportGui.py
- ilastik/applets/pixelClassification/pixelClassificationGui.py
- ilastik/applets/predictionViewer/predictionViewerGui.py
- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py
- ilastik/workflows/voxelSegmentation/slicGui.py
- ilastik/workflows/voxelSegmentation/voxelSegmentationGui.py
Adjusts usage of `NormalizableLayer` (and its descendants such as `AlphaModulatedLayer`) everywhere, removing he `range` parameter, which wasn't doing anything useful.
This PR only exists because of https://github.com/ilastik/volumina/pull/265 and therefore should be merged together with that.
> Removes the range parameter from usage of volumina's NormalizableLayer

- ilastik/applets/objectClassification/opObjectClassification.py
- ilastik/utility/exportFile.py
Tiny fix when exporting object classification to h5 table. Previously this would raise an exception when an image was empty (=no objects).
also made sure callbacks of the progress signal would be unsubscribed in any case. Previously those would've been kept in case of error (and progress would be reported n-times).
maybe fixes #2279
> Fix obj export empty image

- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py
Solves an issue with https://github.com/ilastik/volumina/pull/255
Two assignments to Final Layer visible property result in a race between signals
Is there a reason why this layer initially starts as hidden?
> Update layers visibility in thresholding

- tests/test_ilastik/test_workflows/testObjectClassificationGui.py
- tests/test_ilastik/widgets/test_ImageFileDialog.py
final layer is recreated when setupLayers is called (this is triggered by
clicking the apply threshold button).
> fix Object Classsification Gui test: make sure to get current final layer

- ilastik/shell/gui/ilastikShell.py
`(proj, work) in mostRecentProjectPaths` was false because recent paths now come from JSON, and project-workflow pairs were lists, not tuples.
Closes https://github.com/ilastik/ilastik/issues/2321
> Don't keep duplicates in recent projects list

- ilastik/plugins_default/test_objfeats.py
add mandatory keys to feature descriptions.
Otherwise selecting _all_ features in debug mode will lead to failure in export.
fixes #2256
> make test-features exportable

- ilastik/applets/labeling/labelingGui.py
- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/workflows/tracking/common.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
- ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
I guess someone buried the knowledge that it's not very beneficial for solving the tracking problem to have a lot of merge objects somehow implicitly in the assumption that no one will add more than 14 objects. If we want to discourage it, we should make it explicit somewhere and not rely on "people just not doing it".
This PR allows users to add as many merged objects as they want. We should deal with the algorithmic problems this imposes somewhere else.
* made sure new colors are added to colortable when initial size is exceeded.
* made sure naming of new labels follows the scheme `x Objects`.
fixes #2294
> fixed error when adding more than 15 objects in object count classifier

- ilastik/applets/serverConfiguration/configStorage.py
tiktorch servers were saved to ilastikrc instead of preferences.
In general nothing is ever written to ilastikrc, this is tackled in
#2348 with a proper fix.
This commit rather makes it not error out in the meantime - enabling tutorials
to go smoothly.
closes #2351
> Quickfix nn wf save servers

- ilastik/applets/serverConfiguration/configStorage.py
- tests/test_ilastik/test_applets/test_serverConfiguration/test_configStore.py
quickfix! Completely remove saving configured server to .ilastikrc
this is properly tackled in  #2331 by saving to prefs
removing the save action fixes #2355
> completely removed persisting servers to .ilastikrc

- lazyflow/operators/ioOperators/opFormattedDataExport.py
This updates ilastik to use the new Slice5D.to_tuple implementation, which returns
`Tuple[Tuple[int|None], ...], [Tuple[int|None], ...]]`
instead of
`Tuple[np.ndsarray, np.ndarray]`.
Requires `ndstructs 0.0.5dev0`
> Uses new Slice5D.to_tuple from ndstructs

- lazyflow/operators/ioOperators/opExportMultipageTiff.py
- lazyflow/operators/ioOperators/opTiffReader.py
- lazyflow/utility/__init__.py
- lazyflow/utility/roiRequestBuffer.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpTiffReader.py
- tests/test_lazyflow/test_utility/conftest.py
- tests/test_lazyflow/test_utility/testRoiRequestBatch.py
- tests/test_lazyflow/test_utility/testRoiRequestBuffer.py
With this PR we finally switch from `tifffile 0.4.post2` which we have been building ourselves. `tifffile` even changed there versioning scheme in the meantime :o . I tried to keep the changes minimal as possible (e.g. still using vigra to read the pages), but ended up having to modify `OpExportMultipageTiff` quite a bit.
TODO:
> API changes for tifffile upgrade

- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py
There seems to be pattern common in the code that invites copy paste errors that are somehow hard to spot. Things like
```python
self.topLevelOperatorView.InputChannelColors.notifyMetaChanged(bind(self._updateGuiFromOperator))
self.__cleanup_fns.append(
partial(self.topLevelOperatorView.InputImage.unregisterMetaChanged, bind(self._updateGuiFromOperator))
)
```
This looks unsuspicious because of long mangled names. The problem there is that the signal is unregistered from a different slot that in has been subscribed to. The problem now is that the `_updateGuiFromOperator` function is not removed from the slot. GUI is destroyed first, then the operators are cleaned up. In the avalanche of notifications, functions might be fired that manipulate the gui and result in issues like #2376. I will …
> add proper unsubscribe callbacks to cleanup funcs

- ilastik/applets/edgeTraining/edgeTrainingGui.py
- ilastik/applets/edgeTrainingWithMulticut/edgeTrainingWithMulticutGui.py
- ilastik/applets/multicut/multicutGui.py
Reorganized the code a bit after finding a good old `RuntimeError: wrapped C/C++ object of type QPushButton has been deleted` error when _closing_ the multicut workflow at the training stage.
Made inheritance from `LabelViewerGui` explicit by converting `EdgeTrainingGui` to a Mixin. Also removed some of the explicit `ParentClass.method` calls and let this be handled with `super`.
> Cleanup/Fix of Multicut Gui Code

- ilastik/plugins_default/tracking_ctc_export.py
- lazyflow/operators/ioOperators/opTiffReader.py
with tifffile 0.17 (that we currently distribute) tifffile is not longer shipped as part of skimage, but as a dependency.
also `tifffile.imsave` is deprecated in favor of `tifffile.imwrite`
> use conda installed tifffile in plugin

- ilastik/workflows/newAutocontext/newAutocontextWorkflow.py
- lazyflow/operators/valueProviders.py
probably not elegant, and possibly dangerous, open to suggestions here. But at least it works.
Currently, autocontext will start retraining in batch processing (starting with the second image), [user report](https://forum.image.sc/t/ilastik-autocontext-stage2-probability-output-range-incorrect-in-headless-mode/46603). This costs time, and even worse - will retrain without the data...
This only pops up in autocontext (the same is done in pixel classification, too) because one classifier output is input for the next stage :/
cache value can now be forced, without setting it's output to dirty.
> add possibility to silently force cache values

- bin/labelcounts.py
the script was in a defunct state.
Done the more or less minimal changes to get it working again.
This should probably be redone completely at some point (using the ilp parser library), but I would say this is very low priority now.
> Make the labelcount script count again

- ilastik/applets/dataSelection/dataSelectionGui.py
This fixes batchprocessing in Gui mode for workflows with limits on the lane
numbers. Buttons in the summary view are deleted in batch processing to a bug
#2380. With this workaround, batch
processing at least works for all workflows again.
Also to be a bit more cautious callbacks that tough the Gui are cleaned up and
made sure to run in main thread.
fixes #2270
fixes #2250
> Workaround for batch-processing issue

- ilastik/app.py
Running ilastik in the headless mode caused it to crash because
attempting to migrate preferences indirectly caused import of the
volumina package, which, in turn, imports Qt GUI libraries that could
be unavailable in the headless mode.
Closes https://github.com/ilastik/ilastik/issues/2385.
> Do not migrate preferences in the headless mode

- ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
I guess the only person that can tell why it wasn't there would be @akreshuk. Is there a reason batch was hidden here? I rummaged a bit in history but couldn't find an explanation. Was this just an oversight?
> enable batch processing applet in tracking with learning

- lazyflow/request/request.py
- tests/test_lazyflow/test_request/test_request.py
The initial step in the direction of a bit more transparent concurrency control in volumina pixelpipeline
> Add futures like add_done_callback to requests

- ilastik/applets/serverConfiguration/serverConfigDrawer.ui
Added a link pointing to [the prerequisites section](https://www.ilastik.org/documentation/nn/nn#pre-requisites-for-running-the-workflow) of the NN workflow docs:
> Added link to docs from serverconfig drawer

- ilastik/applets/counting/countingGuiBoxesInterface.py
- ilastik/applets/edgeTraining/edgeTrainingGui.py
- ilastik/applets/edgeTrainingWithMulticut/edgeTrainingWithMulticutGui.py
- ilastik/applets/edgeTrainingWithMulticut/opEdgeTrainingWithMulticut.py
- ilastik/applets/multicut/multicutGui.py
- ilastik/applets/pixelClassification/pixelClassificationGui.py
- ilastik/utility/gui/__init__.py
- ilastik/utility/gui/widgets.py
- ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
- lazyflow/operators/opBlockedArrayCache.py
Multicut has been misbehaving with multiple lanes in the past - that's why it was single lane now for a while. This PR enables using multiple lanes again and dodges some of the previous pitfalls:
fixes #2061, live update is synced via a broadcasting slot
fixes https://github.com/ilastik/ilastik/issues/2189 , this was cause by circular updates in the multi-lane setting. Prevented this by not sending signals from widgets currently being updated in operator callbacks
fixes #1858, live update now inherently synced via callbacks
fixes #2139 by hiding prediction layer if no classifier is trained
commits can be reviewed in order.
superseeds #1910
> Enable multicut with multiple lanes

- ilastik/widgets/stackFileSelectionWidget.py
Fixes error message of "variable used before assignment" when selecting a bad directory in the Add Stack dialogue. Also disables the Ok button when no files are selected.
> Stack selection improvements

- ilastik/applets/dataSelection/opDataSelection.py
- lazyflow/operators/__init__.py
- lazyflow/operators/valueProviders.py
- tests/test_lazyflow/test_operators/testValueProviders.py
When running ilastik in headless, we do not require training data to be present. However, ilastik will try to train its classifier, if it has not been saved to the project file. This can lead to training from all zeros when data is inaccessible.
This is of course not acceptable.
fixes https://github.com/ilastik/ilastik/issues/2299
> Make sure ilastik errors when trying to access missing data in headless

- ilastik/applets/edgeTraining/opEdgeTraining.py
- ilastik/applets/edgeTrainingWithMulticut/opEdgeTrainingWithMulticut.py
- ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
normally, we like to still see cache values, even if input changes to enable
"correct where it's wrong" type of labeling.
When superpixels change, the old predictions don't make any sense at all, so
caches are flushed.
fixes #1488 
fixes #2154
> clear caches when superpixel input changes

- ilastik/applets/base/appletSerializer.py
- tests/test_ilastik/test_applets/base/testSerializer.py
looks like we didn't compress when we really should've :/
Anecdotal space saving for a project I have:
From 6.9 GB -> 40 MB...
and yeah the added test now suddenly using fixtures, I know. But I couldn't get myself to hacking it into one of the other tests (especially because a  larger block size is required, or compression will not have an effect on size of the final file...
fixes https://github.com/ilastik/ilastik/issues/1205
> made sure compression is passed through to the serialization of data

- ilastik/applets/multicut/opMulticut.py
quick fix for a problem I found using multicut (didn't bother to open an issue).
clicking "live multicut" before training a classifier would result in an error.
We should probably be more user-friendly here, too, and not have that button enabled if RF is not trained (https://github.com/ilastik/ilastik/issues/2414).
> fix doing "live" multicut without trained classifier

- lazyflow/operators/ioOperators/opExportSlot.py
I don't think there is an issue about this, but @constantinpape brought this up:
currently we overwrite image files with the same file name. In general this makes sense, of course, but for hdf5/n5 files, it is possible to add multiple datasets to the result file.
This PR changes the behavior; hdf5/n5 files are now opened in append mode, datasets are overwritten if already present.
I have opened #2410 in order to keep track of progress on hdf5 table export. I think we should merge this already and live with not being able to do the same for the h5 table export for now.
> Change default file mode when writing hdf5/n5 image files

- ilastik/applets/edgeTraining/opEdgeTraining.py
Salvaged from PR #1910 (4ece7b62ccd3c73aa007915cdd282601102e6b61)
fixes #2085
if only one class is labeled, the matching probabilities are returned right away without going through prediction first.
CC: @paulhfu
I'd say we can close #1910 after this is merged
> short circuit prediction if only one class is annotated

- bin/export_from_tiled_volume.py
- ilastik/applets/counting/opCounting.py
- ilastik/clusterOps.py
- ilastik/workflows/voxelSegmentation/classifierOperators.py
- ilastik/workflows/voxelSegmentation/opSlic.py
- lazyflow/classifiers/vigraRfAdaptiveMaskPixelwiseClassifier.py
- lazyflow/classifiers/vigraRfPixelwiseClassifier.py
- lazyflow/operators/classifierOperators.py
- lazyflow/operators/ioOperators/ioOperators.py
- lazyflow/operators/ioOperators/opDvidVolume.py
- lazyflow/operators/ioOperators/opRESTfulPrecomputedChunkedVolumeReader.py
- lazyflow/operators/ioOperators/opStreamingH5N5Reader.py
- lazyflow/operators/opCompressedCache.py
- lazyflow/operators/opFilterLabels.py
- lazyflow/roi.py
- lazyflow/utility/bigRequestStreamer.py
- lazyflow/utility/helpers.py
- lazyflow/utility/io_util/multiprocessHdf5File.py
- lazyflow/utility/roiRequestBatch.py
- lazyflow/utility/roiRequestBuffer.py
- tests/test_lazyflow/test_utility/test_helpers.py
In `numpy` default `int` type is `long`. [On windows, default `long` is 32 bits](https://numpy.org/devdocs/reference/arrays.scalars.html#integer-types).
added a tiny helper function that should be used when reducing shapes to their volume in order not to fall into this issue
ref: [user report on image.sc](https://forum.image.sc/t/overflow-warning-in-ilastik/48790?u=k-dominik)
> Make sure to use int datatype for potentially large volumes

- ilastik/applets/edgeTrainingWithMulticut/edgeTrainingWithMulticutGui.py
- lazyflow/slot.py
That's a brief one.
before, live update would be turned off silently leaving the button in an inconsistent state when "update multicut" was pressed.
> restore live update value after updating multicut

- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
PixelClassification + Object Classification, while not recommended, should work properly. Right now projects are not loaded correctly (see #2244)
this prevents dirty notifications bubbling up. In the combined workflow, the pixel classification classifier is set after the object classifier is added.
Hence, it is marked as dirty and discarded. Even worse, it sets the segmentation dirty, which in turn discards the object annotations.
Setting classifiers "silently" is exactly what you want there. No dirty notifications bubbling ~~up~~ down on added lanes.
fixes #2244
> PC + OC workflow: fix loading projects

- lazyflow/operators/generic.py
- tests/test_lazyflow/test_operators/testOpMultiArraySlicer2.py
Removed calls to `setDirty` for outputslots in `setupOutputs` of `OpMultiArraySlicer2`. I can not think of a reason why this was there in the first place. `Operator._setupOutputs` has the necessary logic in place.
~~while I couldn't exactly reproduce the reported issue~~, I could create a similar one when enabling users to add singleton axis in export (see https://github.com/ilastik/volumina/pull/263).
Update: I managed to reproduce the original issue - with a bit of trickery. I also made sure this does not happen anymore with this branch/pr:
1. In pixel classification, use 5d dataset with singletons in `t` and `z`.
2. train a classifier
3. In export: remove axes `t` and `z` (or just one of them), when closing the dialog, you'll get an error. Reopen the dialog and change some other …
> Fix OpMultiArraySlicer2 dirty to early

- ilastik/applets/counting/opCounting.py
- lazyflow/operators/generic.py
- lazyflow/roi.py
- tests/test_lazyflow/test_operators/testOpMaxChannelIndicator.py
* removed logic that would return `0` pixels for tied predictions.
* unified behavior with the Simple Segmentation export slot (no `0` pixels there).
* made sure not to reintroduce #1033
fixes #2025
> Simplify logic in ArgMaxChannelIndicator; get rid of transparent pixels

- ilastik/applets/neuralNetwork/nnClass.ui
- ilastik/applets/neuralNetwork/nnClassApplet.py
- ilastik/applets/neuralNetwork/nnClassGui.py
- ilastik/applets/neuralNetwork/nnClassificationDataExportGui.py
- ilastik/applets/neuralNetwork/tiktorchController.py
Summary:
* This sets the classification applet up as a "predict" only for now.
* initially hides prediction layers in export (would start predicting there right away otherwise)
* model "upload" rephrased to model "initialization"
NN Drawer:
before:
after:
> Neural Network Classification workflow cleanup

- lazyflow/operators/tiktorch/classifier.py
- tests/test_lazyflow/test_operators/test_tiktorch/test_classifier.py
Previously, the output shape was hard-coded. This breaks many networks ;).
Derive output shape from model information  returned by server.
> Handle outputshape returned by server

- ilastik/app.py
- ilastik/config.py
- ilastik/workflows/neuralNetwork/_localLauncher.py
- ilastik/workflows/neuralNetwork/_localWorkflow.py
This starts the local server from a local environment (if `tiktorch.sever` and `pytorch` are in the environment).
Adds a command line flag to specify cpu/cuda device to use: `--nn_device` (calling it `nn` as it can also be `cpu`).
The local workflow can now be configured like
```bash
python ilastik.py 
--tiktorch_executable ... \
--nn_device ...
```
> Neural Network Workflow - start 'local' server from environment

- ilastik/widgets/featureTableWidget.py
- tests/test_ilastik/widgets/test_featureTableWidget.py
> Prevent Ctrl+A shortcut toggling 2d/3d state in feature table

- CONTRIBUTING.md
- notebooks/Readme.md
- notebooks/pixel_classification_api/Readme.md
- notebooks/pixel_classification_api/environment.yml
- notebooks/pixel_classification_api/pixel-classification-api.ipynb
This (hopefully) fixes the notebook example by adding missing package and a note about strict channel priority.
Also added setting up conda with strict channel priority as a first setup step. It's not default yet, but I think we've been using it for so long, not realizing that this is something worth mentioning.
> Fix notebook ex

- ilastik/widgets/featureDlg.py
- ilastik/widgets/featureTableWidget.py
Left is patched, right is current
Old feature dialog icon rendering used incorrect sizeHints
which resulten in upscaling and pixelization of checkmarks and
3d / 2d toggles
> Improve feature dialog rendering

- ilastik/applets/objectClassification/objectClassificationApplet.py
The gui would only be properly initialized for the first lane, now this is done for every lane. As a result, ilastik would be in brush mode, not in object annotation mode.
fixes https://github.com/ilastik/ilastik/issues/2470
fixes https://github.com/ilastik/ilastik/issues/1921
> initialize all object classification gui lanes once accessed the first time

- ilastik/applets/edgeTraining/edgeTrainingSerializer.py
- ilastik/applets/edgeTraining/opEdgeTraining.py
- ilastik/applets/edgeTrainingWithMulticut/opEdgeTrainingWithMulticut.py
- lazyflow/operator.py
- lazyflow/utility/testing.py
- tests/test_ilastik/test_applets/edgeTraining/testEdgeTrainingSerializer.py
- tests/test_lazyflow/test_operators/testMultiOutputMockOperator.py
Summary:
* use correct data to compute features on when _not_ training a random forest. Due to a faulty connection it would always use the probability map from the last lane.
* fixed some more level0 slot to level1 slot connection by adding appropriate broadcasting slots to wrappers.
* added a utility method `build_multi_output_mock_op` to produce a "mock" predecessor for top level operators, such that all their inputs can be made ready
* added test for `EdgeTrainingSerializer`
* added a "migration" procedure for "old" multilane projects that use the predictions directly as weights in the multicut
Comments very welcome, @emilmelnikov @Tomaz-Vieira
> Multicut fixes

- ilastik/applets/edgeTraining/edgeTrainingGui.py
Before one could end up with a lane with disabled button status if no annotations
were made in that lane...
I went via a signal because I couldn't find a better way. The problem is that EdgeLabelsDict is a multislot. So changes will only trigger updates for the particular lane-gui. Alternatively, one could make it a 0-level slot with a dictionary with lane keys... but that would also come with all kinds of synchronization issues in case of deleted lanes and so on...
Also makes sure to disable the live update mode when annotations are deleted.
> sync live update btn status across lanes via signal

- ilastik/applets/dataSelection/dataSelectionGui.py
in the past it was possible to drag n drop files into all roles.
Reason for loss of this functionality was that the startingLaneNum would not be
would not be incremented.
Now we increment this with each file path.
fixes: https://github.com/ilastik/ilastik/issues/2472
> fix dnd behavior on secondary roles

- .circleci/config.yml
- appveyor.yml
removed default channels from test environment. This resets build cache on circleci.
> [mnt, ci] remove defaults channel from envs

- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/utility/exportFile.py
- lazyflow/roi.py
- lazyflow/rtype.py
collections.Iterable -> collections.abc.Iterable (since Python 3.3, deprecated in 3.9)
> removed deprecated Iterable from collections

- lazyflow/operators/opDetectMissingData.py
- tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
- tests/test_lazyflow/test_operators/testOpInterpMissingData.py
we're checking there against sklearn 0.11, which is not even available on
conda-forge anymore (oldest version at time of writing 0.17).
Furthermore this check doesn't work for versions 1.* :)
> removed check for sklearn version in OpInterpMissingData

- lazyflow/metaDict.py
- lazyflow/operators/ioOperators/opInputDataReader.py
- lazyflow/operators/opSimpleBlockedArrayCache.py
- lazyflow/operators/opSlicedBlockedArrayCache.py
- lazyflow/operators/opSplitRequestsBlockwise.py
- lazyflow/utility/helpers.py
- tests/test_lazyflow/test_operators/testCacheMemoryManager.py
numpy deprecated checking `numpy.issubdtype(whatever, numpy.dtype)` with `numpy.dtype` as second argument (which was coerced to `numpy.generic` in the past). The warning for this was there for quite some time. I took the opportunity and removed some code duplication in the process of fixing this.
Also fixed a typo that has been there from 2014 that prevented the metadata for ram_usage_per_requested_pixel to be set. To be fair, this wasn't an issue up until the numpy deprecation as most operators had some sort of safeguard around this.
> Fix ram estimation, prepare numpy upgrade

- .circleci/config.yml
- ilastik/ilastik_logging/default_config.py
logging is configure whenever the main ilastik main function is executed
(`ilastik.app.main`). In tests this happens multiple times.
This change prevents multiple initialization of logging. For me this
reduced the log size per test run from 2.7MB to 270kB
> configure logging only once

- ilastik/applets/batchProcessing/batchProcessingGui.py
- tests/test_ilastik/test_applets/batchProcessing/test_batchProcessingGui.py
treat drag and dropped paths as local files.
fixes #2523
> Fix drag n drop in batchprocessing on windows

- .circleci/config.yml
- CONTRIBUTING.md
- appveyor.yml
- scripts/devenv.py
This updates the contributing instructions with use of mamba instead of conda for envrionment creation. Also update `devenv.py` accordingly.
> Use mamba to spin up development environments

- .github/workflows/core-conda-bld.yml
- conda-recipe/meta.yaml
- tests/test_ilastik/widgets/test_ImageFileDialog.py
Summary:
* added multi-output (meta) recipe, which ensures core and "release" packages are in sync
* added build/test to gh-actions
* legacy-gui-tests currently not run there (would hang, need to investigate, will open issue after merge)
* windows-gpu variant not tested - didn't manage to find a working combination of packages yet (issue after merge)
* in order to speedup tests, avoid unnecessary builds, conda build is done in two stages, ones to only build noarch recipe on linux, and then runs the tests in a second stage on all osses.
> Add release recipe

- ilastik_scripts/ilastik_startup.py
package structure has changed - `ilastik-meta` folder is not in `ilastik_root` anymore. Use `python.exe`, which is in `ilastik_root`, as an anchor.
This command line flag is not documented and will not show up with `ilastik --help`. It is only called in the context of `ilastik.exe`.
> fix path setup for windows binary

- .circleci/config.yml
- .gitignore
- CONTRIBUTING.md
- appveyor.yml
- ilastik/__init__.py
- ilastik/applets/pixelClassification/pixelClassificationSerializer.py
previously build str was not included, so version would currently be `1.4.0` as opposed to `1.4.0b27`.
Also added setuptools_scm to dev dependencies and made sure there is a proper version set in dev mode, too.
> fix version str

- ilastik/applets/edgeTraining/edgeTrainingSerializer.py
- ilastik/applets/edgeTraining/opEdgeTraining.py
- ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
makes sure the classifier is properly deserialized last, so that it is not set dirty by accident (and then retrained)...
update: I looked into why the labels are removed at the end of headless batch processing (and also when closing the project) and it happens during cleanup, - in principle we don't care about the removal there, so it's now skipped during cleanup.
partly addresses #2561
this PR doesn't improve command line handling or error messages, that are also part of #2561
> Fix project deserialization in multicut

- conda-recipe/meta.yaml
- dev/environment-dev.yml
`tifffile` versions `2022.x` on CF currently don't reflect this constraint
> fix tifffile incompatibility with py37

- .circleci/config.yml
- appveyor.yml
Currently the latest conda and mamba are not compatible anymore. Updating conda first, will not allow for mamba installation (I think they retroactively patched all packages to pin conda to `<4.13`. In any case, conda will not downgrade itself during the process and will produce the usual soup of incompatibility hints.
Here, we'll install mamba first, and let mamba do all solving (for updating conda, and other packages in the base env).
gitlab actions are fine, as they're using mambaforge.
xref: https://github.com/mamba-org/mamba/issues/1724
> Fix ci: mamba/conda incompatibility

- ilastik/applets/neuralNetwork/nnClassGui.py
- ilastik/applets/neuralNetwork/opNNclass.py
- ilastik/workflows/neuralNetwork/_nnWorkflowBase.py
tiny PR that adds the possibility to load an _optional_ "overlay" image into the NN workflows. This can be useful, when a networks expects some other input than the raw data, but it's still interesting to see the result on top of the raw data. I think @akreshuk requested it :)
> Added overlay layer for NN workflow

- ilastik/applets/edgeTraining/opEdgeTraining.py
Symptom: multicut could be update with different thresholds when training a classifier just fine. Going directly from boundary evidence, however, would not result in updated multicut segmentations.
I traced this back to the classifier. The classifier will be set dirty by the change of edgeFeatures (triggered by the `TrainRandomForest` slot. While it's true that, changing the features should invalidate the classifier.
I see four possible ways to mitigate it:
1. separate paths for weights from RF predictions or from boundary evidence directly (#2595)
1. Disconnect the slot when classifier is not trained - the op becomes not ready and will not signal dirtiness. This would require quite some rework - but would probably be the cleanest solution.
2. Add the `TrainRandomForest` slot to …
> fix multicut not updating from boundary evidence

- ilastik/applets/edgeTraining/edgeTrainingGui.py
- ilastik/applets/multicut/multicutGui.py
as discussed previously, we want to declutter the UI a bit by removing non-essential layers. Following layers will now only be available in debug mode:
* Naive Segmentation
* Voxel Data
* Multicut Disagreements
> multicut: show non-essential layers only in debug mode

- ilastik/shell/gui/ilastikShell.py
otherwise save_as action results in segfault :/
related to #2428
> enforce updateShellProjectDisplay runs in main thread

- .pre-commit-config.yaml
https://github.com/psf/black/issues/2964
Hi,
I'm working with @k-dominik on the #2590 issue and we realized pre-commit was crashing on my machine unless I fixed the click version.
This PR modifies the .pre-commit-config.yaml file to fix _click_ at version 8.0.4 that solves the pre-commit problem.
> Added pin for click in black pre-commit hook

- notebooks/Readme.md
- notebooks/pixel_classification_api/environment.yml
- notebooks/pixel_classification_api/pixel-classification-api.ipynb
* adapted the Pixel Classification API example to use the `ilastik-core` package. Also using `imageio` instead of `skimage.io` now.
* updated installation instructions to use mamba
> update pixel classification example to use ilastik-core

- conda-recipe/meta.yaml
- lazyflow/operators/ioOperators/opExportSlot.py
- lazyflow/operators/ioOperators/opInputDataReader.py
absolutely not sure why this bubbles up now, but when creating dev environments on mac and windows, calling the ilastik startup script will result in`ModuleNotFoundError`, with `libdvid` as root cause.
On linux `ImportError` is raised (and ignored, as expected) with `OpDvidVolume` as root cause.
for reference, the error on osx (also tested it on a _fresh_ windows machine):
<details>
```pytb
File "/Users/kutra/sources/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 100, in launchShell
from ilastik.shell.gui.ilastikShell import IlastikShell
File "/Users/kutra/sources/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 97, in <module>
import ilastik.workflows
File "/Users/kutra/sources/ilastik-meta/ilastik/ilastik/workflows/__init__.py", line 31, in <module>
from …
```
> fix ilastik startup on mac/windows

- ilastik/applets/edgeTraining/edgeTrainingGui.py
- ilastik/applets/edgeTraining/opEdgeTraining.py
- ilastik/applets/edgeTraining/simpleEdgeFeatSelection.py
- ilastik/applets/edgeTrainingWithMulticut/opEdgeTrainingWithMulticut.py
- ilastik/applets/wsdt/opWsdt.py
- ilastik/widgets/collapsibleWidget.py
- ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
- ilastik/workflows/multicut/multicutWorkflow.py
- tests/test_ilastik/test_applets/edgeTraining/testEdgeTrainingSerializer.py
- tests/test_ilastik/test_workflows/testEdgeTrainingWithMulticutGui.py
- tests/test_ilastik/widgets/test_collapsibleWidget.py
Using input of the very useful discussion in #2546 @akreshuk and I came up with the simple dialog for selecting features.
Available features:
* shape: translates to a subset of edgeregion(edge): radii
* Intensity: mean, Q10, Q90. For raw data always computed on all channels (per channel). Per default it is not possible to select a probability channel here, only raw data, or "boundary channel".
Screenshots:
<details>
features selected per default
default features in the advanced dialog
indication of non-default selection
</details>
Note: This will be merged if tests pass - in case of comments, pls open an issue.
> Multicut - simple Edge Feature Selection

- conda-recipe/meta.yaml
- dev/environment-dev.yml
will solve a lot of numpy warnings
> update to vigra build with latest patches

- ilastik/applets/counting/countingOperators.py
- ilastik/applets/counting/opCounting.py
- ilastik/applets/dataSelection/opDataSelection.py
- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/applets/thresholdTwoLevels/_OpObjectsSegment.py
- ilastik/utility/exportFile.py
- ilastik/workflows/voxelSegmentation/opSlic.py
- lazyflow/classifiers/vigraRfAdaptiveMaskPixelwiseClassifier.py
- lazyflow/operators/generic.py
- lazyflow/operators/ioOperators/UfmfParser.py
- lazyflow/operators/opCompressedCache.py
- lazyflow/operators/opLabelVolume.py
- lazyflow/operators/opLazyConnectedComponents.py
- lazyflow/utility/chunkHelpers.py
- lazyflow/utility/helpers.py
- tests/test_ilastik/bin/generate_test_data.py
- tests/test_ilastik/test_applets/base/testSerializer.py
- tests/test_ilastik/test_applets/batchProcessing/test_batchProcessingGui.py
- tests/test_ilastik/test_applets/blockwiseObjectClassification/testOpBlockwiseObjectClassification.py
- tests/test_ilastik/test_applets/objectClassification/testConvexHull.py
- tests/test_ilastik/test_applets/objectClassification/testOperators.py
- tests/test_ilastik/test_applets/objectCounting/testObjectCountingOperators.py
- tests/test_ilastik/test_applets/thresholdTwoLevels/testThresholdTwoLevels.py
- tests/test_ilastik/test_shell/test_license_dialog.py
- tests/test_ilastik/widgets/test_appletDrawerToolBox.py
- tests/test_ilastik/widgets/test_featureTableWidget.py
- tests/test_lazyflow/test_operators/testOpLabelVolume.py
- tests/test_lazyflow/test_operators/testValueProviders.py
this fixes various warnings so for the tests this reduces the number of warnings from 20k+ to ~1.5k
notes:
* changed `np.int` to `np.int64` anywhere, althought this might result in different behavior on windows (but maybe in intended behavior as all devs are on either linux or osx, where `np.int` would get 8bytes..
* `np.bool` to `bool` doesn't change anything
| PR | `n_warnings` |
| --:| ---:|
| #2611 | 27863 |
| #2612 | 27856 |
| #2613 | 1301 |
<sub>numbers taken from circleci runs</sub>
ref: [numpy 1.20 deprecations](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)
> Fix warnings

- ilastik/applets/base/appletSerializer.py
- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/applets/trackingFeatureExtraction/trackingFeatures.py
- lazyflow/operators/oldVigraOperators.py
- lazyflow/operators/opVigraWatershed.py
- tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationSerializer.py
- tests/test_lazyflow/test_operators/testOpBlockedArrayCache.py
- tests/test_lazyflow/test_operators/testOpCompressedUserLabelArray.py
- tests/test_lazyflow/test_operators/testOpDenseLabelArray.py
- tests/test_lazyflow/test_operators/testOpSlicedBlockedArrayCache.py
further reduce number of warnings - and be compatible with numpy 1.23 and up
`n_warnings` 1301 -> 1163
> maintenance: Fix numpy tuple warnings

- ilastik/applets/objectClassification/objectClassificationDataExportGui.py
- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
enables the export of the simple segmentation from the Pixel Classification stage
per user request... I'm not a fan of this since we [want to remove this workflow](#2621), but also because Simple Segmentation is often only used because it's more convenient to work with than a multi-channel probability image. But we allow export from pixel classification so I think it's fair to expect that it can be exported from the combined workflow as well.
> add simple segmentation output to Pixel+Object Class workflow

- ilastik/applets/neuralNetwork/modelStateControl.py
- ilastik/applets/neuralNetwork/nnClassGui.py
previously it was possible to edit content, delete everything - but it wouldn't behave properly - keeping the old model source.
Now even on error you have to clear the model (this gives you a chance of noting what model causes the problem and also the cause via the error message).
fixes #2624
> make model text edit non-editable on error

- tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
- tests/test_ilastik/test_applets/featureSelection/testNewFeatureSelection.py
- tests/test_ilastik/test_shell/test_license_dialog.py
- tests/test_ilastik/test_workflows/axesOrderPreservation/testAxesOrderPreservation.py
this was another source of warnings (and was keeping us from updating pytest).
I'm fine with most of it, except for the last commit (`testOpDataSelection.py`)- this test was a bit awkward to rewrite. Maybe @emilmelnikov has an elegant idea how to make this nicer - on the other hand - it's just a test.
Note: total number of tests run goes from 1150 -> 1125 because of `tests/test_ilastik/test_applets/featureSelection/testNewFeatureSelection.py`. There the yield tests have been changed to direct calls and, hence, don't show up individually anymore.
> Pytest generator test deprecation

- .github/workflows/static-code-analysis.yml
- ilastik/applets/base/applet.py
- ilastik/applets/featureSelection/__init__.py
- ilastik/applets/featureSelection/opFeatureSelection.py
- ilastik/applets/pixelClassification/pixelClassificationGui.py
- ilastik/applets/pixelClassification/suggestFeaturesDialog.py
- ilastik/workflows/newAutocontext/newAutocontextWorkflow.py
- ilastik/workflows/voxelSegmentation/voxelSegmentationGui.py
- lazyflow/operators/oldVigraOperators.py
- tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationGui.py
Enable _SuggestFeatures_ Dialog to deal with "narrow" stacks. Previously it would error out and might even produce segfaults :o.
On the way there was
* refactoring - naming _is_ important. It is frustrating every time I am looking for this particular dialog. Now naming reflects what is shown in the UI.
* made the dialog properly modal and made it run in the same eventloop
* made its `_run_selection` method somewhat more robust to errors - at least the graph is reverted to the same state as before
* by adding some attributes to the error that is raised by the `OpFeatureSelection` when incompatible scales are used, the dialog now automatically deselects the ones that do not work (for features that only don't fit in _z_, they are now calculated in 2D).
See also #2637 
Bottom line: Ideally …
> Fix suggest features for narrow stacks

- ilastik/shell/gui/ilastik-style-osx.qss
- ilastik/shell/gui/startShellGui.py
`QSlider` on OSX is broken: updating the handle programmatically via `slider.setValue` is not reflected in the UI once the slider has been moved manually before.
Adding a stylesheet "resolves" this issue. I tried to make it as similar to the default stylesheet as possible (see screenshots below).
Side note: Also switched to using `pathlib` in favor of `os` in `startShellGui.py`.
ref: https://bugreports.qt.io/browse/QTBUG-96522
slider before: 
slider with this PR: 
fixes #2623
> add qslider stylesheet on osx

- ilastik/applets/neuralNetwork/modelStateControl.py
showing the errormessage from within the Qthread leads to segfaults - of course. Make sure to call the method from the gui thread.
> fixes a segfault if model initialization fails

- lazyflow/operators/opBlockedArrayCache.py
The operator doesn't need `setupOutputs`, inner ops are fully connected. Metadata is already set in `OpSimpleBlockedArrayCache`, nothing should be necessary in this Op.
Probably leftover code from refactoring to using `OpSimpleBlockedArrayCache`
`setupOutputs` here also had a strange behavior of conditionally setting the value of an input slot: `Blockshape`. When changing the input to this op, the Blockshape would not update 💣 
Also updated the documentation of this op and removed commented code for clarity.
> remove unnecessary setupOutputs

- conda-recipe/meta.yaml
- ilastik/applets/blockwiseObjectClassification/blockwiseObjectClassificationGui.py
- ilastik/applets/labeling/labelingGui.py
- ilastik/applets/neuralNetwork/nnClassGui.py
- ilastik/applets/objectExtraction/objectExtractionGui.py
- ilastik/applets/thresholdTwoLevels/thresholdTwoLevelsGui.py
- ilastik/applets/tracking/base/trackingBaseGui.py
- ilastik/applets/tracking/manual/manualTrackingGui.py
- ilastik/applets/wsdt/wsdtGui.py
- ilastik/workflows/carving/preprocessingViewerGui.py
- ilastik/workflows/voxelSegmentation/voxelSegmentationGui.py
homogenizes user experience by making the "i" shortcut available in
* thresholding (object classification)
* preprocessing (carving)
* watershed (multicut)
* Tracking
* Manual Tracking
* Blockwise Object Classification
* Object Extraction
needs `volumina>=1.3.8`
fixes #2628
Missing is only Carving, where the existence of the Overlay layer makes it impossible to use with the `toggleTopToBottom` method.
> add "i" shortcut some preprocessing applets

- .github/workflows/static-code-analysis.yml
darker release 1.6.0 is available that fixes incompatibility with newer black versions.
fixes #2640
> mnt: update darker version in ci

- ilastik/applets/edgeTrainingWithMulticut/edgeTrainingWithMulticutGui.py
This is a bit of a tiny optimization, but it feels like it is doubling the fps you get in multicut.
Painting overlapping paths is probably quite costly (I guess to check what parts need to be painted, basically the whole path has to be compared).
There is no visible difference doing that, just faster rendering.
> avoid showing multiple overlapping edge layers

- lazyflow/operators/filterOperators.py
- tests/test_lazyflow/test_operators/test_opBaseFilter.py
for the special case of mixtures of 2D filters on 3D presmoothed data, `OpBaseFilter` will get a 3D source array. From this array one has to access the correct z-slice. This fixes a bug for single z-slice requests which previously returned the bottom-most slice of the source array. Now the correct slice is returned.
thanks @FredHamprecht for discovering the issue!
> fixes filter offset for 2d filters on 3D presmoothed data along z-axis

- ilastik/shell/gui/ilastikShell.py
- ilastik/widgets/collapsibleWidget.py
- tests/test_ilastik/widgets/test_collapsibleWidget.py
A controversial one (must be) to end the year :)
the startup screen became quite crowded. On normal machines, users sometimes don't even see that they can load their previous projects and such.
* Grouping of workflows according to task.
* order explicitly not via the order of imports in workflows.__init__.py
* Tracking, and Other workflows collapsed per default
Preview on OSX:
> reorganize startup screen

- ilastik/applets/wsdt/opWsdt.py
- ilastik/applets/wsdt/wsdtApplet.py
- ilastik/applets/wsdt/wsdtSerializer.py
- tests/conftest.py
- tests/test_ilastik/test_applets/edgeTraining/testEdgeTrainingSerializer.py
- tests/test_ilastik/test_applets/multicutWsdt/test_Consistency.py
- tests/test_ilastik/test_applets/multicutWsdt/test_parallel_watershed.py
- tests/test_ilastik/test_applets/multicutWsdt/test_wsdtSerializer.py
- tests/test_ilastik/test_workflows/testEdgeTrainingWithMulticutGui.py
**Summary**:
This PR enables parallel waterershed in multicut following the pattern outlined in [carvingtools.py](https://github.com/ilastik/ilastik/blob/4f673a68ff5b49b52c6b911d67ceec6234260810/ilastik/workflows/carving/carvingTools.py#L108)
Note, that in future, we want to [use the same watershed methods in Carving and Multicut](https://github.com/ilastik/ilastik/issues/2081), but this will not be addressed in this PR.
Quirks to find here:
* in order to make this backwards compatible I added an additional slot - `BlockwiseWatershed` to the op. In order to not do it blockwise for legacy projects, I didn't see another way then reviving the deprecated default value for serialSlots. For now I put it into a separate class. The deprecation [needs a separate investigation](). If someone has a …
> parallel dt watershed in multicut using elf

- ilastik/workflows/carving/carvingGui.py
- ilastik/workflows/carving/carvingWorkflow.py
- ilastik/workflows/carving/opCarving.py
- ilastik/workflows/carving/opPreprocessing.py
- ilastik/workflows/carving/watershed_segmentor.py
- lazyflow/operator.py
This fixes https://github.com/ilastik/ilastik/issues/2627
For the moment it implements a workaround: When the user changes the preprocessing, the carving operator reapplies existing labels as if they were new user input.
There would be a "proper" way to do this that does not require the carving operator to write to its own input. The MST provides a ["setSeeds" function](https://github.com/ilastik/ilastiktools/blob/main/include/ilastiktools/carving.hxx#L478), but this is currently buggy (you give it foreground and background labels, but it writes all of them into the MST as background seeds). I have left it at the workaround fix until we fix this bug in ilastiktools.
> #2627 carving loses labels after repeat preprocessing

- ilastik/workflows/carving/opPreprocessing.py
- ilastik/workflows/carving/preprocessingApplet.py
- ilastik/workflows/carving/preprocessingGui.py
- ilastik/workflows/carving/preprocessingSerializer.py
Added the missing Preprocessing settings to the serializer and changed the naming as the "reset" mechanism no longer exists (removed in 2013 - see 89e5559ae8534b4b231f4385347965984be99b4b).
This is branched from https://github.com/ilastik/ilastik/pull/2658 to save myself some merge conflicts, so we should merge that first if it hasn't happened yet. The commits to be reviewed in this PR are only the last three.
> Gh2657 carving does not save all preprocessing settings to project

- ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py
Enables immediate dirty propagation once super pixel change via a `FreezeCache` cycle  for the edge-training/multicut caches.
Fixes display of outdated multicut solution after superpixels have changed.
> propagate dirtyness to layers

- ilastik/applets/neuralNetwork/bioimageiodl.py
- ilastik/applets/neuralNetwork/modelStateControl.py
- ilastik/applets/neuralNetwork/nnClassGui.py
- ilastik/applets/neuralNetwork/nnClassSerializer.py
- ilastik/applets/neuralNetwork/tiktorchController.py
- ilastik/workflows/neuralNetwork/_nnWorkflowBase.py
bioimageio.spec will try to fetch some data from github and bioimageio. This is necessary for its operation, but shouldn't be done on _every_ startup of ilastik.
This delays those imports until NN-related workflows are actually used.
[1c50af6eb7e664bf024a0c3e50f828d5d3325f09](https://github.com/ilastik/ilastik/pull/2655/commits/1c50af6eb7e664bf024a0c3e50f828d5d3325f09) is unrelated - it's a tiny change to applet readiness that I didn't want to bother anyone reviewing independently. Now Export and Batch processing are consistently enabled once a valid model is in the project.
> delay bioimageio imports

- ilastik/applets/tracking/conservation/drawer.ui
- ilastik/applets/tracking/conservation/opConservationTracking.py
because default values matter!
in most cases, the maxNearestNeighbors value should be larger than 1, to allow for greater flexibility in the tracking solution.
New default is 3 (discussed with @akreshuk)
> Better default value for maxNearestNeighbors

- ilastik/shell/gui/licenseDialog.py
- tests/test_ilastik/test_shell/test_license_dialog.py
setting env variables reliably on app startup tended to be error prone. now we copy license files statically into the ilastik root
> License data copied to ilastik root folder during release process

- ilastik/workflows/carving/carvingGui.py
- ilastik/workflows/carving/opCarving.py
- ilastik/workflows/carving/opPreprocessing.py
- ilastik/workflows/carving/preprocessingGui.py
- ilastik/workflows/carving/watershed_segmentor.py
Sorry this one became so big. The commits are probably easier to review individually than the PR as a whole.
The original aim was to delete existing saved objects when the user re-runs the preprocessing, and to warn the user before doing so (#2011).
It turned out there were some more issues around saving and loading objects, particularly with tracking whether the current state is ready to be saved as an object. This should be improved now, which should make it easier in the future if we go for keeping the labels of saved objects and only throw away their segmentation when changing preprocessing.
> Carving drop saved objects when changing preprocessing

- ilastik/workflows/carving/carvingGui.py
Fix for #2626.
This is for sorting the list of saved carved objects when the user wants to browse and maybe load. The previous implementation converts any chunks of digits within object names into int, which can break sorting when it leads to comparisons between str and int. This happens when some objects start with a digit and others start with a non-digit.
To avoid building something more sophisticated that will sort numbers numerically and non-digits alphabetically, we instead now do numerical sorting only for a trailing number if it exists, or if the entire name is a number.
> Carving: Enable saved-objects-list sorting to handle digits and letters

- ilastik/applets/base/applet.py
- ilastik/applets/batchProcessing/batchProcessingGui.py
- ilastik/applets/counting/countingBatchProcessingGui.py
- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/projectManager.py
This PR adds autosave before doing batch processing on clicking of the _Process all files_ button. Furthermore, __dirty tracking is disabled__ for the duration of the batch processing. This results in a "clean" graph after batch. Otherwise it will get inevitably dirty because lanes are added/removed...
> Autosave before batch

- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/gui/ui/ilastikShell.ui
- ilastik/widgets/filePathButton.py
Because v1.4.0 is imminent, don't change too much, just move _Open Project_ and _Open Recent Project_ buttons, make the logo smaller, and add some external links.
> Change startup screen to the 3-column layout

- ilastik/workflows/carving/carvingGui.py
- ilastik/workflows/carving/carvingSerializer.py
- ilastik/workflows/carving/opCarving.py
This allows the user to use the "clear" button to not only remove all currently drawn labels, but also to get "out" of a currently loaded object (see [previous comment](https://github.com/ilastik/ilastik/pull/2664#issuecomment-1410503826)).
I've also inlined a couple of extracted functions that were previously used by an alternative saving mechanism. There used to be "Save" and "Save As", but we got rid of the former a few years ago.
> Carving: Also clear object when clearing labels

- ilastik/workflows/carving/carvingGui.py
- ilastik/workflows/carving/opCarving.py
This closes #2656 
The watershed can't handle either fore- or background labels being missing currently. I don't see why it couldn't, but fixing that in ilastiktools is a different scale of work.
So instead we quick-fix by preventing the user from running segmentation if one of the label types is missing.
> Carving: Prevent running segmentation when fore- or background labels are missing

- ilastik/shell/gui/ilastikShell.py
- ilastik/widgets/filePathButton.py
this was necessary for correct size calculation on linux
before:
with this PR:
> Set stylesheet as early as possible

- ilastik/applets/wsdt/opWsdt.py
- tests/test_ilastik/test_applets/multicutWsdt/test_Consistency.py
since 0.46, elf watershed returns `uint64`. As we do some further processing with `vigra` we need to cast to `uint32` (`uint64` not supported by `vigra`).
xref: https://github.com/constantinpape/elf/issues/68
(also removed an unused import in the tests)
> fix elf ws now returns uint64

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/ilastik_logging/logging_config.json
looks like this package isn't needed anymore in ilastik (functionality replaced by `vigra`/`elf`).
> mnt: wsdt package not used

- lazyflow/operator.py
- lazyflow/operators/classifierOperators.py
- lazyflow/operators/generic.py
- lazyflow/operators/opCompressedUserLabelArray.py
- lazyflow/slot.py
- tests/test_lazyflow/test_graph/test_dirty_modtime.py
Dirty propagation in ilastik goes depth-first. It is possible for dirtiness to propagate to the same target via multiple upstream paths. This commit adds the concept of a "modification time" (`mod_time` in the code) to encode sources of dirtiness.
Operators will keep track of the last `mod_time` they've seen (during dirty propagation) and can ignore it, if it is already known (see `Operator.setAllDirty`).
In more complicated graphs like in autocontext, this solves heavy delays when annotating.
To illustrate the problem, consider the above DAG, a "simplified" auto-context-like setup. In normal dirty prop, when setting the input dirty, the following sequence would occur:
```
_____________________ BLOCK A ____
|                                  |
Input --> Filter1 --> Stacker1 --> Filter4 …
```
> functionality to ignore multiple dirty propagations from same source

- appveyor.yml
- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/ilastik_logging/default_config.py
- tests/conftest.py
- tests/test_ilastik/test_workflows/test_DatasetInfo.py
- tests/test_ilastik/test_workflows/test_HeadlessPixelClassificationWorkflow.py
- tests/test_ilastik/widgets/test_datasetInfoEditorWidget.py
Final blocking thing preventing us from updating Python was pytest. This updates pytest from `3.x` pin to 7.2.0 (latest, not pinned)
There were some small real issues
* `tmp_path` magic that would resolve symlinks vs `tempfile.mk*` not doing it.
* in one of the tests, we use [`pytester`](https://docs.pytest.org/en/6.2.x/reference.html#pytest.Pytester), which is supposed to run tests in a more isolated manner (guess that was the motivation for using it, from the docs I take it is used to test pytest itself). Behavior of `pytester` `testdir` fixture seems to have changed - since pytest 3.x. I didn't dig into the pytest source code, but somehow invoking `run` seems to alter the environment for subsequent calls to `run` in the same test function. Splitting those functions means better …
> release pin on pytest

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/applets/neuralNetwork/modelStateControl.py
- ilastik/applets/neuralNetwork/nnClassGui.py
- ilastik/applets/neuralNetwork/opNNClassificationDataExport.py
- ilastik/applets/trainableDomainAdaptation/__init__.py
- ilastik/applets/trainableDomainAdaptation/modelStateControl.py
- ilastik/applets/trainableDomainAdaptation/opTrainableDomainAdaptation.py
- ilastik/applets/trainableDomainAdaptation/tiktorchController.py
- ilastik/applets/trainableDomainAdaptation/trainableDomainAdaptationApplet.py
- ilastik/applets/trainableDomainAdaptation/trainableDomainAdaptationGui.py
- ilastik/applets/trainableDomainAdaptation/trainableDomainAdaptationSerializer.py
- ilastik/shell/gui/ilastikShell.py
- ilastik/workflows/__init__.py
- ilastik/workflows/neuralNetwork/_nnWorkflowBase.py
- ilastik/workflows/trainableDomainAdaptation/__init__.py
- ilastik/workflows/trainableDomainAdaptation/_localTrainableDomainAdaptationWorkflow.py
- lazyflow/operators/__init__.py
- lazyflow/operators/generic.py
- tests/test_lazyflow/test_operators/testOpMultiChannelSelector.py
aka shallow2deep
Not a lot of ways to make this PR more digestible - it is a whole new workflow after all. The only _added_ applet would be `ilastik.applets.trainableDomainAdaptation`.
Lets you
1. Annotate an image, Pixel Classification style
2. Using one of the shallow2deep networks from the BioImage Model Zoo get enhanced predictions. the idea is, of course,  to do this in an interactive loop.
The implementation relies a lot on the functionality (tried and tested) of the Pixel Classification Workflow, and the Neural Network Classification Workflow.
Ref: [From Shallow to Deep: Exploiting Feature-Based Classifiers for Domain Adaptation in Semantic Segmentation](https://www.frontiersin.org/articles/10.3389/fcomp.2022.805166/full) | …
> Add Trainable Domain Adaptation workflow

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/workflows/neuralNetwork/_nnWorkflowBase.py
- ilastik/workflows/trainableDomainAdaptation/_localTrainableDomainAdaptationWorkflow.py
- ilastik_scripts/ilastik_startup.py
- lazyflow/operators/ioOperators/opBigTiffReader.py
- tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationGui.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpBigTiffReader.py
Necessary changes to distribute arm-64-based build
Summary:
* `pytiff` is not available for with compatible dependencies - so I removed it and changed to reading bigtiff with `tifffile`. Note: I'm using memmap here, and it has weird closing behavior:
> Flush the memmap instance to write the changes to the file. Currently there is no API to close the underlying mmap. It is tricky to ensure the resource is actually closed, since it may be shared between different memmap instances.
Alternatively to using `del` and trusting gc, as now in the code, one could close the private `_mmap` object. See also [numpy issue #13510](https://github.com/numpy/numpy/issues/13510)
* the good old workaround for big sur is not needed on newer python versions - which also means that carving will have the 3D …
> Osx arm 64

- ilastik/workflows/neuralNetwork/_localLauncher.py
Unfortunately it can take longer than 20 seconds...
cc: @btbest
> increase timeout to launch tiktorch

- ilastik/workflows/neuralNetwork/_localLauncher.py
elf limits threads on import, which has side effects even for the tiktorch process (via env variables). This resulted in single threaded neural network prediction on CPU.
In order to get proper performance out of neural networks on CPU, we unset these variables before starting the process.
ref: https://github.com/constantinpape/elf/issues/75
> hacky fix for elf limiting threads

- tests/test_ilastik/helpers/shellGuiTestCaseBase.py
- tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationGui.py
**Summary**
* fixed test "mouse moves" by sending event to the viewport
* fixed getting pixel values from viewports by hiding the cursor.
**Details**
tests relying on getting pixel values from one of the viewports seemed to be involving mouse moves (not strokes) in order to move the cursor out of the fov. I think these might have worked by chance before. At least on osx, where `TestPixelClassificationGui.test_7_EraseCompleteLabel` stopped working.
Mouse move works if sent to the viewport imageview itself, which is fixed in https://github.com/ilastik/ilastik/pull/2736/commits/0857884d4c53e3aaf4cd30e4a0aba1e97f0f4470
I have confirmed that this issue also affects windows. There the test passes by coincidence, due to maybe some slightly different rendering of the crosshair.
In order to get …
> fix test mouse move

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/applets/neuralNetwork/opNNclass.py
- ilastik/config.py
- lazyflow/metaDict.py
- lazyflow/operators/tiktorch/classifier.py
- lazyflow/operators/tiktorch/operators.py
- tests/test_lazyflow/test_operators/test_tiktorch/test_classifier.py
In preparation for NN-like workflows to handle models with multiple in- and outputs and support tensor names/ids [which are mandatory in the spec](https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/model_spec_latest.md#bioimageio-model-resource-description-file-specification-049). These changes still work only for single in- and output models. Will make this operator properly work with multiple inputs/outputs in follow up work with an example workflow.
Summary
* `OpNNclass` tensor id aware, but expects only a single in- and output
tensor.
* `ModelSession`:
* added convenience properties for in and output names.
* getters for input and output shapes now return dicts with tensor ids
as keys.
* added a few type annotations for peace of mind.
note: this requires [tiktorch …
> make NN-related operators aware of tensor ids

- lazyflow/operators/ioOperators/opTiffReader.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpTiffReader.py
Summary:
* simplify metadata handling (tifffile got better); we relied on some internals of tifffile here. Now we trust the `.series` object to have correct metadata.
* use tifffile to read the actual files
* side effect: tiff files in weird paths (special characters) can now be read even on windows :)
fixes #2731, fixes #2729
> replace vigra for tiff reading with tifffile

- tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationGui.py
`TestPixelClassificationGui.test_01_AddRemoveData` does not seem to work anymore on any platform or CI provider.
Disabling it for now, so test suite runs everywhere.
xref: https://github.com/ilastik/ilastik/issues/2741
thx for reporting @btbest
> Disabled addRemoveData test

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/applets/wsdt/opWsdt.py
- ilastik/workflows/neuralNetwork/_localLauncher.py
- tests/conftest.py
- tests/test_ilastik/helpers/wait.py
- tests/test_ilastik/test_applets/multicutWsdt/test_parallel_watershed.py
- tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationGui.py
- tests/test_ilastik/test_workflows/testCarvingGui.py
- tests/test_ilastik/test_workflows/testEdgeTrainingWithMulticutGui.py
our hacky fix is not necessary when ensuring elf > 0.4.8
Summary:
* updated pin for `elf`
* updated dependencies for pandas2 (elf --> skan2 --> pandas2)
* removed the hacky fix from #2724
* plus only very vaguely related changes
* watershed in muticut is sensitive to small numerical inaccuracies in filters. The superpixels are not the same on OSX arm-64. In order to still test the RF training there, added a test that uses ground truth to autolabel. Related to that, we require a slightly lower accuracy (0.98 -> 0.97) to compare superpixels to ground truth.
* Moved some of the testing utility functions into a single module (`tests.test_ilastik.helpers.wait`) in order to reuse them in the multicut test. There is some overlap in the functions there, but will not solve this now.
* re-enabled …
> Undo elf fix

- ilastik/applets/dataSelection/opDataSelection.py
Inspired by https://forum.image.sc/t/error-loading-file-ilastik/81584, I was looking for error messages relating to axistags and image shape, as I recall seeing some during my own use that were quite ugly and not understandable.
I couldn't find any other ones though, so here's a suggestion for the one mentioned in the issue on the forum.
Old: 
New (with a forced error, since I have no broken example file 🙃 ):
> Data input: Phrase axistags error message more user-friendly

- ilastik/utility/exportFile.py
- tests/test_ilastik/test_utility/test_exportFile.py
fix for #2714, only uses the v1.8 H5 if necessary
> First try most compatible H5 saving, otherwise use v1.8 

- .circleci/config.yml
- appveyor.yml
- ilastik/applets/objectExtraction/opObjectExtraction.py
- lazyflow/request/request.py
- tests/test_ilastik/helpers/shellGuiTestCaseBase.py
- tests/test_ilastik/test_workflows/test_neuralNetwork/test_localHeadless.py
- tests/test_lazyflow/test_request/testRequestPool.py
Use request system to allow for parallel computation of local object features.
Will speed up computation if gil is released in features `compute_local` somewhere.
fixes part of #2744 
Todos:
for our [drosophila example](https://data.ilastik.org/drosophila.zip) I found a 2-3 times speedup in feature computation (all excl location) on my M1 without any numbers changing.
> Request object features per plugin in parallel

- ilastik/applets/layerViewer/layerViewerGui.py
- ilastik/workflow.py
This fixes as far as I can find all instances where we string-concatenate while `raise`ing. We should avoid this because:
```
> a = None
> "bla" + a
TypeError: can only concatenate str (not "NoneType") to str
```
Tiny detail but this just popped up obscuring an error for me.
> Remove string concatenation when raising

- conda-recipe/meta.yaml
- dev/environment-dev.yml
bump tiktorch in order to fix NN workflows // changed zenodo API
fixes: #2764
> bump tiktorch

- conda-recipe/meta.yaml
- dev/environment-dev.yml
those builds are not compatible with numpy 1.21
this is only apparent with _some_ models from the model zoo...
> exclude broken xarray builds

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- docs/lazyflow/operator_overview.rst
- docs/lazyflow/request.rst
- ilastik/excepthooks.py
- lazyflow/operator.py
- lazyflow/operators/valueProviders.py
- lazyflow/request/request.py
- lazyflow/slot.py
- lazyflow/utility/__init__.py
- lazyflow/utility/exception_helpers.py
- lazyflow/utility/roiRequestBatch.py
- lazyflow/utility/roiRequestBuffer.py
- tests/test_ilastik/test_workflows/carving/test_opPreprocessing.py
- tests/test_lazyflow/conftest.py
- tests/test_lazyflow/test_operators/testOpMaxChannelIndicator.py
- tests/test_lazyflow/test_operators/testOpMultiArrayStacker.py
- tests/test_lazyflow/test_operators/testOpReorderAxes.py
- tests/test_lazyflow/test_operators/testOperatorInterface.py
- tests/test_lazyflow/test_operators/testValueProviders.py
- tests/test_lazyflow/test_request/testRequest.py
- tests/test_lazyflow/test_request/testRequestPool.py
- tests/test_lazyflow/test_request/test_request.py
- tests/test_lazyflow/test_utility/testRoiRequestBatch.py
- tests/test_lazyflow/test_utility/testRoiRequestBuffer.py
- tests/test_lazyflow/test_utility/test_exception_helpers.py
I always struggled with making sense of our tracebacks.
<details><summary><code>exception-test.py</code></summary>
```Python
from lazyflow.graph import InputSlot, OutputSlot, Graph, Operator
class OpBroken(Operator):
Out = OutputSlot()
def setupOutputs(self):
self.Out.meta.shape = (1,)
self.Out.meta.dtype = object
def execute(self, *args, **kwargs):
raise Exception("OpBroken 👿")
def propagateDirty(self, *args, **kwargs):
pass
class OpPassThrough(Operator):
In = InputSlot()
Out = OutputSlot()
def setupOutputs(self):
self.Out.meta.shape = (1,)
self.Out.meta.dtype = object
def execute(self, *args, **kwargs):
self.In[:].wait()
def propagateDirty(self, *args, **kwargs):
pass
g = Graph()
b = OpBroken(graph=g)
m = OpPassThrough(graph=g)
m.name = "OpPT_1"
n = OpPassThrough(graph=g)
n.name = …
```
> lazyflow: use exception chaining in requests

- ilastik/applets/dataSelection/dataSelectionApplet.py
- ilastik/applets/dataSelection/opDataSelection.py
- lazyflow/metaDict.py
This changes the default export location to the directory containing the project file, unless otherwise specified.
As far as I can tell, this affects (i.e. changes the default to project dir instead of user home dir):
- datasets sourced over URL
- potentially some legacy projects (those that end up deserialising into the fallback path that uses `PreloadedArrayDatasetInfo`, though I didn't investigate how a project file ends up there)
For all other dataset types (e.g. directory-is-dataset like for tif series, datasets stored project-internally, and of course datasets from a single file), the behaviour should not change.
I added a couple of assert messages in metaDict.py because they tripped me up in the GUI and without any message or stack trace, it took ages to figure out where I was …
> OpDataSelection: Default file exports to project file path

- dev/environment-dev.yml
I wanted to bump vigra, too, with this PR, but currently it is not as straight forward as I was hoping: #2776
> bump numpy 1.22

- .circleci/config.yml
I'm honestly not sure if this fixes #2766, but it didn't hang in this PR ;). Also makes probably sense to go to larger resource as we are pretty much maxing out the ram usage on the medium ones.
For reference the memory graph for the large one with 8Gb of Ram (medium has 4Gb):
for the checkout part, I kept the medium resource - cause why not :)
> try larger resource class for tests on circleci

- ilastik/applets/thresholdTwoLevels/drawer.ui
See #2778 
The maximum on QSPinBox also determines its width, so increasing the max also makes the layout wider.
I arranged the Min and Max spin boxes vertically because this applet drawer is already too wide:
In terms of computation, there are no issues with allowing arbitrary values - if the user chooses nonsensical min and max (e.g. with min > max), there are simply no objects that match the filter. The user can also do this in the current version already.
Fixes #2778
> Object size filter: Increase permitted value range

- ilastik/applets/labeling/labelingGui.py
Not copying the list means that when a value is changed (in this case, by the user selecting another color in the ColorDialog), the original list in the colortables module import is modified. This persists until ilastik is restarted.
Fixes https://github.com/ilastik/ilastik/issues/2728
> Labeling GUI: Copy colortable

- ilastik/applets/dataSelection/dataSelectionSerializer.py
- ilastik/applets/dataSelection/opDataSelection.py
- ilastik/exceptions.py
- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/headless/headlessShell.py
- ilastik/shell/projectManager.py
- tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
Here's what legacy UrlDatasetInfo compatibility could look like if we want to "upgrade in memory".
When attempting to load an old HBP-style project, the user gets a warning to please make a copy: 
If the user loads, we use a reimplemented UrlDatasetInfo class that provides the additional fields to upgrade the deserialized dict to a MultiscaleUrlDatasetInfo-equivalent. If the user then saves, we store the upgraded dict claiming to be a "MultiscaleUrlDatasetInfo", which makes older ilastik versions unable to load the newly saved project file.
This is an alternative solution to https://github.com/ilastik/ilastik/pull/2795
> Reimplement urldatasetinfo as legacy

- tests/test_lazyflow/test_operators/testOpCompressedUserLabelArray.py
- tests/test_lazyflow/test_operators/testOpDenseLabelArray.py
- tests/test_lazyflow/test_operators/testOperatorInterface.py
Pytest 8 changes some deprecation warnings to become errors. This should fix them.
> Fix pytest8

- tests/test_ilastik/test_applets/dataSelection/testDataSelectionGui.py
`QApplication.processEvents` didn't actually deflake the test unfortunately. I've messed around a bit with a `QTimer` to try whether a hard wait would fix it, and what amount of time would be required.
~Sadly, this seems to work, but only with 200ms or more wait time. It's not a small amount of time to sacrifice for a single test, so I'm not sure if we want to do this or if it's better to skip this test on MacOS...~ This didn't work because QTimer.singleShot of course dispatches the timer on a separate thread, it doesn't make the test thread wait :facepalm: Would have had to use time.sleep or sth.
> Tests: Deflake scale combobox in test on MacOS

- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/datasetDetailedInfoTableModel.py
- ilastik/applets/dataSelection/datasetDetailedInfoTableView.py
- ilastik/applets/dataSelection/opDataSelection.py
- ilastik/applets/dataSelection/precomputedVolumeBrowser.py
- lazyflow/operators/ioOperators/opRESTfulPrecomputedChunkedVolumeReader.py
- lazyflow/utility/io_util/RESTfulPrecomputedChunkedVolume.py
- tests/test_ilastik/test_applets/dataSelection/testDataSelectionGui.py
- tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
The primary benefit of this is to avoid storing integers in the project file, which only make sense to a consumer of the project file if they know the context of how ilastik handles the list of scales (i.e. in reverse order).
In the context of Precomputed specifically, the key-string even contains resolution information. Also for upcoming ome-zarr support, this will allow us to be more flexible in identifying a specific dataset inside the container.
~This branch is based on [btbest:import-legacy-urldatasetinfo](https://github.com/ilastik/ilastik/pull/2795), only the last two commits are additions in this PR.~ Rebased on main since we dropped that one.
> Use key-strings to identify multiscales

- ilastik/applets/dataExport/opDataExport.py
- ilastik/config.py
most ilastik outputs compress very well - compressed hdf5 should be made the default format.
Furthermore the default format can now be customized in the config.
accompanying volumina request to change the default order: https://github.com/ilastik/volumina/pull/313
CC: @oanegros (https://github.com/ilastik/ilastik/issues/2796#issuecomment-1878606777)
> Change default export format to compressed hdf5

- ilastik/applets/dataExport/dataExportGui.py
This fixes the disabled "Export All" button by adding a listener to sync the button state to backend after the temporary lane added by batch processing is removed.
Arguably, the real fix is to remove the entire disabling/enabling logic for this button. We prevent the user from reaching the export applet if their project is in a state that cannot be exported anyway. In what state would an individual lane be unexportable?
Fixes #2811
> Data Export: Update buttons after removing lane

- .github/workflows/core-conda-bld.yml
we need larger pagefile size for the neural network tests. D: (default) has a size limit of 12GB, which led to an error.
https://github.com/al-cheb/configure-pagefile-action/issues/18 recommends setting disk root to C:
<details><summary>Warning/Error</summary>
```
test-conda-packages (windows-latest, ilastik-gpu)
Exception calling "SetPageFileSize" with "3" argument(s): "The operation completed successfully"
At D:\a\_actions\al-cheb\configure-pagefile-action\v1.4\scripts\SetPageFileSize.ps1:193 char:1
+ [Util.PageFile]::SetPageFileSize($minimumSize, $maximumSize, $diskRoo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : Win32Exception
```
</details>
> ci: circumvent disk space limitation on D:

- conda-recipe/meta.yaml
- tests/test_ilastik/widgets/test_ImageFileDialog.py
in the conda recipe we had practically overridden the paths for tests by specifying `.` as path. So in the gh actions it worked before as no source folders were present (e.g. collection errors out for me locally when the `bin` folder is checked for tests...)
Also add source folders for doctests.
> let pytest use pytest.ini to discover tests

- ilastik/utility/exportFile.py
Everytime I look at `exportFile.py` I want to rewrite it. In lieu of time, another hack...
Previously, only features computed in the 1st timeframe would get a column in the export table. One would expect that with this bug there would be none ;). Global features are always computed -> produce an (empty) table in every frame, but local ones, only if there are objects.
This is more a bandaid then a proper fix. It would probably be better to go from `selected` features (from the dialog) for 
column names, but currently the plugin information is stripped from those :(
CC: @oanegros (thank you for pointing it out and helping to debug)
> Ensure all object features get exported to table

- ilastik/applets/dataSelection/datasetDetailedInfoTableView.py
This fixes one of our most frequent flaky tests on MacOS:
```
=================================== FAILURES ===================================
___________________ TestOpDataSelection_Basic2D.testBasic2Dc ___________________
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
File "$SRC_DIR/ilastik/applets/dataSelection/datasetDetailedInfoTableView.py", line 188, in <lambda>
QTimer.singleShot(750, lambda: parent_view.setIndexWidget(index, None))
RuntimeError: wrapped C/C++ object of type DatasetDetailedInfoTableView has been deleted
```
According to the comment, the timer is there because deleting the indexWidget synchronously is impossible. It seems to work just fine for me to …
> Data selection: Remove inline Add buttons immediately

- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/precomputedVolumeBrowser.py
A couple of small improvements to the web-source selector dialog: Ensuring the URL contains "http", and a history.
`        RECENT_URLS_KEY = "Recent URLs"` <- is this an acceptable key to use for inside the preferences?
> Improve web loading gui

- ilastik/applets/layerViewer/layerViewerGui.py
- tests/test_ilastik/test_applets/layerViewer/testLayerViewerGui.py
Fixing and test-covering a couple of subtle bugs I found in the layerViewerGui while implementing OME support
> Fix layerviewer update after shape change

- ilastik/applets/dataSelection/opDataSelection.py
- ilastik/applets/dataSelection/precomputedVolumeBrowser.py
- lazyflow/operators/ioOperators/opInputDataReader.py
- lazyflow/operators/ioOperators/opRESTfulPrecomputedChunkedVolumeReader.py
- lazyflow/utility/io_util/RESTfulPrecomputedChunkedVolume.py
A couple of smaller changes from my OME branch that we can independently integrate into main:
- Better feedback for connection errors in the URL dialog
- Moving stripping the "precomputed://" prefix from URLs into the Precomputed adapter to reduce duplications of the string constant across data loading classes (and because knowing about the prefix should be none of their concern)
> Precomputed handling

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/applets/base/singleToMultiGuiAdapter.py
This is a band-aid for #2836 that at least stops downstream applets from throwing errors because they are looking for GUIs of lanes that do not exist.
The user then ends up on a Feature Selection applet with an empty viewer, which is less weird than seeing the data selection gui. In fact, this allows them to change the selected scales, so they can even fix the project without necessarily having to close it...
> Multi-GUI adapter: Stop throwing if no lanes exist

- ilastik/plugins_default/vigra_objfeats.py
clarify warning issued for objects that have the same value for all pixels (ref: [image.sc topic](https://forum.image.sc/t/encountered-bad-objects-features-while-training/95038?u=k-dominik))
- n/a Add docstrings and comments.
- n/a Add tests.
- n/a Reference relevant issues and other pull requests.
> Add note on 'bad features' warning for skewness and kurtosis

- ilastik/applets/counting/countingGui.py
- ilastik/applets/counting/countingGuiBoxesInterface.py
- ilastik/shell/gui/ilastikShell.py
- ilastik/widgets/featureTableWidget.py
- ilastik/widgets/preView.py
- lazyflow/operator.py
- lazyflow/operators/cacheMemoryManager.py
One of our test configurations picked up Python 3.10 (which is fine for the "lirbary" usage). This resulted in some minor errors:
1. Threadings `condition.notifyAll` has been marked for deprecation in favor of `condition.notify_all`. In `TestCompatibilityChecks.test_access_opaque_slot_value_should_not_warn_or_raise` we check that no warning is raised. This was of course broken by the deprecation. Rather than adapting the test I preferred keeping up with Python
2. Python stopped implicitly converting types in function calls -> results in errors/segfaults in pyqt. Explicitly converted types or made sure e.g. integer value division is used (e.g. in draw methods of `featureTableWidget`).
fixes #2852
> Python 3.10 compatiblity fixes

- ilastik/applets/dataSelection/precomputedVolumeBrowser.py
Just a tiny improvement to the dialog for choosing a URL. Currently, the user first has to "Check URL", and if the URL gives a successful response, the Ok button is activated. If the user then changes the URL, the button remains activated and the user can add any arbitrary string to the project (which will attempt to fetch from there and fail).
> Web-loading GUI: Update OK button

- ilastik/applets/layerViewer/layerViewerGui.py
- ilastik/workflows/carving/carvingGui.py
Issue: when switching to dataexport one sometimes raises an exception like (against current `volumina` main):
<details><summary>Exception</summary>
```pytb
ERROR 2024-05-07 16:55:14,802 excepthooks 93120 6118469632 Unhandled exception in thread: 'Worker #0'
ERROR 2024-05-07 16:55:14,803 excepthooks 93120 6118469632 Traceback (most recent call last):
File ".../ilastik/lazyflow/request/request.py", line 383, in _execute
self._result = self.fn()
File ".../ilastik/lazyflow/slot.py", line 868, in __call__
result_op = self.operator.call_execute(self.slot.top_level_slot, self.slot.subindex, self.roi, destination)
File ".../ilastik/lazyflow/operator.py", line 592, in call_execute
return self.execute(slot, subindex, roi, result, **kwargs)
File ".../ilastik/lazyflow/operators/opReorderAxes.py", …
```
> Delay setupLayers to LayerGui being shown

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/applets/base/appletSerializer/legacyClassifiers.py
- ilastik/experimental/api/_pipelines.py
- ilastik/experimental/parser/_h5helpers.py
- ilastik/experimental/parser/_projects.py
- ilastik/experimental/parser/types.py
- lazyflow/classifiers/lazyflowClassifier.py
- tests/test_ilastik/test_experimental/test_api/test_pipelines.py
- tests/test_ilastik/test_experimental/test_parser/test_projects.py
Summary:
* public api unchanged
* internal representations of "applets" based on pydantic models - currently limited to the data that is needed for processing (will add more along with the tool for data relocation)
* added `_h5helpers` module in `ilastik.experimental`, which could also live in `ilastik.applet.base.appletSerializer.serializerUtils`, but it's not needed there
* some internals have changed -> tests needed to be adapted
- not needed, with pydantic classes mostly documents themselves ;D Add docstrings and comments.
- n/a (api unchanged) Update [user documentation](https://github.com/ilastik/ilastik.github.io).
- n/a Reference relevant issues and other pull requests.
> Use pydantic for .ilp deserialization in experimental/api

- ilastik/ilastik_logging/default_config.py
- ilastik/ilastik_logging/logging_config.json
- ilastik/workflows/voxelSegmentation/classifierOperators.py
- lazyflow/graph.py
- lazyflow/operator.py
- lazyflow/operatorWrapper.py
- lazyflow/operators/classifierOperators.py
- lazyflow/slot.py
- lazyflow/utility/orderedSignal.py
Now that debug logging actually works, this introduces a bunch of new debug statements that allow tracing what lazyflow is doing. Also:
- Fix default naming of operators. This was only happening in `_after_init`, which is too late. We want the default name to already be set at the start of `__init__` so that slots instantiated during `__init__` can put it in their logger name.
- Add utf-8 encoding to log config to override cp1252 on windows and make it possible to log slot.meta (which can contain σ,  throws in cp1252)
At this point, the changes I make when I need to debug lazyflow are:
1. Start ilastik with `--debug`
2. Set `write_logs=True` in `Slot.__init__` instead of False to set up slot-wise logging
3. Change `INFO` to `DEBUG` in logging_config.json for lazyflow.signals, …
> Lazyflow logging and fix default operator naming

- ilastik/shell/gui/startShellGui.py
This will set WM_CLASS on X11 (hopefully wayland, too). abcdesktop had problems without it being set (clicking the task bar icon would resulted in new instances of ilastik spinning up instead of showing the current one).
fixes #2872
> Start QApplication with non-empty argv

- .circleci/config.yml
Apparently the previous "fix" was coincidence. Root cause is using `conda run` to run pytest. This hides the output per default until the process completes. Adding `--live-stream` to `conda run` will print things immediately. That way the test run can also run more than 10 minutes 🥇 .
In the process I separated the steps a bit more, such that coverage upload happens separately.
> Fix circleCI pt2: try to get pytest output immediately

- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/objectExtraction/objectExtractionGui.py
- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/applets/tracking/base/pluginExportOptionsDlg.py
- ilastik/applets/tracking/base/trackingBaseDataExportApplet.py
- ilastik/applets/tracking/base/trackingBaseDataExportGui.py
- ilastik/applets/tracking/conservation/conservationTrackingGui.py
- ilastik/applets/tracking/conservation/opConservationTracking.py
- ilastik/plugins/__init__.py
- ilastik/plugins/manager.py
- ilastik/plugins/types.py
- ilastik/utility/exportFile.py
- ilastik/workflows/counting/__init__.py
- ilastik/workflows/objectClassification/__init__.py
- ilastik/workflows/tracking/conservation/conservationTrackingWorkflow.py
- ilastik/workflows/tracking/structured/structuredTrackingWorkflow.py
- tests/test_ilastik/test_applets/objectExtraction/testOperators.py
ilastik object features can be added via a (`yapsy`-based) plugin system. The usual way would be to put them into the user plugins folder. However, some plugins will have requirements wrt dependencies. In order to better track those, they should be added as conda package, configured with the appropriate dependencies. This will enable us to include them in the distribution, along with all necessary dependencies.
- n/a Update [user documentation](https://github.com/ilastik/ilastik.github.io).
CC: @oanegros
> Oc plugins via entrypoints

- conda-recipe/meta.yaml
- ilastik/applets/dataSelection/multiscaleDatasetBrowser.py
- ilastik_scripts/ilastik_startup.py
- lazyflow/operators/opLabelVolume.py
- lazyflow/utility/io_util/OMEZarrStore.py
- lazyflow/utility/pipeline.py
- tests/test_startup.py
This PR originally was about fixing a SyntaxWarning message (see below), which I was going to just leave here until b18. Then discovered that `zarr.storage.FSStore` can't connect to remote servers in b17 on Linux and Mac due to issues with the SSL cert path, so b17 is unreleasable. Pushing the fix for that here instead and we'll just take the SyntaxWarning fixes along.
Original description: 
This is not a great UX... (not to mention one of these was clearly a typo)
> Fixes for 1.4.1b17 release

- ilastik/applets/objectExtraction/featureSelectionWithHelp.ui
- ilastik/applets/objectExtraction/objectExtractionGui.py
with the inclusion of the sphericaltexture plugin, the "All excl. location" button behavior changed - it would also include
those new features. Here we change the behavior of the button to include only the default features, as they were present in previous versions.
Timing-wise the sphericaltexture features are about a factor of 10x
slower to compute than our other features - so these should be selected
only if useful for the task (tbd by users).
> Object classification: Restore default feature selection from previous verisons

- tests/test_lazyflow/test_request/testRequestLock.py
does removing the timeout actually fix it?
edit: It doesn't, guess we'll have to skip the test for now
> Skip requestLock test on CircleCI

- ilastik/app.py
- ilastik/ilastik_logging/__init__.py
- ilastik/ilastik_logging/default_config.py
- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/gui/reportIssueDialog.py
- tests/test_ilastik/test_logging/test_default_config.py
- tests/test_ilastik/test_shell/test_report_issue_dialog.py
This adds a "Report issue by email" menu action to the Help menu. It's intended to give us something shorter to tell people on the forum than the old "Please find the log with `Settings > Open Log folder`, delete it, reproduce the error, and then email us the log or upload it here on your forum post".
Now we would have to tell them, "Please go to `Help > Report issue by email` and attach the log as described there."
What the button actually does, is open the default email client with a blueprint email that includes version, OS, active workflow and applet, as well as open the log folder. The hope being that this makes it easier for the user to provide the basic info we need. (The reason it opens the log folder instead of pre-attaching the log file, is because that's not supported in …
> Easier problem reporting

- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/projectManager.py
- ilastik/workflow.py
Closes #2721
I did some refactoring as well, as I was navigating through the code.
I could potentially add a little bit more logic to make the cursor busy only for the neural network workflows, where the tiktorch server is needed, but I skipped it, since it is a very lightweight process, and it won't cause harm even for the simpler, faster workflows that don't introduce latency (shoud maybe do it though?).
Manually tested by introducing latency at the creation of the project manager with `time.sleep()`:
```python
import time
time.sleep(2)
self.projectManager = ProjectManager(self, workflow_class, self._workflow_cmdline_args, project_creation_args)
```
> Add wait cursor when tiktorch server is started

- ilastik/applets/pixelClassification/opPixelClassification.py
- ilastik/applets/pixelClassification/pixelClassificationGui.py
- ilastik/workflows/newAutocontext/newAutocontextWorkflow.py
Forgotten to push this...
This connects the raw data to the "overlay" layer in 2nd round of autocontext. This enables seeing the raw-data as is (all channels), as opposed to the raw data (that has preds stacked on top) and thus might not be interpreted correctly anymore.
Especially useful when viewing rgb like data.
fixes #2567 #2174  #1410
> Autocontext: Connect raw data directly in 2nd (or later) rounds

- ilastik/applets/dataSelection/dataLaneSummaryTableModel.py
- ilastik/applets/dataSelection/datasetDetailedInfoTableModel.py
- ilastik/applets/dataSelection/datasetDetailedInfoTableView.py
- ilastik/applets/labeling/labelingGui.py
- ilastik/shell/gui/aboutDialog.py
- ilastik/utility/gui/__init__.py
- ilastik/widgets/featureTableWidget.py
- ilastik/widgets/labelListView.py
- ilastik/widgets/listView.py
Wow, how much time can one spend on choosing colors for a button...
Motivation (gallery of horror): I personally don't use dark mode, but almost every user I support (on osx) does. And it was really ugly:
<details><summary>About dialog</summary>
</details>
<details><summary>Feature Selection</summary>
</details>
<details><summary>Pixel Classification Training</summary>
</details>
Dealing with dark mode in qt5 seems also to be challenging to do properly (see [here](https://stackoverflow.com/questions/75457687/detect-dark-application-style)). This PR adds some band aids to at least make ilastik usable in  dark mode:
<details><summary>About dialog</summary>
</details>
<details><summary>Feature Selection</summary>
</details>
<details><summary>Pixel Classification Training</summary>
</details> …
> Fix dark mode (for mac)

- .github/workflows/core-conda-bld.yml
- .github/workflows/deploy.yml
- CONTRIBUTING.md
- Readme.md
- appveyor.yml
- conda-recipe/meta.yaml
- dev/environment-dev.yml
- notebooks/Readme.md
mamba is officially deprecated since July, and now it throws ugly warnings when you use it.
More places where this should be replaced, and contributing.md to be updated, but already pushing to test CI
> Stop using mamba

- ilastik/workflows/carving/preprocessingDrawer.ui
Super tiny typo fix in carve/preprocessing reduce-to tooltip
n/a :)
> Fix typo in carve/preprocessing

- tests/conftest.py
- tests/test_ilastik/test_workflows/testObjectClassificationGui.py
this test was flaky due to so many features in training - fixing the seed should fix this.
Edit: triggered the test runs 3 times and _that particular_ test didn't fail.
> Fix flaky ObjectClassificationGui test

- .github/workflows/core-conda-bld.yml
- lazyflow/__init__.py
this causes problems for consumers of the API, see #2913. Note, the ilastik application installs the faulthandler anyways, so for ilastik there is no change in behavior.
fixes #2913
> remove faulthandler activation on lazyflow import

- ilastik/applets/dataSelection/datasetDetailedInfoTableModel.py
- ilastik/applets/dataSelection/opDataSelection.py
- lazyflow/operators/ioOperators/opExportSlot.py
- lazyflow/operators/ioOperators/opOMEZarrMultiscaleReader.py
- lazyflow/operators/ioOperators/opRESTfulPrecomputedChunkedVolumeReader.py
- lazyflow/operators/ioOperators/opStreamingH5N5Reader.py
- lazyflow/slot.py
- lazyflow/utility/io_util/OMEZarrStore.py
- lazyflow/utility/io_util/RESTfulPrecomputedChunkedVolume.py
- lazyflow/utility/io_util/multiscaleStore.py
- lazyflow/utility/io_util/write_ome_zarr.py
- tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
- tests/test_ilastik/test_workflows/testEdgeTrainingWithMulticutGui.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpExportSlot.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpStreamingH5N5Reader.py
- tests/test_lazyflow/test_utility/test_io_util/test_write_ome_zarr.py
Support exporting to OME-Zarr
This PR on its own only enables writing to OME-Zarr through headless, since the export GUI is in volumina (https://github.com/ilastik/volumina/pull/316)
* Local file system only, writing to web stores tbd
* Output image is single-scale. Scaling turns out to be quite complex to do properly and blockwise / RAM-friendly / web-friendly, so leaving it for another PR. Hopefully if someone wants to have their output scaled before I get it done, they can use other tools that are out there. Though I'm not sure how good the converters/scalers out there actually are at handling OME-Zarr as input. Once I do implement it, they will be able to load any single-scale exports from this version, and "convert" them to multiscale by exporting them in the to-be-added format …
> Export to OME-Zarr

- conda-recipe/meta.yaml
- dev/environment-dev.yml
Issue we first saw in https://github.com/ilastik/ilastik/pull/2904 with pytorch 2.4.1
E.g. https://github.com/ilastik/ilastik/actions/runs/11721367647/job/32654563102
```
Traceback (most recent call last):
File "C:\Users\runneradmin\miniconda3\conda-bld\ilastik-gpu_1730976400239\test_tmp\run_test.py", line 23, in <module>
import torch
File "C:\Users\runneradmin\miniconda3\conda-bld\ilastik-gpu_1730976400239\_test_env\lib\site-packages\torch\__init__.py", line 262, in <module>
_load_dll_libraries()
File "C:\Users\runneradmin\miniconda3\conda-bld\ilastik-gpu_1730976400239\_test_env\lib\site-packages\torch\__init__.py", line 245, in _load_dll_libraries
raise err
OSError: [WinError 182] The operating system cannot run %1. Error loading …
```
> Fix pytorch fbgemm.dll dependency issue

- ilastik/shell/gui/ilastikShell.py
- lazyflow/__init__.py
- lazyflow/classifiers/lazyflowClassifier.py
- lazyflow/classifiers/parallelVigraRfLazyflowClassifier.py
- lazyflow/classifiers/sklearnLazyflowClassifier.py
- lazyflow/classifiers/vigraRfLazyflowClassifier.py
- lazyflow/classifiers/vigraRfPixelwiseClassifier.py
- tests/test_ilastik/test_shell/test_status_log.py
Log messages that are emitted using the log level 23 (or `lazyflow.USER_LOGLEVEL`) will show up in the status bar. Double clicking that area will open the log history.
Currently this will show the number of labels and oob in pixel classification, object classification (and related workflows - tracking...) as well as multicut.
- [couldn't find one] Reference relevant issues and other pull requests.
> Add logging widget to status bar

- ilastik/applets/dataSelection/multiscaleDatasetBrowser.py
- ilastik/applets/dataSelection/opDataSelection.py
- lazyflow/operators/ioOperators/opInputDataReader.py
- lazyflow/operators/ioOperators/opOMEZarrMultiscaleReader.py
- lazyflow/operators/ioOperators/opRESTfulPrecomputedChunkedVolumeReader.py
- lazyflow/operators/ioOperators/opStreamingH5N5Reader.py
- lazyflow/operators/ioOperators/opStreamingH5N5SequenceReaderM.py
- lazyflow/operators/ioOperators/opStreamingH5N5SequenceReaderS.py
- lazyflow/utility/io_util/OMEZarrStore.py
- lazyflow/utility/pathHelpers.py
- tests/test_ilastik/test_workflows/test_DatasetInfo.py
- tests/test_ilastik/test_workflows/test_HeadlessPixelClassificationWorkflow.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpExportSlot.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpInputDataReader.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpStreamingH5N5Reader.py
- tests/test_lazyflow/test_utility/test_io_util/test_OMEZarrStore.py
This revamps URI handling in the OME-Zarr loader. With this, we should be able to handle any URI that points to any sub-path within an OME-Zarr store, as long as some parent contains a `zattrs` that conforms to either the `plate`, `well`, `labels` or `multiscales` spec of the OME-Zarr standard
_AND_... as long as the URI contains ".zarr" somewhere. This still eliminates stores that don't follow the naming convention (looking at you, [webknossos](https://zarr.webknossos.org/)), and I want to change this requirement. But I think this will have to be kept for another PR, as it'll take some playing around to see what's the nicest way of doing it.
But, if the address is within an OME-Zarr store, the loader now introspects the given path and its parents until it hits the first conforming spec, …
> Support selecting/loading arbitrary URIs within an OME-Zarr store

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/applets/edgeTraining/opEdgeTraining.py
- tests/test_ilastik/test_applets/edgeTraining/testOpEdgeTraining.py
Fixes training for multiple images in multicut. `pandas` deprecated `DataFrame.append` as of 1.4.0, and removed it in `pandas` 2. Also added an explicit version 2 pin for pandas for dev envs and conda recipes.
fixes #2933
> Multicut: Fix deprecated append on pd.DataFrame

- .github/workflows/core-conda-bld.yml
`.conda` is the default package format since conda build `25.1.0`
> Switch to .conda package format (with latest conda build)

- tests/test_lazyflow/conftest.py
On CI caches could be cleaned in certain situations during tests that would require reproducible cache behavior.
With these two fixtures, all tests in lazyflow will get a fresh cache that is cleaned only after every test.
fixes https://github.com/ilastik/ilastik/issues/2540
other examples:
* `test_lazyflow.test_operators.testOpBlockedArrayCache.TestOpBlockedArrayCache_masked.testFixAtCurrent`
<details><summary>tb</summary>
```pytb
AssertionError: 33 <= 2
assert 33 <= 2
+  where 33 = <lazyflow.utility.testing.OpArrayPiperWithAccessCount object at 0x719548650850>.accessCount
self = <tests.test_lazyflow.test_operators.testOpSlicedBlockedArrayCache.TestOpSlicedBlockedArrayCache object at 0x719578db8610>
def testFixAtCurrent(self):
opCache = self.opCache
opProvider = self.opProvider …
```
> Tests: disable automatic cache cleanup for lazyflow tests.

- lazyflow/utility/io_util/OMEZarrStore.py
Supporting OME-Zarr v0.5 will require zarr v3, which we currently can't have in our env because python-elf restricts zarr<3.
But we can show a nicer error message than `400 Bad Request` (which is what happens e.g. on `https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.5/idr0066/ExpD_chicken_embryo_MIP.ome.zarr` due to the "try parent folders" mechanism - https://uk1s3.embassy.ebi.ac.uk/.zattrs gives 400 instead of 404)
> OME-Zarr: Report v0.5 not supported

- .github/workflows/core-conda-bld.yml
- conda-recipe/meta.yaml
- dev/environment-dev.yml
build 1038 is the latest version of vigra built against boost 1.78.0 (which is the latest boost version we have builds of our packages for, that depend on it).
Note for windows devs (@btbest): It's now necessary to include `ilastik-forge/label/patched` if you want to create a development env close to the release env (where the patched pyshtools is already used).
> bump vigra to 1.11.1 build 1038

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/ilastik_logging/default_config.py
- lazyflow/operators/ioOperators/opInputDataReader.py
- lazyflow/utility/io_util/OMEZarrStore.py
- tests/test_ilastik/test_applets/dataSelection/testOpDataSelection.py
- tests/test_ilastik/test_applets/thresholdTwoLevels/testOpGraphcutSegment.py
- tests/test_lazyflow/test_utility/test_io_util/test_OMEZarrStore.py
This enables reading OME-Zarr from URIs pointing to AWS S3 and S3-compatible objects.
You can try it live with a public bucket I set up for testing: `s3://btbest-public/img.zarr/`
While it's not super user friendly, this also at least enables users to access S3 buckets that require authentication _at all_, by setting up a credentials file in the default location (`~/.aws/credentials`). Alternatively, one can invoke ilastik with the credentials as env variables (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`).
You cannot try it with the private bucket that I also set up to try the authenticated access :) (at least not without some private communication)
Setting up your own private bucket for testing is quite a bit of work. You have to:
1. Create an AWS account (which requires payment …
> OME-Zarr: Support reading from URIs with s3: scheme

- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/objectClassification/opObjectClassification.py
- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
- tests/test_ilastik/test_applets/blockwiseObjectClassification/testOpBlockwiseObjectClassification.py
Previously, in OC, one could activate all applets while on live update. This allowed to change the graph while training and could lead to #1040.
Also fixes downstream unreadiness in case of an untrained classifier.
Fixes #1040
<details><summary>previously - live update active</summary>
</details>
<details><summary>with this PR - live update active</summary>
</details>
- []  ~~ensure errors during batch processing don't block the UI~~ --> will do this separately as it affects all workflows
> Fix state update to inactivate applets in live update

- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/gui/ui/ilastikShell.ui
- tests/test_ilastik/test_shell/test_startup_dnd.py
Going via the "open file" dialog always is a pain.
Also since I'm already touching files here: replaced twitter link with link to bluesky ❤️ 
Todos:
> Added drag-n-drop support for projects to startup page

- ilastik/applets/objectClassification/objectClassificationSerializer.py
- ilastik/applets/objectExtraction/objectExtractionSerializer.py
- ilastik/applets/objectExtraction/opObjectExtraction.py
- ilastik/excepthooks.py
- lazyflow/utility/testing.py
- tests/test_ilastik/test_applets/objectExtraction/testObjectExtractionSerializer.py
This PR adds a check to the deserialization logic of `ObjectExtractionApplet` that checks that all plugins for feature computation are available when deserializing to avoid loading projects where some features can not be computed.
fixes https://github.com/ilastik/ilastik/issues/2942
> Error on missing plugin

- ilastik/applets/objectClassification/objectClassificationGui.py
- ilastik/applets/objectClassification/opObjectClassification.py
- tests/test_ilastik/test_applets/blockwiseObjectClassification/testOpBlockwiseObjectClassification.py
- tests/test_ilastik/test_workflows/testObjectClassificationGui.py
Hook into the editors undo/redo stack to support undo/redo in Object Classification and Tracking flavors. When the input image changes, the undostack is cleared.
> OC: Add undo/redo for object level annotations

- ilastik/applets/batchProcessing/batchProcessingApplet.py
- ilastik/applets/dataExport/dataExportApplet.py
- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
- tests/test_ilastik/test_applets/batchProcessing/test_batchProcessingApplet.py
This PR ensures pre- (`prepare_for_entire_export`) and post export (`post_process_entire_export`) hooks are called, even in failure cases (those are used e.g. to open/close files with summaries (in counting)).
Also fixed call order of `prepare_for_entire_export` which was called for every lane and resulted in tables in counting being overwritten for each file.
Also fixed a few type annotations.
Fixes #2159 (coincidence ;) didn't investigate this specifically)
> Better recovery from batch processing failures

- ilastik/applets/thresholdTwoLevels/drawer.ui
- ilastik/applets/tracking/conservation/drawer.ui
- ilastik/applets/tracking/structured/drawer.ui
This commit sets the size filter initial values to the same ones than as in thresholding. Also same initial value in all tracking flavors.
Tracking reuses some elements from Object Classification. E.g. the thresholding applet. For the actual tracking there is another size-filter step, as there is one in thresholding, too. These don't necessarily need to be in sync, but it's better to start off that way.
fixes #2810
Ideally these values would come from a unique source to keep them in sync also in the future, but every time I look at tracking I think it's either complete rewrite or minimal fix...
> Quickfix: Same object size limits in tracking and oc

- lazyflow/operators/ioOperators/opInputDataReader.py
- lazyflow/utility/io_util/OMEZarrStore.py
Tiny change that should have 0 functional impact.
This is to ensure that we don't get in a situation like https://github.com/ilastik/ilastik/issues/2925 again, where the multiscale URI selector dialog checks and confirms compatibility for a dataset, and then once the user clicks "Add to project", they get an error because the backend checks the compatibility differently.
By using the same function to check compatibility (`OMEZarrStore.is_uri_compatible`), whatever passes the dialog should also pass the backend.
> OME-Zarr: Sync front- and backend check for compatibility

- ilastik/applets/dataSelection/multiscaleDatasetBrowser.py
In order promote the ome-zarr functionality a bit (and also to have super easy access to some testdata when testing on different machines) I thought it would be neat to have quick access to our trusty 2d_cells_apoptotic. I've uploaded a `.zarr` version to data.ilastik.org ...
> Add 2d_cells zarr as default in Multiscale history

- ilastik/applets/trainableDomainAdaptation/modelStateControl.py
Tiny fix for a problem that I found just now when poking the workflow a bit more...
Previously, if a model loaded from ilp was not in the list of models from the zoo, the field would say "remove model". This commit fixes it by always setting the current text.
> Fix show model name for models from ilp

- ilastik/workflows/neuralNetwork/_localLauncher.py
- tests/test_ilastik/test_workflows/test_neuralNetwork/test_localLauncher.py
currently, pytorch does not support all operators, especially in 3D on apple silicon (mps) devices. Setting the env variable "PYTORCH_ENABLE_MPS_FALLBACK". for the tiktorch server process allows running these networks on CPU instead of failing.
Looks like this will still be an issue for a while. With this env variable set, pytorch will decide to fall back to CPU if the network cannot be run on MPS devices.
> Add cpu fallback for tiktorch server on macos silicon

- ilastik/workflows/objectClassification/objectClassificationWorkflow.py
- ilastik/workflows/trainableDomainAdaptation/_localTrainableDomainAdaptationWorkflow.py
In https://github.com/ilastik/ilastik/issues/2621 we agreed to deprecate and ultimately remove this workflow due to the many issues it introduces (huge memory consumption, unreliability...).
I added "deprecated" to the workflow name, and also added a note on the data selection applet, as well as a logger warning to inform headless users, too.
I added a "welcome message" option some time in the past, but it was slashed ;) https://github.com/ilastik/ilastik/pull/2333. Could be revived for more aggressive deprecation...
Edit: somewhere the console/log warning is filtered out 🙄
> Add deprecation notice for PC+OC workflow

- lazyflow/operators/ioOperators/opExportSlot.py
Fixes #2916
This PR filters out unsupported in by updating the list comprehension.
The change ensures that these formats are not included in the file format options, which should prevent them from appearing in the drop-down list in ilastik. (I verified it by running ilastik)
> Filter out unsupported extensions

- ilastik/applets/dataSelection/dataLaneSummaryTableModel.py
- ilastik/applets/dataSelection/dataSelectionGui.py
- ilastik/applets/dataSelection/datasetDetailedInfoTableModel.py
- ilastik/applets/dataSelection/opDataSelection.py
This slot exposed the same information as the input `OpDataSelection.Dataset`, but it is only connected if there are no data constraints violated. The slot is intended to be connected to UI elements of the data selection table. Ui then can rely on this data being valid when connected.
`DatasetDetailedInfoTable` now listens to this slots, instead of `Dataset` so no update gets triggered if data is not valid. Before, invalid states could be already added to the table and had to be rectified which I think could lead to objects being destroyed prematurely. Now the "correct axistags" loop runs before any data is added to the table.
Not sure if I want to merge this before 1.4.1. On the one hand -> segfaults that we know of are avoided, on the other hand, I would test drive this setup for a few …
> Add `DatasetOut` slot to OpDataSelection, Fix segfaults

- conda-recipe/meta.yaml
- dev/environment-dev.yml
- ilastik/applets/neuralNetwork/bioimageiodl.py
- ilastik/applets/neuralNetwork/modelStateControl.py
- ilastik/utility/bioimageio_utils.py
- ilastik/workflows/neuralNetwork/_localLauncher.py
- lazyflow/operators/tiktorch/classifier.py
- tests/test_ilastik/test_workflows/test_neuralNetwork/test_localLauncher.py
- tests/test_lazyflow/test_operators/test_tiktorch/test_classifier.py
Updated tiktorch to `25.4.0` which depends on the current bioimageio versions for spec (`0.5.4.1`) and core (`0.8.0`)
Also:
* only get one set of weights.
* removed tensorflow from supported models, since it is currently not supported on our side
* Don't add model if data channels don't match model channels (#2678)
Fixes #2678
> Optimize bioimage model downloads, update tiktoch/bioimageio

- ilastik/ilastik_logging/default_config.py
If logfile path is relative (e.g. from `--logfile my-log.txt`), then `os.path.dirname(logfile_path)` returned an empty string, which broke on `os.makedirs`.
Now, logdir is wrapped in `Path` that correctly handles relative dirs.
> Fix relative logfile path handling

- ilastik/applets/pixelClassification/suggestFeaturesDialog.py
This PR fixes issue #2683, where running "Suggest Features" without adding annotations caused an exception.
So added a tooltip instructing users to add annotations before running the feature selection.
Please let me know if I can make the message more clear.
@k-dominik, please review when available!
> Fix crash in Suggest Features when no labels are present

- ilastik/shell/gui/licenseDialog.py
On mac, apps use ascii as default encoding (.app). The file 3rd party license file contains non-ascii characters -> encoding needs to be set.
> Enforce encoding when reading license file

- Readme.md
Noticed our forum counter showed an unreasonably low number, so I search for a url that would be more accurate.
left old, right new 🤷
> Update forum counter

- ilastik/applets/dataSelection/multiscaleDatasetBrowser.py
- lazyflow/utility/io_util/OMEZarrStore.py
- lazyflow/utility/io_util/RESTfulPrecomputedChunkedVolume.py
- lazyflow/utility/io_util/multiscaleStore.py
This is step 1 of improving web-multiscale UX on slow network connections.
Running the metadata check in a thread means ilastik doesn't freeze while waiting for potentially very slow responses. Currently, if the response is slow, the only way to cancel and try something else is to shut down ilastik entirely. With this PR, the user can cancel and re-open the dialog. Also added a warning in case of slow connection.
Snippet to run a slow server:
```
from http.server import HTTPServer, SimpleHTTPRequestHandler
from functools import partial
from pathlib import Path
import threading
import time
import socket
from typing import Tuple, Type
def wait_for_server(host_and_port: Tuple[str, int], timeout=5):
end_time = time.time() + timeout
while time.time() < end_time:
try:
with …
```
> Multiscale browser: Run metadata check in thread

- .circleci/config.yml
- conda-recipe/meta.yaml
- dev/environment-dev.yml
Switched to "orb"-based upload on circleCI. Trickiest part was setting the token in the right place and configuring circleci properly. Works now.
Edit: in the end the reason why codecov stopped working was that they now require token usage on protected branches. Technically this is solved by setting the token properly. However, they deprecated their bash script for upload (that was used before in our CI) and using the orb is the way.
> Try orb-based codecov upload

- lazyflow/operators/ioOperators/opFormattedDataExport.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpFormattedDataExport.py
We recommend our users convert Probabilities to `uint8` and normalize `0.0 ... 1.0` to `0 ... 255`.
It looks like some people would like to [normalize to `0 ... 100`](https://forum.image.sc/t/export-probabilities-as-8-bit-images/114083) so that pixels contain integer percentage probabilities. This is currently not possible - float imprecision isn't rounded but truncated during dtype conversion and as a consequence, some probability values like `14.99998` get mismapped to `14` instead of `15`.
I went with `numpy.round(a, 5)` to maintain existing behaviour as much as possible while fixing the specific issue for Probabilities, but I am wondering whether `numpy.round(a)` (without restricting to lower decimals) wouldn't actually be the correct thing to do here.
Fixes …
> Data Export: Round when normalizing float to int

- lazyflow/slot.py
- tests/test_lazyflow/test_operator.py
This sneaky bug is one of the reasons some ilastik workflows can't deal with input datasets changing shape: InputSlots with levels > 0 don't correctly trigger their unready signal. As a consequence, ops that have InputSlots with e.g. level=1 end up with their outputs still ready even if their inputs are unready. Example (note input on the left is red but output is white):
This is an `OpMultiArrayMerger` in object classification. I found this bug while trying to get multiple multiscales in different roles to work properly; it's a bit hard to reproduce through the gui.
I've added a couple of very simple tests to illustrate and reproduce the problem (is lazyflow core functionality really basically untested..?). The root cause of the issue is that when disconnecting, multi-inputs check their …
> Lazyflow.Slot: Fix multi-inputs not signalling unreadiness

- lazyflow/utility/io_util/OMEZarrStore.py
- lazyflow/utility/io_util/write_ome_zarr.py
- tests/test_ilastik/test_workflows/test_HeadlessPixelClassificationWorkflow.py
- tests/test_lazyflow/test_operators/test_ioOperators/testOpInputDataReader.py
I had included these kwargs going by the example of ome-zarr-py ([kwargs for v0.1](https://github.com/ome/ome-zarr-py/blob/ba98c05959283e3084eb30d6e5f1289e2fb2abff/ome_zarr/format.py#L138) and [for v0.4](https://github.com/ome/ome-zarr-py/blob/ba98c05959283e3084eb30d6e5f1289e2fb2abff/ome_zarr/format.py#L190)).
On the reading side, it's not necessary to specify these kwargs. `"."` is the default dimension separator up to and including module version `zarr=2.*`. When it is overriden by the writer to `dimension_separator="/"` (as one should for OME-Zarr since v0.2), zarr writes this into the `.zarray` file along with the other array metadata like shape, dtype and chunk shape. From there, zarr will find it when re-reading the same data.
On the writing side, we write OME-Zarr v0.4, which …
> OME-Zarr: Remove kwargs when reading

- lazyflow/utility/io_util/write_ome_zarr.py
- tests/test_lazyflow/test_utility/test_io_util/test_write_ome_zarr.py
😭 
* input has no channels -> KeyError "c"
* input has a bunch of downscales smaller than the working scale, but export gets cropped tiny -> matched downscale shapes can have 1 and 0 along xyz
> OME-Zarr export: Fix corner cases when matching input scales

- ilastik/applets/dataSelection/dataSelection.ui
- ilastik/applets/featureSelection/viewerControls.ui
- ilastik/applets/neuralNetwork/viewerControls.ui
- ilastik/applets/pixelClassification/viewerControls.ui
- ilastik/shell/gui/ilastikShell.py
- ilastik/shell/gui/shellWidgets.py
- ilastik/shell/gui/ui/ilastikShell.ui
This PR is mostly in preparation to add the secondary controls (currently the "label finder"). For this it will be nicer to have better control over the main splitter. I tried to hide direct widget access by the shell behind methods if practicable. Also the typing is now a bit nicer.
I also renamed some of the variables here because this was always confusing me:
* `sideSplitter` -> `mainSplitter`
* `mainSplitter` (applet + viewer controls were named that) -> `mainControls`
Here it might make sense to review in commit order.
> Refactor Main splitter from .ui definition to Python

- .github/workflows/core-conda-bld.yml
- .github/workflows/deploy.yml
- appveyor.yml
Atm it seems both miniforge and setup-miniconda ship a slightly-outdated `conda` 25.3.1 and a slightly-outdated `conda-libmamba-solver` 25.3.0 (I guess setup-miniconda has the same because it just installs miniforge...).
When the workflows update `conda` to 25.9.0, this removes a "Spinner" class that `conda-libmamba-solver` 25.3.0 depends on (cf. https://github.com/conda/conda/releases/tag/25.9.0: `Remove class conda.common.io.Spinner. Use conda.reporters.get_spinner instead. (https://github.com/conda/conda/pull/15221)`). This leads to:
```
>>> conda install -n base -c conda-forge setuptools_scm
Error while loading conda entry point: conda-libmamba-solver (cannot import name 'Spinner' from 'conda.common.io' (C:\Miniforge\Lib\site-packages\conda\common\io.py))
CondaValueError: You have …
```
> Fix conda CI
